
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const ReferentialIntegrityStrategy = {
  CASCADE: 'CASCADE',
  RESTRICT: 'RESTRICT',
  SET_NULL: 'SET_NULL',
  INVALIDATE: 'INVALIDATE'
} as const

export type ReferentialIntegrityStrategy = (typeof ReferentialIntegrityStrategy)[keyof typeof ReferentialIntegrityStrategy]
