
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AssetToAsset` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model AssetToAsset
 * 
 */
export type AssetToAssetModel = runtime.Types.Result.DefaultSelection<Prisma.$AssetToAssetPayload>

export type AggregateAssetToAsset = {
  _count: AssetToAssetCountAggregateOutputType | null
  _avg: AssetToAssetAvgAggregateOutputType | null
  _sum: AssetToAssetSumAggregateOutputType | null
  _min: AssetToAssetMinAggregateOutputType | null
  _max: AssetToAssetMaxAggregateOutputType | null
}

export type AssetToAssetAvgAggregateOutputType = {
  fromAssetId: number | null
  toAssetId: number | null
  fieldId: number | null
}

export type AssetToAssetSumAggregateOutputType = {
  fromAssetId: number | null
  toAssetId: number | null
  fieldId: number | null
}

export type AssetToAssetMinAggregateOutputType = {
  fromAssetId: number | null
  toAssetId: number | null
  fieldId: number | null
}

export type AssetToAssetMaxAggregateOutputType = {
  fromAssetId: number | null
  toAssetId: number | null
  fieldId: number | null
}

export type AssetToAssetCountAggregateOutputType = {
  fromAssetId: number
  toAssetId: number
  fieldId: number
  _all: number
}


export type AssetToAssetAvgAggregateInputType = {
  fromAssetId?: true
  toAssetId?: true
  fieldId?: true
}

export type AssetToAssetSumAggregateInputType = {
  fromAssetId?: true
  toAssetId?: true
  fieldId?: true
}

export type AssetToAssetMinAggregateInputType = {
  fromAssetId?: true
  toAssetId?: true
  fieldId?: true
}

export type AssetToAssetMaxAggregateInputType = {
  fromAssetId?: true
  toAssetId?: true
  fieldId?: true
}

export type AssetToAssetCountAggregateInputType = {
  fromAssetId?: true
  toAssetId?: true
  fieldId?: true
  _all?: true
}

export type AssetToAssetAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AssetToAsset to aggregate.
   */
  where?: Prisma.AssetToAssetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssetToAssets to fetch.
   */
  orderBy?: Prisma.AssetToAssetOrderByWithRelationInput | Prisma.AssetToAssetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AssetToAssetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssetToAssets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssetToAssets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AssetToAssets
  **/
  _count?: true | AssetToAssetCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AssetToAssetAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AssetToAssetSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AssetToAssetMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AssetToAssetMaxAggregateInputType
}

export type GetAssetToAssetAggregateType<T extends AssetToAssetAggregateArgs> = {
      [P in keyof T & keyof AggregateAssetToAsset]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAssetToAsset[P]>
    : Prisma.GetScalarType<T[P], AggregateAssetToAsset[P]>
}




export type AssetToAssetGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AssetToAssetWhereInput
  orderBy?: Prisma.AssetToAssetOrderByWithAggregationInput | Prisma.AssetToAssetOrderByWithAggregationInput[]
  by: Prisma.AssetToAssetScalarFieldEnum[] | Prisma.AssetToAssetScalarFieldEnum
  having?: Prisma.AssetToAssetScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AssetToAssetCountAggregateInputType | true
  _avg?: AssetToAssetAvgAggregateInputType
  _sum?: AssetToAssetSumAggregateInputType
  _min?: AssetToAssetMinAggregateInputType
  _max?: AssetToAssetMaxAggregateInputType
}

export type AssetToAssetGroupByOutputType = {
  fromAssetId: number
  toAssetId: number
  fieldId: number
  _count: AssetToAssetCountAggregateOutputType | null
  _avg: AssetToAssetAvgAggregateOutputType | null
  _sum: AssetToAssetSumAggregateOutputType | null
  _min: AssetToAssetMinAggregateOutputType | null
  _max: AssetToAssetMaxAggregateOutputType | null
}

type GetAssetToAssetGroupByPayload<T extends AssetToAssetGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AssetToAssetGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AssetToAssetGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AssetToAssetGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AssetToAssetGroupByOutputType[P]>
      }
    >
  >



export type AssetToAssetWhereInput = {
  AND?: Prisma.AssetToAssetWhereInput | Prisma.AssetToAssetWhereInput[]
  OR?: Prisma.AssetToAssetWhereInput[]
  NOT?: Prisma.AssetToAssetWhereInput | Prisma.AssetToAssetWhereInput[]
  fromAssetId?: Prisma.IntFilter<"AssetToAsset"> | number
  toAssetId?: Prisma.IntFilter<"AssetToAsset"> | number
  fieldId?: Prisma.IntFilter<"AssetToAsset"> | number
  fromAsset?: Prisma.XOR<Prisma.AssetScalarRelationFilter, Prisma.AssetWhereInput>
  toAsset?: Prisma.XOR<Prisma.AssetScalarRelationFilter, Prisma.AssetWhereInput>
}

export type AssetToAssetOrderByWithRelationInput = {
  fromAssetId?: Prisma.SortOrder
  toAssetId?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
  fromAsset?: Prisma.AssetOrderByWithRelationInput
  toAsset?: Prisma.AssetOrderByWithRelationInput
}

export type AssetToAssetWhereUniqueInput = Prisma.AtLeast<{
  fromAssetId_toAssetId_fieldId?: Prisma.AssetToAssetFromAssetIdToAssetIdFieldIdCompoundUniqueInput
  AND?: Prisma.AssetToAssetWhereInput | Prisma.AssetToAssetWhereInput[]
  OR?: Prisma.AssetToAssetWhereInput[]
  NOT?: Prisma.AssetToAssetWhereInput | Prisma.AssetToAssetWhereInput[]
  fromAssetId?: Prisma.IntFilter<"AssetToAsset"> | number
  toAssetId?: Prisma.IntFilter<"AssetToAsset"> | number
  fieldId?: Prisma.IntFilter<"AssetToAsset"> | number
  fromAsset?: Prisma.XOR<Prisma.AssetScalarRelationFilter, Prisma.AssetWhereInput>
  toAsset?: Prisma.XOR<Prisma.AssetScalarRelationFilter, Prisma.AssetWhereInput>
}, "fromAssetId_toAssetId_fieldId">

export type AssetToAssetOrderByWithAggregationInput = {
  fromAssetId?: Prisma.SortOrder
  toAssetId?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
  _count?: Prisma.AssetToAssetCountOrderByAggregateInput
  _avg?: Prisma.AssetToAssetAvgOrderByAggregateInput
  _max?: Prisma.AssetToAssetMaxOrderByAggregateInput
  _min?: Prisma.AssetToAssetMinOrderByAggregateInput
  _sum?: Prisma.AssetToAssetSumOrderByAggregateInput
}

export type AssetToAssetScalarWhereWithAggregatesInput = {
  AND?: Prisma.AssetToAssetScalarWhereWithAggregatesInput | Prisma.AssetToAssetScalarWhereWithAggregatesInput[]
  OR?: Prisma.AssetToAssetScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AssetToAssetScalarWhereWithAggregatesInput | Prisma.AssetToAssetScalarWhereWithAggregatesInput[]
  fromAssetId?: Prisma.IntWithAggregatesFilter<"AssetToAsset"> | number
  toAssetId?: Prisma.IntWithAggregatesFilter<"AssetToAsset"> | number
  fieldId?: Prisma.IntWithAggregatesFilter<"AssetToAsset"> | number
}

export type AssetToAssetCreateInput = {
  fieldId: number
  fromAsset: Prisma.AssetCreateNestedOneWithoutFromAssetToAssetsInput
  toAsset: Prisma.AssetCreateNestedOneWithoutToAssetToAssetsInput
}

export type AssetToAssetUncheckedCreateInput = {
  fromAssetId: number
  toAssetId: number
  fieldId: number
}

export type AssetToAssetUpdateInput = {
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
  fromAsset?: Prisma.AssetUpdateOneRequiredWithoutFromAssetToAssetsNestedInput
  toAsset?: Prisma.AssetUpdateOneRequiredWithoutToAssetToAssetsNestedInput
}

export type AssetToAssetUncheckedUpdateInput = {
  fromAssetId?: Prisma.IntFieldUpdateOperationsInput | number
  toAssetId?: Prisma.IntFieldUpdateOperationsInput | number
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AssetToAssetCreateManyInput = {
  fromAssetId: number
  toAssetId: number
  fieldId: number
}

export type AssetToAssetUpdateManyMutationInput = {
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AssetToAssetUncheckedUpdateManyInput = {
  fromAssetId?: Prisma.IntFieldUpdateOperationsInput | number
  toAssetId?: Prisma.IntFieldUpdateOperationsInput | number
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AssetToAssetListRelationFilter = {
  every?: Prisma.AssetToAssetWhereInput
  some?: Prisma.AssetToAssetWhereInput
  none?: Prisma.AssetToAssetWhereInput
}

export type AssetToAssetOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AssetToAssetFromAssetIdToAssetIdFieldIdCompoundUniqueInput = {
  fromAssetId: number
  toAssetId: number
  fieldId: number
}

export type AssetToAssetCountOrderByAggregateInput = {
  fromAssetId?: Prisma.SortOrder
  toAssetId?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
}

export type AssetToAssetAvgOrderByAggregateInput = {
  fromAssetId?: Prisma.SortOrder
  toAssetId?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
}

export type AssetToAssetMaxOrderByAggregateInput = {
  fromAssetId?: Prisma.SortOrder
  toAssetId?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
}

export type AssetToAssetMinOrderByAggregateInput = {
  fromAssetId?: Prisma.SortOrder
  toAssetId?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
}

export type AssetToAssetSumOrderByAggregateInput = {
  fromAssetId?: Prisma.SortOrder
  toAssetId?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
}

export type AssetToAssetCreateNestedManyWithoutFromAssetInput = {
  create?: Prisma.XOR<Prisma.AssetToAssetCreateWithoutFromAssetInput, Prisma.AssetToAssetUncheckedCreateWithoutFromAssetInput> | Prisma.AssetToAssetCreateWithoutFromAssetInput[] | Prisma.AssetToAssetUncheckedCreateWithoutFromAssetInput[]
  connectOrCreate?: Prisma.AssetToAssetCreateOrConnectWithoutFromAssetInput | Prisma.AssetToAssetCreateOrConnectWithoutFromAssetInput[]
  createMany?: Prisma.AssetToAssetCreateManyFromAssetInputEnvelope
  connect?: Prisma.AssetToAssetWhereUniqueInput | Prisma.AssetToAssetWhereUniqueInput[]
}

export type AssetToAssetCreateNestedManyWithoutToAssetInput = {
  create?: Prisma.XOR<Prisma.AssetToAssetCreateWithoutToAssetInput, Prisma.AssetToAssetUncheckedCreateWithoutToAssetInput> | Prisma.AssetToAssetCreateWithoutToAssetInput[] | Prisma.AssetToAssetUncheckedCreateWithoutToAssetInput[]
  connectOrCreate?: Prisma.AssetToAssetCreateOrConnectWithoutToAssetInput | Prisma.AssetToAssetCreateOrConnectWithoutToAssetInput[]
  createMany?: Prisma.AssetToAssetCreateManyToAssetInputEnvelope
  connect?: Prisma.AssetToAssetWhereUniqueInput | Prisma.AssetToAssetWhereUniqueInput[]
}

export type AssetToAssetUncheckedCreateNestedManyWithoutFromAssetInput = {
  create?: Prisma.XOR<Prisma.AssetToAssetCreateWithoutFromAssetInput, Prisma.AssetToAssetUncheckedCreateWithoutFromAssetInput> | Prisma.AssetToAssetCreateWithoutFromAssetInput[] | Prisma.AssetToAssetUncheckedCreateWithoutFromAssetInput[]
  connectOrCreate?: Prisma.AssetToAssetCreateOrConnectWithoutFromAssetInput | Prisma.AssetToAssetCreateOrConnectWithoutFromAssetInput[]
  createMany?: Prisma.AssetToAssetCreateManyFromAssetInputEnvelope
  connect?: Prisma.AssetToAssetWhereUniqueInput | Prisma.AssetToAssetWhereUniqueInput[]
}

export type AssetToAssetUncheckedCreateNestedManyWithoutToAssetInput = {
  create?: Prisma.XOR<Prisma.AssetToAssetCreateWithoutToAssetInput, Prisma.AssetToAssetUncheckedCreateWithoutToAssetInput> | Prisma.AssetToAssetCreateWithoutToAssetInput[] | Prisma.AssetToAssetUncheckedCreateWithoutToAssetInput[]
  connectOrCreate?: Prisma.AssetToAssetCreateOrConnectWithoutToAssetInput | Prisma.AssetToAssetCreateOrConnectWithoutToAssetInput[]
  createMany?: Prisma.AssetToAssetCreateManyToAssetInputEnvelope
  connect?: Prisma.AssetToAssetWhereUniqueInput | Prisma.AssetToAssetWhereUniqueInput[]
}

export type AssetToAssetUpdateManyWithoutFromAssetNestedInput = {
  create?: Prisma.XOR<Prisma.AssetToAssetCreateWithoutFromAssetInput, Prisma.AssetToAssetUncheckedCreateWithoutFromAssetInput> | Prisma.AssetToAssetCreateWithoutFromAssetInput[] | Prisma.AssetToAssetUncheckedCreateWithoutFromAssetInput[]
  connectOrCreate?: Prisma.AssetToAssetCreateOrConnectWithoutFromAssetInput | Prisma.AssetToAssetCreateOrConnectWithoutFromAssetInput[]
  upsert?: Prisma.AssetToAssetUpsertWithWhereUniqueWithoutFromAssetInput | Prisma.AssetToAssetUpsertWithWhereUniqueWithoutFromAssetInput[]
  createMany?: Prisma.AssetToAssetCreateManyFromAssetInputEnvelope
  set?: Prisma.AssetToAssetWhereUniqueInput | Prisma.AssetToAssetWhereUniqueInput[]
  disconnect?: Prisma.AssetToAssetWhereUniqueInput | Prisma.AssetToAssetWhereUniqueInput[]
  delete?: Prisma.AssetToAssetWhereUniqueInput | Prisma.AssetToAssetWhereUniqueInput[]
  connect?: Prisma.AssetToAssetWhereUniqueInput | Prisma.AssetToAssetWhereUniqueInput[]
  update?: Prisma.AssetToAssetUpdateWithWhereUniqueWithoutFromAssetInput | Prisma.AssetToAssetUpdateWithWhereUniqueWithoutFromAssetInput[]
  updateMany?: Prisma.AssetToAssetUpdateManyWithWhereWithoutFromAssetInput | Prisma.AssetToAssetUpdateManyWithWhereWithoutFromAssetInput[]
  deleteMany?: Prisma.AssetToAssetScalarWhereInput | Prisma.AssetToAssetScalarWhereInput[]
}

export type AssetToAssetUpdateManyWithoutToAssetNestedInput = {
  create?: Prisma.XOR<Prisma.AssetToAssetCreateWithoutToAssetInput, Prisma.AssetToAssetUncheckedCreateWithoutToAssetInput> | Prisma.AssetToAssetCreateWithoutToAssetInput[] | Prisma.AssetToAssetUncheckedCreateWithoutToAssetInput[]
  connectOrCreate?: Prisma.AssetToAssetCreateOrConnectWithoutToAssetInput | Prisma.AssetToAssetCreateOrConnectWithoutToAssetInput[]
  upsert?: Prisma.AssetToAssetUpsertWithWhereUniqueWithoutToAssetInput | Prisma.AssetToAssetUpsertWithWhereUniqueWithoutToAssetInput[]
  createMany?: Prisma.AssetToAssetCreateManyToAssetInputEnvelope
  set?: Prisma.AssetToAssetWhereUniqueInput | Prisma.AssetToAssetWhereUniqueInput[]
  disconnect?: Prisma.AssetToAssetWhereUniqueInput | Prisma.AssetToAssetWhereUniqueInput[]
  delete?: Prisma.AssetToAssetWhereUniqueInput | Prisma.AssetToAssetWhereUniqueInput[]
  connect?: Prisma.AssetToAssetWhereUniqueInput | Prisma.AssetToAssetWhereUniqueInput[]
  update?: Prisma.AssetToAssetUpdateWithWhereUniqueWithoutToAssetInput | Prisma.AssetToAssetUpdateWithWhereUniqueWithoutToAssetInput[]
  updateMany?: Prisma.AssetToAssetUpdateManyWithWhereWithoutToAssetInput | Prisma.AssetToAssetUpdateManyWithWhereWithoutToAssetInput[]
  deleteMany?: Prisma.AssetToAssetScalarWhereInput | Prisma.AssetToAssetScalarWhereInput[]
}

export type AssetToAssetUncheckedUpdateManyWithoutFromAssetNestedInput = {
  create?: Prisma.XOR<Prisma.AssetToAssetCreateWithoutFromAssetInput, Prisma.AssetToAssetUncheckedCreateWithoutFromAssetInput> | Prisma.AssetToAssetCreateWithoutFromAssetInput[] | Prisma.AssetToAssetUncheckedCreateWithoutFromAssetInput[]
  connectOrCreate?: Prisma.AssetToAssetCreateOrConnectWithoutFromAssetInput | Prisma.AssetToAssetCreateOrConnectWithoutFromAssetInput[]
  upsert?: Prisma.AssetToAssetUpsertWithWhereUniqueWithoutFromAssetInput | Prisma.AssetToAssetUpsertWithWhereUniqueWithoutFromAssetInput[]
  createMany?: Prisma.AssetToAssetCreateManyFromAssetInputEnvelope
  set?: Prisma.AssetToAssetWhereUniqueInput | Prisma.AssetToAssetWhereUniqueInput[]
  disconnect?: Prisma.AssetToAssetWhereUniqueInput | Prisma.AssetToAssetWhereUniqueInput[]
  delete?: Prisma.AssetToAssetWhereUniqueInput | Prisma.AssetToAssetWhereUniqueInput[]
  connect?: Prisma.AssetToAssetWhereUniqueInput | Prisma.AssetToAssetWhereUniqueInput[]
  update?: Prisma.AssetToAssetUpdateWithWhereUniqueWithoutFromAssetInput | Prisma.AssetToAssetUpdateWithWhereUniqueWithoutFromAssetInput[]
  updateMany?: Prisma.AssetToAssetUpdateManyWithWhereWithoutFromAssetInput | Prisma.AssetToAssetUpdateManyWithWhereWithoutFromAssetInput[]
  deleteMany?: Prisma.AssetToAssetScalarWhereInput | Prisma.AssetToAssetScalarWhereInput[]
}

export type AssetToAssetUncheckedUpdateManyWithoutToAssetNestedInput = {
  create?: Prisma.XOR<Prisma.AssetToAssetCreateWithoutToAssetInput, Prisma.AssetToAssetUncheckedCreateWithoutToAssetInput> | Prisma.AssetToAssetCreateWithoutToAssetInput[] | Prisma.AssetToAssetUncheckedCreateWithoutToAssetInput[]
  connectOrCreate?: Prisma.AssetToAssetCreateOrConnectWithoutToAssetInput | Prisma.AssetToAssetCreateOrConnectWithoutToAssetInput[]
  upsert?: Prisma.AssetToAssetUpsertWithWhereUniqueWithoutToAssetInput | Prisma.AssetToAssetUpsertWithWhereUniqueWithoutToAssetInput[]
  createMany?: Prisma.AssetToAssetCreateManyToAssetInputEnvelope
  set?: Prisma.AssetToAssetWhereUniqueInput | Prisma.AssetToAssetWhereUniqueInput[]
  disconnect?: Prisma.AssetToAssetWhereUniqueInput | Prisma.AssetToAssetWhereUniqueInput[]
  delete?: Prisma.AssetToAssetWhereUniqueInput | Prisma.AssetToAssetWhereUniqueInput[]
  connect?: Prisma.AssetToAssetWhereUniqueInput | Prisma.AssetToAssetWhereUniqueInput[]
  update?: Prisma.AssetToAssetUpdateWithWhereUniqueWithoutToAssetInput | Prisma.AssetToAssetUpdateWithWhereUniqueWithoutToAssetInput[]
  updateMany?: Prisma.AssetToAssetUpdateManyWithWhereWithoutToAssetInput | Prisma.AssetToAssetUpdateManyWithWhereWithoutToAssetInput[]
  deleteMany?: Prisma.AssetToAssetScalarWhereInput | Prisma.AssetToAssetScalarWhereInput[]
}

export type AssetToAssetCreateWithoutFromAssetInput = {
  fieldId: number
  toAsset: Prisma.AssetCreateNestedOneWithoutToAssetToAssetsInput
}

export type AssetToAssetUncheckedCreateWithoutFromAssetInput = {
  toAssetId: number
  fieldId: number
}

export type AssetToAssetCreateOrConnectWithoutFromAssetInput = {
  where: Prisma.AssetToAssetWhereUniqueInput
  create: Prisma.XOR<Prisma.AssetToAssetCreateWithoutFromAssetInput, Prisma.AssetToAssetUncheckedCreateWithoutFromAssetInput>
}

export type AssetToAssetCreateManyFromAssetInputEnvelope = {
  data: Prisma.AssetToAssetCreateManyFromAssetInput | Prisma.AssetToAssetCreateManyFromAssetInput[]
  skipDuplicates?: boolean
}

export type AssetToAssetCreateWithoutToAssetInput = {
  fieldId: number
  fromAsset: Prisma.AssetCreateNestedOneWithoutFromAssetToAssetsInput
}

export type AssetToAssetUncheckedCreateWithoutToAssetInput = {
  fromAssetId: number
  fieldId: number
}

export type AssetToAssetCreateOrConnectWithoutToAssetInput = {
  where: Prisma.AssetToAssetWhereUniqueInput
  create: Prisma.XOR<Prisma.AssetToAssetCreateWithoutToAssetInput, Prisma.AssetToAssetUncheckedCreateWithoutToAssetInput>
}

export type AssetToAssetCreateManyToAssetInputEnvelope = {
  data: Prisma.AssetToAssetCreateManyToAssetInput | Prisma.AssetToAssetCreateManyToAssetInput[]
  skipDuplicates?: boolean
}

export type AssetToAssetUpsertWithWhereUniqueWithoutFromAssetInput = {
  where: Prisma.AssetToAssetWhereUniqueInput
  update: Prisma.XOR<Prisma.AssetToAssetUpdateWithoutFromAssetInput, Prisma.AssetToAssetUncheckedUpdateWithoutFromAssetInput>
  create: Prisma.XOR<Prisma.AssetToAssetCreateWithoutFromAssetInput, Prisma.AssetToAssetUncheckedCreateWithoutFromAssetInput>
}

export type AssetToAssetUpdateWithWhereUniqueWithoutFromAssetInput = {
  where: Prisma.AssetToAssetWhereUniqueInput
  data: Prisma.XOR<Prisma.AssetToAssetUpdateWithoutFromAssetInput, Prisma.AssetToAssetUncheckedUpdateWithoutFromAssetInput>
}

export type AssetToAssetUpdateManyWithWhereWithoutFromAssetInput = {
  where: Prisma.AssetToAssetScalarWhereInput
  data: Prisma.XOR<Prisma.AssetToAssetUpdateManyMutationInput, Prisma.AssetToAssetUncheckedUpdateManyWithoutFromAssetInput>
}

export type AssetToAssetScalarWhereInput = {
  AND?: Prisma.AssetToAssetScalarWhereInput | Prisma.AssetToAssetScalarWhereInput[]
  OR?: Prisma.AssetToAssetScalarWhereInput[]
  NOT?: Prisma.AssetToAssetScalarWhereInput | Prisma.AssetToAssetScalarWhereInput[]
  fromAssetId?: Prisma.IntFilter<"AssetToAsset"> | number
  toAssetId?: Prisma.IntFilter<"AssetToAsset"> | number
  fieldId?: Prisma.IntFilter<"AssetToAsset"> | number
}

export type AssetToAssetUpsertWithWhereUniqueWithoutToAssetInput = {
  where: Prisma.AssetToAssetWhereUniqueInput
  update: Prisma.XOR<Prisma.AssetToAssetUpdateWithoutToAssetInput, Prisma.AssetToAssetUncheckedUpdateWithoutToAssetInput>
  create: Prisma.XOR<Prisma.AssetToAssetCreateWithoutToAssetInput, Prisma.AssetToAssetUncheckedCreateWithoutToAssetInput>
}

export type AssetToAssetUpdateWithWhereUniqueWithoutToAssetInput = {
  where: Prisma.AssetToAssetWhereUniqueInput
  data: Prisma.XOR<Prisma.AssetToAssetUpdateWithoutToAssetInput, Prisma.AssetToAssetUncheckedUpdateWithoutToAssetInput>
}

export type AssetToAssetUpdateManyWithWhereWithoutToAssetInput = {
  where: Prisma.AssetToAssetScalarWhereInput
  data: Prisma.XOR<Prisma.AssetToAssetUpdateManyMutationInput, Prisma.AssetToAssetUncheckedUpdateManyWithoutToAssetInput>
}

export type AssetToAssetCreateManyFromAssetInput = {
  toAssetId: number
  fieldId: number
}

export type AssetToAssetCreateManyToAssetInput = {
  fromAssetId: number
  fieldId: number
}

export type AssetToAssetUpdateWithoutFromAssetInput = {
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
  toAsset?: Prisma.AssetUpdateOneRequiredWithoutToAssetToAssetsNestedInput
}

export type AssetToAssetUncheckedUpdateWithoutFromAssetInput = {
  toAssetId?: Prisma.IntFieldUpdateOperationsInput | number
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AssetToAssetUncheckedUpdateManyWithoutFromAssetInput = {
  toAssetId?: Prisma.IntFieldUpdateOperationsInput | number
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AssetToAssetUpdateWithoutToAssetInput = {
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
  fromAsset?: Prisma.AssetUpdateOneRequiredWithoutFromAssetToAssetsNestedInput
}

export type AssetToAssetUncheckedUpdateWithoutToAssetInput = {
  fromAssetId?: Prisma.IntFieldUpdateOperationsInput | number
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AssetToAssetUncheckedUpdateManyWithoutToAssetInput = {
  fromAssetId?: Prisma.IntFieldUpdateOperationsInput | number
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
}



export type AssetToAssetSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  fromAssetId?: boolean
  toAssetId?: boolean
  fieldId?: boolean
  fromAsset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
  toAsset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assetToAsset"]>

export type AssetToAssetSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  fromAssetId?: boolean
  toAssetId?: boolean
  fieldId?: boolean
  fromAsset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
  toAsset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assetToAsset"]>

export type AssetToAssetSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  fromAssetId?: boolean
  toAssetId?: boolean
  fieldId?: boolean
  fromAsset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
  toAsset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assetToAsset"]>

export type AssetToAssetSelectScalar = {
  fromAssetId?: boolean
  toAssetId?: boolean
  fieldId?: boolean
}

export type AssetToAssetOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"fromAssetId" | "toAssetId" | "fieldId", ExtArgs["result"]["assetToAsset"]>
export type AssetToAssetInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  fromAsset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
  toAsset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
}
export type AssetToAssetIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  fromAsset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
  toAsset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
}
export type AssetToAssetIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  fromAsset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
  toAsset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
}

export type $AssetToAssetPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AssetToAsset"
  objects: {
    fromAsset: Prisma.$AssetPayload<ExtArgs>
    toAsset: Prisma.$AssetPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    fromAssetId: number
    toAssetId: number
    fieldId: number
  }, ExtArgs["result"]["assetToAsset"]>
  composites: {}
}

export type AssetToAssetGetPayload<S extends boolean | null | undefined | AssetToAssetDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AssetToAssetPayload, S>

export type AssetToAssetCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AssetToAssetFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AssetToAssetCountAggregateInputType | true
  }

export interface AssetToAssetDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AssetToAsset'], meta: { name: 'AssetToAsset' } }
  /**
   * Find zero or one AssetToAsset that matches the filter.
   * @param {AssetToAssetFindUniqueArgs} args - Arguments to find a AssetToAsset
   * @example
   * // Get one AssetToAsset
   * const assetToAsset = await prisma.assetToAsset.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AssetToAssetFindUniqueArgs>(args: Prisma.SelectSubset<T, AssetToAssetFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AssetToAssetClient<runtime.Types.Result.GetResult<Prisma.$AssetToAssetPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AssetToAsset that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AssetToAssetFindUniqueOrThrowArgs} args - Arguments to find a AssetToAsset
   * @example
   * // Get one AssetToAsset
   * const assetToAsset = await prisma.assetToAsset.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AssetToAssetFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AssetToAssetFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AssetToAssetClient<runtime.Types.Result.GetResult<Prisma.$AssetToAssetPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AssetToAsset that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetToAssetFindFirstArgs} args - Arguments to find a AssetToAsset
   * @example
   * // Get one AssetToAsset
   * const assetToAsset = await prisma.assetToAsset.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AssetToAssetFindFirstArgs>(args?: Prisma.SelectSubset<T, AssetToAssetFindFirstArgs<ExtArgs>>): Prisma.Prisma__AssetToAssetClient<runtime.Types.Result.GetResult<Prisma.$AssetToAssetPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AssetToAsset that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetToAssetFindFirstOrThrowArgs} args - Arguments to find a AssetToAsset
   * @example
   * // Get one AssetToAsset
   * const assetToAsset = await prisma.assetToAsset.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AssetToAssetFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AssetToAssetFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AssetToAssetClient<runtime.Types.Result.GetResult<Prisma.$AssetToAssetPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AssetToAssets that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetToAssetFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AssetToAssets
   * const assetToAssets = await prisma.assetToAsset.findMany()
   * 
   * // Get first 10 AssetToAssets
   * const assetToAssets = await prisma.assetToAsset.findMany({ take: 10 })
   * 
   * // Only select the `fromAssetId`
   * const assetToAssetWithFromAssetIdOnly = await prisma.assetToAsset.findMany({ select: { fromAssetId: true } })
   * 
   */
  findMany<T extends AssetToAssetFindManyArgs>(args?: Prisma.SelectSubset<T, AssetToAssetFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssetToAssetPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AssetToAsset.
   * @param {AssetToAssetCreateArgs} args - Arguments to create a AssetToAsset.
   * @example
   * // Create one AssetToAsset
   * const AssetToAsset = await prisma.assetToAsset.create({
   *   data: {
   *     // ... data to create a AssetToAsset
   *   }
   * })
   * 
   */
  create<T extends AssetToAssetCreateArgs>(args: Prisma.SelectSubset<T, AssetToAssetCreateArgs<ExtArgs>>): Prisma.Prisma__AssetToAssetClient<runtime.Types.Result.GetResult<Prisma.$AssetToAssetPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AssetToAssets.
   * @param {AssetToAssetCreateManyArgs} args - Arguments to create many AssetToAssets.
   * @example
   * // Create many AssetToAssets
   * const assetToAsset = await prisma.assetToAsset.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AssetToAssetCreateManyArgs>(args?: Prisma.SelectSubset<T, AssetToAssetCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AssetToAssets and returns the data saved in the database.
   * @param {AssetToAssetCreateManyAndReturnArgs} args - Arguments to create many AssetToAssets.
   * @example
   * // Create many AssetToAssets
   * const assetToAsset = await prisma.assetToAsset.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AssetToAssets and only return the `fromAssetId`
   * const assetToAssetWithFromAssetIdOnly = await prisma.assetToAsset.createManyAndReturn({
   *   select: { fromAssetId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AssetToAssetCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AssetToAssetCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssetToAssetPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AssetToAsset.
   * @param {AssetToAssetDeleteArgs} args - Arguments to delete one AssetToAsset.
   * @example
   * // Delete one AssetToAsset
   * const AssetToAsset = await prisma.assetToAsset.delete({
   *   where: {
   *     // ... filter to delete one AssetToAsset
   *   }
   * })
   * 
   */
  delete<T extends AssetToAssetDeleteArgs>(args: Prisma.SelectSubset<T, AssetToAssetDeleteArgs<ExtArgs>>): Prisma.Prisma__AssetToAssetClient<runtime.Types.Result.GetResult<Prisma.$AssetToAssetPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AssetToAsset.
   * @param {AssetToAssetUpdateArgs} args - Arguments to update one AssetToAsset.
   * @example
   * // Update one AssetToAsset
   * const assetToAsset = await prisma.assetToAsset.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AssetToAssetUpdateArgs>(args: Prisma.SelectSubset<T, AssetToAssetUpdateArgs<ExtArgs>>): Prisma.Prisma__AssetToAssetClient<runtime.Types.Result.GetResult<Prisma.$AssetToAssetPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AssetToAssets.
   * @param {AssetToAssetDeleteManyArgs} args - Arguments to filter AssetToAssets to delete.
   * @example
   * // Delete a few AssetToAssets
   * const { count } = await prisma.assetToAsset.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AssetToAssetDeleteManyArgs>(args?: Prisma.SelectSubset<T, AssetToAssetDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AssetToAssets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetToAssetUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AssetToAssets
   * const assetToAsset = await prisma.assetToAsset.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AssetToAssetUpdateManyArgs>(args: Prisma.SelectSubset<T, AssetToAssetUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AssetToAssets and returns the data updated in the database.
   * @param {AssetToAssetUpdateManyAndReturnArgs} args - Arguments to update many AssetToAssets.
   * @example
   * // Update many AssetToAssets
   * const assetToAsset = await prisma.assetToAsset.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AssetToAssets and only return the `fromAssetId`
   * const assetToAssetWithFromAssetIdOnly = await prisma.assetToAsset.updateManyAndReturn({
   *   select: { fromAssetId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AssetToAssetUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AssetToAssetUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssetToAssetPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AssetToAsset.
   * @param {AssetToAssetUpsertArgs} args - Arguments to update or create a AssetToAsset.
   * @example
   * // Update or create a AssetToAsset
   * const assetToAsset = await prisma.assetToAsset.upsert({
   *   create: {
   *     // ... data to create a AssetToAsset
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AssetToAsset we want to update
   *   }
   * })
   */
  upsert<T extends AssetToAssetUpsertArgs>(args: Prisma.SelectSubset<T, AssetToAssetUpsertArgs<ExtArgs>>): Prisma.Prisma__AssetToAssetClient<runtime.Types.Result.GetResult<Prisma.$AssetToAssetPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AssetToAssets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetToAssetCountArgs} args - Arguments to filter AssetToAssets to count.
   * @example
   * // Count the number of AssetToAssets
   * const count = await prisma.assetToAsset.count({
   *   where: {
   *     // ... the filter for the AssetToAssets we want to count
   *   }
   * })
  **/
  count<T extends AssetToAssetCountArgs>(
    args?: Prisma.Subset<T, AssetToAssetCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AssetToAssetCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AssetToAsset.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetToAssetAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AssetToAssetAggregateArgs>(args: Prisma.Subset<T, AssetToAssetAggregateArgs>): Prisma.PrismaPromise<GetAssetToAssetAggregateType<T>>

  /**
   * Group by AssetToAsset.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetToAssetGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AssetToAssetGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AssetToAssetGroupByArgs['orderBy'] }
      : { orderBy?: AssetToAssetGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AssetToAssetGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAssetToAssetGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AssetToAsset model
 */
readonly fields: AssetToAssetFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AssetToAsset.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AssetToAssetClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  fromAsset<T extends Prisma.AssetDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AssetDefaultArgs<ExtArgs>>): Prisma.Prisma__AssetClient<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  toAsset<T extends Prisma.AssetDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AssetDefaultArgs<ExtArgs>>): Prisma.Prisma__AssetClient<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AssetToAsset model
 */
export interface AssetToAssetFieldRefs {
  readonly fromAssetId: Prisma.FieldRef<"AssetToAsset", 'Int'>
  readonly toAssetId: Prisma.FieldRef<"AssetToAsset", 'Int'>
  readonly fieldId: Prisma.FieldRef<"AssetToAsset", 'Int'>
}
    

// Custom InputTypes
/**
 * AssetToAsset findUnique
 */
export type AssetToAssetFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetToAsset
   */
  select?: Prisma.AssetToAssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetToAsset
   */
  omit?: Prisma.AssetToAssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetToAssetInclude<ExtArgs> | null
  /**
   * Filter, which AssetToAsset to fetch.
   */
  where: Prisma.AssetToAssetWhereUniqueInput
}

/**
 * AssetToAsset findUniqueOrThrow
 */
export type AssetToAssetFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetToAsset
   */
  select?: Prisma.AssetToAssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetToAsset
   */
  omit?: Prisma.AssetToAssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetToAssetInclude<ExtArgs> | null
  /**
   * Filter, which AssetToAsset to fetch.
   */
  where: Prisma.AssetToAssetWhereUniqueInput
}

/**
 * AssetToAsset findFirst
 */
export type AssetToAssetFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetToAsset
   */
  select?: Prisma.AssetToAssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetToAsset
   */
  omit?: Prisma.AssetToAssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetToAssetInclude<ExtArgs> | null
  /**
   * Filter, which AssetToAsset to fetch.
   */
  where?: Prisma.AssetToAssetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssetToAssets to fetch.
   */
  orderBy?: Prisma.AssetToAssetOrderByWithRelationInput | Prisma.AssetToAssetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AssetToAssets.
   */
  cursor?: Prisma.AssetToAssetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssetToAssets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssetToAssets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AssetToAssets.
   */
  distinct?: Prisma.AssetToAssetScalarFieldEnum | Prisma.AssetToAssetScalarFieldEnum[]
}

/**
 * AssetToAsset findFirstOrThrow
 */
export type AssetToAssetFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetToAsset
   */
  select?: Prisma.AssetToAssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetToAsset
   */
  omit?: Prisma.AssetToAssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetToAssetInclude<ExtArgs> | null
  /**
   * Filter, which AssetToAsset to fetch.
   */
  where?: Prisma.AssetToAssetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssetToAssets to fetch.
   */
  orderBy?: Prisma.AssetToAssetOrderByWithRelationInput | Prisma.AssetToAssetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AssetToAssets.
   */
  cursor?: Prisma.AssetToAssetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssetToAssets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssetToAssets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AssetToAssets.
   */
  distinct?: Prisma.AssetToAssetScalarFieldEnum | Prisma.AssetToAssetScalarFieldEnum[]
}

/**
 * AssetToAsset findMany
 */
export type AssetToAssetFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetToAsset
   */
  select?: Prisma.AssetToAssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetToAsset
   */
  omit?: Prisma.AssetToAssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetToAssetInclude<ExtArgs> | null
  /**
   * Filter, which AssetToAssets to fetch.
   */
  where?: Prisma.AssetToAssetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssetToAssets to fetch.
   */
  orderBy?: Prisma.AssetToAssetOrderByWithRelationInput | Prisma.AssetToAssetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AssetToAssets.
   */
  cursor?: Prisma.AssetToAssetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssetToAssets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssetToAssets.
   */
  skip?: number
  distinct?: Prisma.AssetToAssetScalarFieldEnum | Prisma.AssetToAssetScalarFieldEnum[]
}

/**
 * AssetToAsset create
 */
export type AssetToAssetCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetToAsset
   */
  select?: Prisma.AssetToAssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetToAsset
   */
  omit?: Prisma.AssetToAssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetToAssetInclude<ExtArgs> | null
  /**
   * The data needed to create a AssetToAsset.
   */
  data: Prisma.XOR<Prisma.AssetToAssetCreateInput, Prisma.AssetToAssetUncheckedCreateInput>
}

/**
 * AssetToAsset createMany
 */
export type AssetToAssetCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AssetToAssets.
   */
  data: Prisma.AssetToAssetCreateManyInput | Prisma.AssetToAssetCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AssetToAsset createManyAndReturn
 */
export type AssetToAssetCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetToAsset
   */
  select?: Prisma.AssetToAssetSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AssetToAsset
   */
  omit?: Prisma.AssetToAssetOmit<ExtArgs> | null
  /**
   * The data used to create many AssetToAssets.
   */
  data: Prisma.AssetToAssetCreateManyInput | Prisma.AssetToAssetCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetToAssetIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AssetToAsset update
 */
export type AssetToAssetUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetToAsset
   */
  select?: Prisma.AssetToAssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetToAsset
   */
  omit?: Prisma.AssetToAssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetToAssetInclude<ExtArgs> | null
  /**
   * The data needed to update a AssetToAsset.
   */
  data: Prisma.XOR<Prisma.AssetToAssetUpdateInput, Prisma.AssetToAssetUncheckedUpdateInput>
  /**
   * Choose, which AssetToAsset to update.
   */
  where: Prisma.AssetToAssetWhereUniqueInput
}

/**
 * AssetToAsset updateMany
 */
export type AssetToAssetUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AssetToAssets.
   */
  data: Prisma.XOR<Prisma.AssetToAssetUpdateManyMutationInput, Prisma.AssetToAssetUncheckedUpdateManyInput>
  /**
   * Filter which AssetToAssets to update
   */
  where?: Prisma.AssetToAssetWhereInput
  /**
   * Limit how many AssetToAssets to update.
   */
  limit?: number
}

/**
 * AssetToAsset updateManyAndReturn
 */
export type AssetToAssetUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetToAsset
   */
  select?: Prisma.AssetToAssetSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AssetToAsset
   */
  omit?: Prisma.AssetToAssetOmit<ExtArgs> | null
  /**
   * The data used to update AssetToAssets.
   */
  data: Prisma.XOR<Prisma.AssetToAssetUpdateManyMutationInput, Prisma.AssetToAssetUncheckedUpdateManyInput>
  /**
   * Filter which AssetToAssets to update
   */
  where?: Prisma.AssetToAssetWhereInput
  /**
   * Limit how many AssetToAssets to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetToAssetIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AssetToAsset upsert
 */
export type AssetToAssetUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetToAsset
   */
  select?: Prisma.AssetToAssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetToAsset
   */
  omit?: Prisma.AssetToAssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetToAssetInclude<ExtArgs> | null
  /**
   * The filter to search for the AssetToAsset to update in case it exists.
   */
  where: Prisma.AssetToAssetWhereUniqueInput
  /**
   * In case the AssetToAsset found by the `where` argument doesn't exist, create a new AssetToAsset with this data.
   */
  create: Prisma.XOR<Prisma.AssetToAssetCreateInput, Prisma.AssetToAssetUncheckedCreateInput>
  /**
   * In case the AssetToAsset was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AssetToAssetUpdateInput, Prisma.AssetToAssetUncheckedUpdateInput>
}

/**
 * AssetToAsset delete
 */
export type AssetToAssetDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetToAsset
   */
  select?: Prisma.AssetToAssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetToAsset
   */
  omit?: Prisma.AssetToAssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetToAssetInclude<ExtArgs> | null
  /**
   * Filter which AssetToAsset to delete.
   */
  where: Prisma.AssetToAssetWhereUniqueInput
}

/**
 * AssetToAsset deleteMany
 */
export type AssetToAssetDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AssetToAssets to delete
   */
  where?: Prisma.AssetToAssetWhereInput
  /**
   * Limit how many AssetToAssets to delete.
   */
  limit?: number
}

/**
 * AssetToAsset without action
 */
export type AssetToAssetDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetToAsset
   */
  select?: Prisma.AssetToAssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetToAsset
   */
  omit?: Prisma.AssetToAssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetToAssetInclude<ExtArgs> | null
}
