
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AssetTypeField` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model AssetTypeField
 * 
 */
export type AssetTypeFieldModel = runtime.Types.Result.DefaultSelection<Prisma.$AssetTypeFieldPayload>

export type AggregateAssetTypeField = {
  _count: AssetTypeFieldCountAggregateOutputType | null
  _avg: AssetTypeFieldAvgAggregateOutputType | null
  _sum: AssetTypeFieldSumAggregateOutputType | null
  _min: AssetTypeFieldMinAggregateOutputType | null
  _max: AssetTypeFieldMaxAggregateOutputType | null
}

export type AssetTypeFieldAvgAggregateOutputType = {
  assetTypeId: number | null
  fieldId: number | null
  fieldTypeId: number | null
}

export type AssetTypeFieldSumAggregateOutputType = {
  assetTypeId: number | null
  fieldId: number | null
  fieldTypeId: number | null
}

export type AssetTypeFieldMinAggregateOutputType = {
  assetTypeId: number | null
  fieldId: number | null
  fieldTypeId: number | null
  required: boolean | null
  name: string | null
  referentialIntegrityStrategy: $Enums.ReferentialIntegrityStrategy | null
  allowMultipleRelations: boolean | null
}

export type AssetTypeFieldMaxAggregateOutputType = {
  assetTypeId: number | null
  fieldId: number | null
  fieldTypeId: number | null
  required: boolean | null
  name: string | null
  referentialIntegrityStrategy: $Enums.ReferentialIntegrityStrategy | null
  allowMultipleRelations: boolean | null
}

export type AssetTypeFieldCountAggregateOutputType = {
  assetTypeId: number
  fieldId: number
  fieldTypeId: number
  required: number
  name: number
  items: number
  referentialIntegrityStrategy: number
  allowMultipleRelations: number
  _all: number
}


export type AssetTypeFieldAvgAggregateInputType = {
  assetTypeId?: true
  fieldId?: true
  fieldTypeId?: true
}

export type AssetTypeFieldSumAggregateInputType = {
  assetTypeId?: true
  fieldId?: true
  fieldTypeId?: true
}

export type AssetTypeFieldMinAggregateInputType = {
  assetTypeId?: true
  fieldId?: true
  fieldTypeId?: true
  required?: true
  name?: true
  referentialIntegrityStrategy?: true
  allowMultipleRelations?: true
}

export type AssetTypeFieldMaxAggregateInputType = {
  assetTypeId?: true
  fieldId?: true
  fieldTypeId?: true
  required?: true
  name?: true
  referentialIntegrityStrategy?: true
  allowMultipleRelations?: true
}

export type AssetTypeFieldCountAggregateInputType = {
  assetTypeId?: true
  fieldId?: true
  fieldTypeId?: true
  required?: true
  name?: true
  items?: true
  referentialIntegrityStrategy?: true
  allowMultipleRelations?: true
  _all?: true
}

export type AssetTypeFieldAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AssetTypeField to aggregate.
   */
  where?: Prisma.AssetTypeFieldWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssetTypeFields to fetch.
   */
  orderBy?: Prisma.AssetTypeFieldOrderByWithRelationInput | Prisma.AssetTypeFieldOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AssetTypeFieldWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssetTypeFields from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssetTypeFields.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AssetTypeFields
  **/
  _count?: true | AssetTypeFieldCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AssetTypeFieldAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AssetTypeFieldSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AssetTypeFieldMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AssetTypeFieldMaxAggregateInputType
}

export type GetAssetTypeFieldAggregateType<T extends AssetTypeFieldAggregateArgs> = {
      [P in keyof T & keyof AggregateAssetTypeField]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAssetTypeField[P]>
    : Prisma.GetScalarType<T[P], AggregateAssetTypeField[P]>
}




export type AssetTypeFieldGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AssetTypeFieldWhereInput
  orderBy?: Prisma.AssetTypeFieldOrderByWithAggregationInput | Prisma.AssetTypeFieldOrderByWithAggregationInput[]
  by: Prisma.AssetTypeFieldScalarFieldEnum[] | Prisma.AssetTypeFieldScalarFieldEnum
  having?: Prisma.AssetTypeFieldScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AssetTypeFieldCountAggregateInputType | true
  _avg?: AssetTypeFieldAvgAggregateInputType
  _sum?: AssetTypeFieldSumAggregateInputType
  _min?: AssetTypeFieldMinAggregateInputType
  _max?: AssetTypeFieldMaxAggregateInputType
}

export type AssetTypeFieldGroupByOutputType = {
  assetTypeId: number
  fieldId: number
  fieldTypeId: number
  required: boolean
  name: string
  items: string[]
  referentialIntegrityStrategy: $Enums.ReferentialIntegrityStrategy | null
  allowMultipleRelations: boolean
  _count: AssetTypeFieldCountAggregateOutputType | null
  _avg: AssetTypeFieldAvgAggregateOutputType | null
  _sum: AssetTypeFieldSumAggregateOutputType | null
  _min: AssetTypeFieldMinAggregateOutputType | null
  _max: AssetTypeFieldMaxAggregateOutputType | null
}

type GetAssetTypeFieldGroupByPayload<T extends AssetTypeFieldGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AssetTypeFieldGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AssetTypeFieldGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AssetTypeFieldGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AssetTypeFieldGroupByOutputType[P]>
      }
    >
  >



export type AssetTypeFieldWhereInput = {
  AND?: Prisma.AssetTypeFieldWhereInput | Prisma.AssetTypeFieldWhereInput[]
  OR?: Prisma.AssetTypeFieldWhereInput[]
  NOT?: Prisma.AssetTypeFieldWhereInput | Prisma.AssetTypeFieldWhereInput[]
  assetTypeId?: Prisma.IntFilter<"AssetTypeField"> | number
  fieldId?: Prisma.IntFilter<"AssetTypeField"> | number
  fieldTypeId?: Prisma.IntFilter<"AssetTypeField"> | number
  required?: Prisma.BoolFilter<"AssetTypeField"> | boolean
  name?: Prisma.StringFilter<"AssetTypeField"> | string
  items?: Prisma.StringNullableListFilter<"AssetTypeField">
  referentialIntegrityStrategy?: Prisma.EnumReferentialIntegrityStrategyNullableFilter<"AssetTypeField"> | $Enums.ReferentialIntegrityStrategy | null
  allowMultipleRelations?: Prisma.BoolFilter<"AssetTypeField"> | boolean
  allowedAssetTypes?: Prisma.ReferencedFieldOnAssetTypeListRelationFilter
  assetType?: Prisma.XOR<Prisma.AssetTypeNullableScalarRelationFilter, Prisma.AssetTypeWhereInput> | null
}

export type AssetTypeFieldOrderByWithRelationInput = {
  assetTypeId?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
  fieldTypeId?: Prisma.SortOrder
  required?: Prisma.SortOrder
  name?: Prisma.SortOrder
  items?: Prisma.SortOrder
  referentialIntegrityStrategy?: Prisma.SortOrderInput | Prisma.SortOrder
  allowMultipleRelations?: Prisma.SortOrder
  allowedAssetTypes?: Prisma.ReferencedFieldOnAssetTypeOrderByRelationAggregateInput
  assetType?: Prisma.AssetTypeOrderByWithRelationInput
}

export type AssetTypeFieldWhereUniqueInput = Prisma.AtLeast<{
  assetTypeId_fieldId?: Prisma.AssetTypeFieldAssetTypeIdFieldIdCompoundUniqueInput
  AND?: Prisma.AssetTypeFieldWhereInput | Prisma.AssetTypeFieldWhereInput[]
  OR?: Prisma.AssetTypeFieldWhereInput[]
  NOT?: Prisma.AssetTypeFieldWhereInput | Prisma.AssetTypeFieldWhereInput[]
  assetTypeId?: Prisma.IntFilter<"AssetTypeField"> | number
  fieldId?: Prisma.IntFilter<"AssetTypeField"> | number
  fieldTypeId?: Prisma.IntFilter<"AssetTypeField"> | number
  required?: Prisma.BoolFilter<"AssetTypeField"> | boolean
  name?: Prisma.StringFilter<"AssetTypeField"> | string
  items?: Prisma.StringNullableListFilter<"AssetTypeField">
  referentialIntegrityStrategy?: Prisma.EnumReferentialIntegrityStrategyNullableFilter<"AssetTypeField"> | $Enums.ReferentialIntegrityStrategy | null
  allowMultipleRelations?: Prisma.BoolFilter<"AssetTypeField"> | boolean
  allowedAssetTypes?: Prisma.ReferencedFieldOnAssetTypeListRelationFilter
  assetType?: Prisma.XOR<Prisma.AssetTypeNullableScalarRelationFilter, Prisma.AssetTypeWhereInput> | null
}, "assetTypeId_fieldId">

export type AssetTypeFieldOrderByWithAggregationInput = {
  assetTypeId?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
  fieldTypeId?: Prisma.SortOrder
  required?: Prisma.SortOrder
  name?: Prisma.SortOrder
  items?: Prisma.SortOrder
  referentialIntegrityStrategy?: Prisma.SortOrderInput | Prisma.SortOrder
  allowMultipleRelations?: Prisma.SortOrder
  _count?: Prisma.AssetTypeFieldCountOrderByAggregateInput
  _avg?: Prisma.AssetTypeFieldAvgOrderByAggregateInput
  _max?: Prisma.AssetTypeFieldMaxOrderByAggregateInput
  _min?: Prisma.AssetTypeFieldMinOrderByAggregateInput
  _sum?: Prisma.AssetTypeFieldSumOrderByAggregateInput
}

export type AssetTypeFieldScalarWhereWithAggregatesInput = {
  AND?: Prisma.AssetTypeFieldScalarWhereWithAggregatesInput | Prisma.AssetTypeFieldScalarWhereWithAggregatesInput[]
  OR?: Prisma.AssetTypeFieldScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AssetTypeFieldScalarWhereWithAggregatesInput | Prisma.AssetTypeFieldScalarWhereWithAggregatesInput[]
  assetTypeId?: Prisma.IntWithAggregatesFilter<"AssetTypeField"> | number
  fieldId?: Prisma.IntWithAggregatesFilter<"AssetTypeField"> | number
  fieldTypeId?: Prisma.IntWithAggregatesFilter<"AssetTypeField"> | number
  required?: Prisma.BoolWithAggregatesFilter<"AssetTypeField"> | boolean
  name?: Prisma.StringWithAggregatesFilter<"AssetTypeField"> | string
  items?: Prisma.StringNullableListFilter<"AssetTypeField">
  referentialIntegrityStrategy?: Prisma.EnumReferentialIntegrityStrategyNullableWithAggregatesFilter<"AssetTypeField"> | $Enums.ReferentialIntegrityStrategy | null
  allowMultipleRelations?: Prisma.BoolWithAggregatesFilter<"AssetTypeField"> | boolean
}

export type AssetTypeFieldCreateInput = {
  fieldId: number
  fieldTypeId: number
  required?: boolean
  name: string
  items?: Prisma.AssetTypeFieldCreateitemsInput | string[]
  referentialIntegrityStrategy?: $Enums.ReferentialIntegrityStrategy | null
  allowMultipleRelations?: boolean
  allowedAssetTypes?: Prisma.ReferencedFieldOnAssetTypeCreateNestedManyWithoutFieldInput
  assetType?: Prisma.AssetTypeCreateNestedOneWithoutAssetTypeFieldInput
}

export type AssetTypeFieldUncheckedCreateInput = {
  assetTypeId: number
  fieldId: number
  fieldTypeId: number
  required?: boolean
  name: string
  items?: Prisma.AssetTypeFieldCreateitemsInput | string[]
  referentialIntegrityStrategy?: $Enums.ReferentialIntegrityStrategy | null
  allowMultipleRelations?: boolean
  allowedAssetTypes?: Prisma.ReferencedFieldOnAssetTypeUncheckedCreateNestedManyWithoutFieldInput
}

export type AssetTypeFieldUpdateInput = {
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
  fieldTypeId?: Prisma.IntFieldUpdateOperationsInput | number
  required?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  items?: Prisma.AssetTypeFieldUpdateitemsInput | string[]
  referentialIntegrityStrategy?: Prisma.NullableEnumReferentialIntegrityStrategyFieldUpdateOperationsInput | $Enums.ReferentialIntegrityStrategy | null
  allowMultipleRelations?: Prisma.BoolFieldUpdateOperationsInput | boolean
  allowedAssetTypes?: Prisma.ReferencedFieldOnAssetTypeUpdateManyWithoutFieldNestedInput
  assetType?: Prisma.AssetTypeUpdateOneWithoutAssetTypeFieldNestedInput
}

export type AssetTypeFieldUncheckedUpdateInput = {
  assetTypeId?: Prisma.IntFieldUpdateOperationsInput | number
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
  fieldTypeId?: Prisma.IntFieldUpdateOperationsInput | number
  required?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  items?: Prisma.AssetTypeFieldUpdateitemsInput | string[]
  referentialIntegrityStrategy?: Prisma.NullableEnumReferentialIntegrityStrategyFieldUpdateOperationsInput | $Enums.ReferentialIntegrityStrategy | null
  allowMultipleRelations?: Prisma.BoolFieldUpdateOperationsInput | boolean
  allowedAssetTypes?: Prisma.ReferencedFieldOnAssetTypeUncheckedUpdateManyWithoutFieldNestedInput
}

export type AssetTypeFieldCreateManyInput = {
  assetTypeId: number
  fieldId: number
  fieldTypeId: number
  required?: boolean
  name: string
  items?: Prisma.AssetTypeFieldCreateitemsInput | string[]
  referentialIntegrityStrategy?: $Enums.ReferentialIntegrityStrategy | null
  allowMultipleRelations?: boolean
}

export type AssetTypeFieldUpdateManyMutationInput = {
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
  fieldTypeId?: Prisma.IntFieldUpdateOperationsInput | number
  required?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  items?: Prisma.AssetTypeFieldUpdateitemsInput | string[]
  referentialIntegrityStrategy?: Prisma.NullableEnumReferentialIntegrityStrategyFieldUpdateOperationsInput | $Enums.ReferentialIntegrityStrategy | null
  allowMultipleRelations?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type AssetTypeFieldUncheckedUpdateManyInput = {
  assetTypeId?: Prisma.IntFieldUpdateOperationsInput | number
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
  fieldTypeId?: Prisma.IntFieldUpdateOperationsInput | number
  required?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  items?: Prisma.AssetTypeFieldUpdateitemsInput | string[]
  referentialIntegrityStrategy?: Prisma.NullableEnumReferentialIntegrityStrategyFieldUpdateOperationsInput | $Enums.ReferentialIntegrityStrategy | null
  allowMultipleRelations?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type AssetTypeFieldListRelationFilter = {
  every?: Prisma.AssetTypeFieldWhereInput
  some?: Prisma.AssetTypeFieldWhereInput
  none?: Prisma.AssetTypeFieldWhereInput
}

export type AssetTypeFieldOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type AssetTypeFieldAssetTypeIdFieldIdCompoundUniqueInput = {
  assetTypeId: number
  fieldId: number
}

export type AssetTypeFieldCountOrderByAggregateInput = {
  assetTypeId?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
  fieldTypeId?: Prisma.SortOrder
  required?: Prisma.SortOrder
  name?: Prisma.SortOrder
  items?: Prisma.SortOrder
  referentialIntegrityStrategy?: Prisma.SortOrder
  allowMultipleRelations?: Prisma.SortOrder
}

export type AssetTypeFieldAvgOrderByAggregateInput = {
  assetTypeId?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
  fieldTypeId?: Prisma.SortOrder
}

export type AssetTypeFieldMaxOrderByAggregateInput = {
  assetTypeId?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
  fieldTypeId?: Prisma.SortOrder
  required?: Prisma.SortOrder
  name?: Prisma.SortOrder
  referentialIntegrityStrategy?: Prisma.SortOrder
  allowMultipleRelations?: Prisma.SortOrder
}

export type AssetTypeFieldMinOrderByAggregateInput = {
  assetTypeId?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
  fieldTypeId?: Prisma.SortOrder
  required?: Prisma.SortOrder
  name?: Prisma.SortOrder
  referentialIntegrityStrategy?: Prisma.SortOrder
  allowMultipleRelations?: Prisma.SortOrder
}

export type AssetTypeFieldSumOrderByAggregateInput = {
  assetTypeId?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
  fieldTypeId?: Prisma.SortOrder
}

export type AssetTypeFieldScalarRelationFilter = {
  is?: Prisma.AssetTypeFieldWhereInput
  isNot?: Prisma.AssetTypeFieldWhereInput
}

export type AssetTypeFieldCreateNestedManyWithoutAssetTypeInput = {
  create?: Prisma.XOR<Prisma.AssetTypeFieldCreateWithoutAssetTypeInput, Prisma.AssetTypeFieldUncheckedCreateWithoutAssetTypeInput> | Prisma.AssetTypeFieldCreateWithoutAssetTypeInput[] | Prisma.AssetTypeFieldUncheckedCreateWithoutAssetTypeInput[]
  connectOrCreate?: Prisma.AssetTypeFieldCreateOrConnectWithoutAssetTypeInput | Prisma.AssetTypeFieldCreateOrConnectWithoutAssetTypeInput[]
  createMany?: Prisma.AssetTypeFieldCreateManyAssetTypeInputEnvelope
  connect?: Prisma.AssetTypeFieldWhereUniqueInput | Prisma.AssetTypeFieldWhereUniqueInput[]
}

export type AssetTypeFieldUncheckedCreateNestedManyWithoutAssetTypeInput = {
  create?: Prisma.XOR<Prisma.AssetTypeFieldCreateWithoutAssetTypeInput, Prisma.AssetTypeFieldUncheckedCreateWithoutAssetTypeInput> | Prisma.AssetTypeFieldCreateWithoutAssetTypeInput[] | Prisma.AssetTypeFieldUncheckedCreateWithoutAssetTypeInput[]
  connectOrCreate?: Prisma.AssetTypeFieldCreateOrConnectWithoutAssetTypeInput | Prisma.AssetTypeFieldCreateOrConnectWithoutAssetTypeInput[]
  createMany?: Prisma.AssetTypeFieldCreateManyAssetTypeInputEnvelope
  connect?: Prisma.AssetTypeFieldWhereUniqueInput | Prisma.AssetTypeFieldWhereUniqueInput[]
}

export type AssetTypeFieldUpdateManyWithoutAssetTypeNestedInput = {
  create?: Prisma.XOR<Prisma.AssetTypeFieldCreateWithoutAssetTypeInput, Prisma.AssetTypeFieldUncheckedCreateWithoutAssetTypeInput> | Prisma.AssetTypeFieldCreateWithoutAssetTypeInput[] | Prisma.AssetTypeFieldUncheckedCreateWithoutAssetTypeInput[]
  connectOrCreate?: Prisma.AssetTypeFieldCreateOrConnectWithoutAssetTypeInput | Prisma.AssetTypeFieldCreateOrConnectWithoutAssetTypeInput[]
  upsert?: Prisma.AssetTypeFieldUpsertWithWhereUniqueWithoutAssetTypeInput | Prisma.AssetTypeFieldUpsertWithWhereUniqueWithoutAssetTypeInput[]
  createMany?: Prisma.AssetTypeFieldCreateManyAssetTypeInputEnvelope
  set?: Prisma.AssetTypeFieldWhereUniqueInput | Prisma.AssetTypeFieldWhereUniqueInput[]
  disconnect?: Prisma.AssetTypeFieldWhereUniqueInput | Prisma.AssetTypeFieldWhereUniqueInput[]
  delete?: Prisma.AssetTypeFieldWhereUniqueInput | Prisma.AssetTypeFieldWhereUniqueInput[]
  connect?: Prisma.AssetTypeFieldWhereUniqueInput | Prisma.AssetTypeFieldWhereUniqueInput[]
  update?: Prisma.AssetTypeFieldUpdateWithWhereUniqueWithoutAssetTypeInput | Prisma.AssetTypeFieldUpdateWithWhereUniqueWithoutAssetTypeInput[]
  updateMany?: Prisma.AssetTypeFieldUpdateManyWithWhereWithoutAssetTypeInput | Prisma.AssetTypeFieldUpdateManyWithWhereWithoutAssetTypeInput[]
  deleteMany?: Prisma.AssetTypeFieldScalarWhereInput | Prisma.AssetTypeFieldScalarWhereInput[]
}

export type AssetTypeFieldUncheckedUpdateManyWithoutAssetTypeNestedInput = {
  create?: Prisma.XOR<Prisma.AssetTypeFieldCreateWithoutAssetTypeInput, Prisma.AssetTypeFieldUncheckedCreateWithoutAssetTypeInput> | Prisma.AssetTypeFieldCreateWithoutAssetTypeInput[] | Prisma.AssetTypeFieldUncheckedCreateWithoutAssetTypeInput[]
  connectOrCreate?: Prisma.AssetTypeFieldCreateOrConnectWithoutAssetTypeInput | Prisma.AssetTypeFieldCreateOrConnectWithoutAssetTypeInput[]
  upsert?: Prisma.AssetTypeFieldUpsertWithWhereUniqueWithoutAssetTypeInput | Prisma.AssetTypeFieldUpsertWithWhereUniqueWithoutAssetTypeInput[]
  createMany?: Prisma.AssetTypeFieldCreateManyAssetTypeInputEnvelope
  set?: Prisma.AssetTypeFieldWhereUniqueInput | Prisma.AssetTypeFieldWhereUniqueInput[]
  disconnect?: Prisma.AssetTypeFieldWhereUniqueInput | Prisma.AssetTypeFieldWhereUniqueInput[]
  delete?: Prisma.AssetTypeFieldWhereUniqueInput | Prisma.AssetTypeFieldWhereUniqueInput[]
  connect?: Prisma.AssetTypeFieldWhereUniqueInput | Prisma.AssetTypeFieldWhereUniqueInput[]
  update?: Prisma.AssetTypeFieldUpdateWithWhereUniqueWithoutAssetTypeInput | Prisma.AssetTypeFieldUpdateWithWhereUniqueWithoutAssetTypeInput[]
  updateMany?: Prisma.AssetTypeFieldUpdateManyWithWhereWithoutAssetTypeInput | Prisma.AssetTypeFieldUpdateManyWithWhereWithoutAssetTypeInput[]
  deleteMany?: Prisma.AssetTypeFieldScalarWhereInput | Prisma.AssetTypeFieldScalarWhereInput[]
}

export type AssetTypeFieldCreateitemsInput = {
  set: string[]
}

export type AssetTypeFieldUpdateitemsInput = {
  set?: string[]
  push?: string | string[]
}

export type NullableEnumReferentialIntegrityStrategyFieldUpdateOperationsInput = {
  set?: $Enums.ReferentialIntegrityStrategy | null
}

export type AssetTypeFieldCreateNestedOneWithoutAllowedAssetTypesInput = {
  create?: Prisma.XOR<Prisma.AssetTypeFieldCreateWithoutAllowedAssetTypesInput, Prisma.AssetTypeFieldUncheckedCreateWithoutAllowedAssetTypesInput>
  connectOrCreate?: Prisma.AssetTypeFieldCreateOrConnectWithoutAllowedAssetTypesInput
  connect?: Prisma.AssetTypeFieldWhereUniqueInput
}

export type AssetTypeFieldUpdateOneRequiredWithoutAllowedAssetTypesNestedInput = {
  create?: Prisma.XOR<Prisma.AssetTypeFieldCreateWithoutAllowedAssetTypesInput, Prisma.AssetTypeFieldUncheckedCreateWithoutAllowedAssetTypesInput>
  connectOrCreate?: Prisma.AssetTypeFieldCreateOrConnectWithoutAllowedAssetTypesInput
  upsert?: Prisma.AssetTypeFieldUpsertWithoutAllowedAssetTypesInput
  connect?: Prisma.AssetTypeFieldWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AssetTypeFieldUpdateToOneWithWhereWithoutAllowedAssetTypesInput, Prisma.AssetTypeFieldUpdateWithoutAllowedAssetTypesInput>, Prisma.AssetTypeFieldUncheckedUpdateWithoutAllowedAssetTypesInput>
}

export type AssetTypeFieldCreateWithoutAssetTypeInput = {
  fieldId: number
  fieldTypeId: number
  required?: boolean
  name: string
  items?: Prisma.AssetTypeFieldCreateitemsInput | string[]
  referentialIntegrityStrategy?: $Enums.ReferentialIntegrityStrategy | null
  allowMultipleRelations?: boolean
  allowedAssetTypes?: Prisma.ReferencedFieldOnAssetTypeCreateNestedManyWithoutFieldInput
}

export type AssetTypeFieldUncheckedCreateWithoutAssetTypeInput = {
  fieldId: number
  fieldTypeId: number
  required?: boolean
  name: string
  items?: Prisma.AssetTypeFieldCreateitemsInput | string[]
  referentialIntegrityStrategy?: $Enums.ReferentialIntegrityStrategy | null
  allowMultipleRelations?: boolean
  allowedAssetTypes?: Prisma.ReferencedFieldOnAssetTypeUncheckedCreateNestedManyWithoutFieldInput
}

export type AssetTypeFieldCreateOrConnectWithoutAssetTypeInput = {
  where: Prisma.AssetTypeFieldWhereUniqueInput
  create: Prisma.XOR<Prisma.AssetTypeFieldCreateWithoutAssetTypeInput, Prisma.AssetTypeFieldUncheckedCreateWithoutAssetTypeInput>
}

export type AssetTypeFieldCreateManyAssetTypeInputEnvelope = {
  data: Prisma.AssetTypeFieldCreateManyAssetTypeInput | Prisma.AssetTypeFieldCreateManyAssetTypeInput[]
  skipDuplicates?: boolean
}

export type AssetTypeFieldUpsertWithWhereUniqueWithoutAssetTypeInput = {
  where: Prisma.AssetTypeFieldWhereUniqueInput
  update: Prisma.XOR<Prisma.AssetTypeFieldUpdateWithoutAssetTypeInput, Prisma.AssetTypeFieldUncheckedUpdateWithoutAssetTypeInput>
  create: Prisma.XOR<Prisma.AssetTypeFieldCreateWithoutAssetTypeInput, Prisma.AssetTypeFieldUncheckedCreateWithoutAssetTypeInput>
}

export type AssetTypeFieldUpdateWithWhereUniqueWithoutAssetTypeInput = {
  where: Prisma.AssetTypeFieldWhereUniqueInput
  data: Prisma.XOR<Prisma.AssetTypeFieldUpdateWithoutAssetTypeInput, Prisma.AssetTypeFieldUncheckedUpdateWithoutAssetTypeInput>
}

export type AssetTypeFieldUpdateManyWithWhereWithoutAssetTypeInput = {
  where: Prisma.AssetTypeFieldScalarWhereInput
  data: Prisma.XOR<Prisma.AssetTypeFieldUpdateManyMutationInput, Prisma.AssetTypeFieldUncheckedUpdateManyWithoutAssetTypeInput>
}

export type AssetTypeFieldScalarWhereInput = {
  AND?: Prisma.AssetTypeFieldScalarWhereInput | Prisma.AssetTypeFieldScalarWhereInput[]
  OR?: Prisma.AssetTypeFieldScalarWhereInput[]
  NOT?: Prisma.AssetTypeFieldScalarWhereInput | Prisma.AssetTypeFieldScalarWhereInput[]
  assetTypeId?: Prisma.IntFilter<"AssetTypeField"> | number
  fieldId?: Prisma.IntFilter<"AssetTypeField"> | number
  fieldTypeId?: Prisma.IntFilter<"AssetTypeField"> | number
  required?: Prisma.BoolFilter<"AssetTypeField"> | boolean
  name?: Prisma.StringFilter<"AssetTypeField"> | string
  items?: Prisma.StringNullableListFilter<"AssetTypeField">
  referentialIntegrityStrategy?: Prisma.EnumReferentialIntegrityStrategyNullableFilter<"AssetTypeField"> | $Enums.ReferentialIntegrityStrategy | null
  allowMultipleRelations?: Prisma.BoolFilter<"AssetTypeField"> | boolean
}

export type AssetTypeFieldCreateWithoutAllowedAssetTypesInput = {
  fieldId: number
  fieldTypeId: number
  required?: boolean
  name: string
  items?: Prisma.AssetTypeFieldCreateitemsInput | string[]
  referentialIntegrityStrategy?: $Enums.ReferentialIntegrityStrategy | null
  allowMultipleRelations?: boolean
  assetType?: Prisma.AssetTypeCreateNestedOneWithoutAssetTypeFieldInput
}

export type AssetTypeFieldUncheckedCreateWithoutAllowedAssetTypesInput = {
  assetTypeId: number
  fieldId: number
  fieldTypeId: number
  required?: boolean
  name: string
  items?: Prisma.AssetTypeFieldCreateitemsInput | string[]
  referentialIntegrityStrategy?: $Enums.ReferentialIntegrityStrategy | null
  allowMultipleRelations?: boolean
}

export type AssetTypeFieldCreateOrConnectWithoutAllowedAssetTypesInput = {
  where: Prisma.AssetTypeFieldWhereUniqueInput
  create: Prisma.XOR<Prisma.AssetTypeFieldCreateWithoutAllowedAssetTypesInput, Prisma.AssetTypeFieldUncheckedCreateWithoutAllowedAssetTypesInput>
}

export type AssetTypeFieldUpsertWithoutAllowedAssetTypesInput = {
  update: Prisma.XOR<Prisma.AssetTypeFieldUpdateWithoutAllowedAssetTypesInput, Prisma.AssetTypeFieldUncheckedUpdateWithoutAllowedAssetTypesInput>
  create: Prisma.XOR<Prisma.AssetTypeFieldCreateWithoutAllowedAssetTypesInput, Prisma.AssetTypeFieldUncheckedCreateWithoutAllowedAssetTypesInput>
  where?: Prisma.AssetTypeFieldWhereInput
}

export type AssetTypeFieldUpdateToOneWithWhereWithoutAllowedAssetTypesInput = {
  where?: Prisma.AssetTypeFieldWhereInput
  data: Prisma.XOR<Prisma.AssetTypeFieldUpdateWithoutAllowedAssetTypesInput, Prisma.AssetTypeFieldUncheckedUpdateWithoutAllowedAssetTypesInput>
}

export type AssetTypeFieldUpdateWithoutAllowedAssetTypesInput = {
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
  fieldTypeId?: Prisma.IntFieldUpdateOperationsInput | number
  required?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  items?: Prisma.AssetTypeFieldUpdateitemsInput | string[]
  referentialIntegrityStrategy?: Prisma.NullableEnumReferentialIntegrityStrategyFieldUpdateOperationsInput | $Enums.ReferentialIntegrityStrategy | null
  allowMultipleRelations?: Prisma.BoolFieldUpdateOperationsInput | boolean
  assetType?: Prisma.AssetTypeUpdateOneWithoutAssetTypeFieldNestedInput
}

export type AssetTypeFieldUncheckedUpdateWithoutAllowedAssetTypesInput = {
  assetTypeId?: Prisma.IntFieldUpdateOperationsInput | number
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
  fieldTypeId?: Prisma.IntFieldUpdateOperationsInput | number
  required?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  items?: Prisma.AssetTypeFieldUpdateitemsInput | string[]
  referentialIntegrityStrategy?: Prisma.NullableEnumReferentialIntegrityStrategyFieldUpdateOperationsInput | $Enums.ReferentialIntegrityStrategy | null
  allowMultipleRelations?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type AssetTypeFieldCreateManyAssetTypeInput = {
  fieldId: number
  fieldTypeId: number
  required?: boolean
  name: string
  items?: Prisma.AssetTypeFieldCreateitemsInput | string[]
  referentialIntegrityStrategy?: $Enums.ReferentialIntegrityStrategy | null
  allowMultipleRelations?: boolean
}

export type AssetTypeFieldUpdateWithoutAssetTypeInput = {
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
  fieldTypeId?: Prisma.IntFieldUpdateOperationsInput | number
  required?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  items?: Prisma.AssetTypeFieldUpdateitemsInput | string[]
  referentialIntegrityStrategy?: Prisma.NullableEnumReferentialIntegrityStrategyFieldUpdateOperationsInput | $Enums.ReferentialIntegrityStrategy | null
  allowMultipleRelations?: Prisma.BoolFieldUpdateOperationsInput | boolean
  allowedAssetTypes?: Prisma.ReferencedFieldOnAssetTypeUpdateManyWithoutFieldNestedInput
}

export type AssetTypeFieldUncheckedUpdateWithoutAssetTypeInput = {
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
  fieldTypeId?: Prisma.IntFieldUpdateOperationsInput | number
  required?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  items?: Prisma.AssetTypeFieldUpdateitemsInput | string[]
  referentialIntegrityStrategy?: Prisma.NullableEnumReferentialIntegrityStrategyFieldUpdateOperationsInput | $Enums.ReferentialIntegrityStrategy | null
  allowMultipleRelations?: Prisma.BoolFieldUpdateOperationsInput | boolean
  allowedAssetTypes?: Prisma.ReferencedFieldOnAssetTypeUncheckedUpdateManyWithoutFieldNestedInput
}

export type AssetTypeFieldUncheckedUpdateManyWithoutAssetTypeInput = {
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
  fieldTypeId?: Prisma.IntFieldUpdateOperationsInput | number
  required?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  items?: Prisma.AssetTypeFieldUpdateitemsInput | string[]
  referentialIntegrityStrategy?: Prisma.NullableEnumReferentialIntegrityStrategyFieldUpdateOperationsInput | $Enums.ReferentialIntegrityStrategy | null
  allowMultipleRelations?: Prisma.BoolFieldUpdateOperationsInput | boolean
}


/**
 * Count Type AssetTypeFieldCountOutputType
 */

export type AssetTypeFieldCountOutputType = {
  allowedAssetTypes: number
}

export type AssetTypeFieldCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  allowedAssetTypes?: boolean | AssetTypeFieldCountOutputTypeCountAllowedAssetTypesArgs
}

/**
 * AssetTypeFieldCountOutputType without action
 */
export type AssetTypeFieldCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetTypeFieldCountOutputType
   */
  select?: Prisma.AssetTypeFieldCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AssetTypeFieldCountOutputType without action
 */
export type AssetTypeFieldCountOutputTypeCountAllowedAssetTypesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReferencedFieldOnAssetTypeWhereInput
}


export type AssetTypeFieldSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  assetTypeId?: boolean
  fieldId?: boolean
  fieldTypeId?: boolean
  required?: boolean
  name?: boolean
  items?: boolean
  referentialIntegrityStrategy?: boolean
  allowMultipleRelations?: boolean
  allowedAssetTypes?: boolean | Prisma.AssetTypeField$allowedAssetTypesArgs<ExtArgs>
  assetType?: boolean | Prisma.AssetTypeField$assetTypeArgs<ExtArgs>
  _count?: boolean | Prisma.AssetTypeFieldCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assetTypeField"]>

export type AssetTypeFieldSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  assetTypeId?: boolean
  fieldId?: boolean
  fieldTypeId?: boolean
  required?: boolean
  name?: boolean
  items?: boolean
  referentialIntegrityStrategy?: boolean
  allowMultipleRelations?: boolean
  assetType?: boolean | Prisma.AssetTypeField$assetTypeArgs<ExtArgs>
}, ExtArgs["result"]["assetTypeField"]>

export type AssetTypeFieldSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  assetTypeId?: boolean
  fieldId?: boolean
  fieldTypeId?: boolean
  required?: boolean
  name?: boolean
  items?: boolean
  referentialIntegrityStrategy?: boolean
  allowMultipleRelations?: boolean
  assetType?: boolean | Prisma.AssetTypeField$assetTypeArgs<ExtArgs>
}, ExtArgs["result"]["assetTypeField"]>

export type AssetTypeFieldSelectScalar = {
  assetTypeId?: boolean
  fieldId?: boolean
  fieldTypeId?: boolean
  required?: boolean
  name?: boolean
  items?: boolean
  referentialIntegrityStrategy?: boolean
  allowMultipleRelations?: boolean
}

export type AssetTypeFieldOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"assetTypeId" | "fieldId" | "fieldTypeId" | "required" | "name" | "items" | "referentialIntegrityStrategy" | "allowMultipleRelations", ExtArgs["result"]["assetTypeField"]>
export type AssetTypeFieldInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  allowedAssetTypes?: boolean | Prisma.AssetTypeField$allowedAssetTypesArgs<ExtArgs>
  assetType?: boolean | Prisma.AssetTypeField$assetTypeArgs<ExtArgs>
  _count?: boolean | Prisma.AssetTypeFieldCountOutputTypeDefaultArgs<ExtArgs>
}
export type AssetTypeFieldIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  assetType?: boolean | Prisma.AssetTypeField$assetTypeArgs<ExtArgs>
}
export type AssetTypeFieldIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  assetType?: boolean | Prisma.AssetTypeField$assetTypeArgs<ExtArgs>
}

export type $AssetTypeFieldPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AssetTypeField"
  objects: {
    allowedAssetTypes: Prisma.$ReferencedFieldOnAssetTypePayload<ExtArgs>[]
    assetType: Prisma.$AssetTypePayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    assetTypeId: number
    fieldId: number
    fieldTypeId: number
    required: boolean
    name: string
    items: string[]
    referentialIntegrityStrategy: $Enums.ReferentialIntegrityStrategy | null
    allowMultipleRelations: boolean
  }, ExtArgs["result"]["assetTypeField"]>
  composites: {}
}

export type AssetTypeFieldGetPayload<S extends boolean | null | undefined | AssetTypeFieldDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AssetTypeFieldPayload, S>

export type AssetTypeFieldCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AssetTypeFieldFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AssetTypeFieldCountAggregateInputType | true
  }

export interface AssetTypeFieldDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AssetTypeField'], meta: { name: 'AssetTypeField' } }
  /**
   * Find zero or one AssetTypeField that matches the filter.
   * @param {AssetTypeFieldFindUniqueArgs} args - Arguments to find a AssetTypeField
   * @example
   * // Get one AssetTypeField
   * const assetTypeField = await prisma.assetTypeField.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AssetTypeFieldFindUniqueArgs>(args: Prisma.SelectSubset<T, AssetTypeFieldFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AssetTypeFieldClient<runtime.Types.Result.GetResult<Prisma.$AssetTypeFieldPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AssetTypeField that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AssetTypeFieldFindUniqueOrThrowArgs} args - Arguments to find a AssetTypeField
   * @example
   * // Get one AssetTypeField
   * const assetTypeField = await prisma.assetTypeField.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AssetTypeFieldFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AssetTypeFieldFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AssetTypeFieldClient<runtime.Types.Result.GetResult<Prisma.$AssetTypeFieldPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AssetTypeField that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetTypeFieldFindFirstArgs} args - Arguments to find a AssetTypeField
   * @example
   * // Get one AssetTypeField
   * const assetTypeField = await prisma.assetTypeField.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AssetTypeFieldFindFirstArgs>(args?: Prisma.SelectSubset<T, AssetTypeFieldFindFirstArgs<ExtArgs>>): Prisma.Prisma__AssetTypeFieldClient<runtime.Types.Result.GetResult<Prisma.$AssetTypeFieldPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AssetTypeField that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetTypeFieldFindFirstOrThrowArgs} args - Arguments to find a AssetTypeField
   * @example
   * // Get one AssetTypeField
   * const assetTypeField = await prisma.assetTypeField.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AssetTypeFieldFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AssetTypeFieldFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AssetTypeFieldClient<runtime.Types.Result.GetResult<Prisma.$AssetTypeFieldPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AssetTypeFields that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetTypeFieldFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AssetTypeFields
   * const assetTypeFields = await prisma.assetTypeField.findMany()
   * 
   * // Get first 10 AssetTypeFields
   * const assetTypeFields = await prisma.assetTypeField.findMany({ take: 10 })
   * 
   * // Only select the `assetTypeId`
   * const assetTypeFieldWithAssetTypeIdOnly = await prisma.assetTypeField.findMany({ select: { assetTypeId: true } })
   * 
   */
  findMany<T extends AssetTypeFieldFindManyArgs>(args?: Prisma.SelectSubset<T, AssetTypeFieldFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssetTypeFieldPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AssetTypeField.
   * @param {AssetTypeFieldCreateArgs} args - Arguments to create a AssetTypeField.
   * @example
   * // Create one AssetTypeField
   * const AssetTypeField = await prisma.assetTypeField.create({
   *   data: {
   *     // ... data to create a AssetTypeField
   *   }
   * })
   * 
   */
  create<T extends AssetTypeFieldCreateArgs>(args: Prisma.SelectSubset<T, AssetTypeFieldCreateArgs<ExtArgs>>): Prisma.Prisma__AssetTypeFieldClient<runtime.Types.Result.GetResult<Prisma.$AssetTypeFieldPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AssetTypeFields.
   * @param {AssetTypeFieldCreateManyArgs} args - Arguments to create many AssetTypeFields.
   * @example
   * // Create many AssetTypeFields
   * const assetTypeField = await prisma.assetTypeField.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AssetTypeFieldCreateManyArgs>(args?: Prisma.SelectSubset<T, AssetTypeFieldCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AssetTypeFields and returns the data saved in the database.
   * @param {AssetTypeFieldCreateManyAndReturnArgs} args - Arguments to create many AssetTypeFields.
   * @example
   * // Create many AssetTypeFields
   * const assetTypeField = await prisma.assetTypeField.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AssetTypeFields and only return the `assetTypeId`
   * const assetTypeFieldWithAssetTypeIdOnly = await prisma.assetTypeField.createManyAndReturn({
   *   select: { assetTypeId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AssetTypeFieldCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AssetTypeFieldCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssetTypeFieldPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AssetTypeField.
   * @param {AssetTypeFieldDeleteArgs} args - Arguments to delete one AssetTypeField.
   * @example
   * // Delete one AssetTypeField
   * const AssetTypeField = await prisma.assetTypeField.delete({
   *   where: {
   *     // ... filter to delete one AssetTypeField
   *   }
   * })
   * 
   */
  delete<T extends AssetTypeFieldDeleteArgs>(args: Prisma.SelectSubset<T, AssetTypeFieldDeleteArgs<ExtArgs>>): Prisma.Prisma__AssetTypeFieldClient<runtime.Types.Result.GetResult<Prisma.$AssetTypeFieldPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AssetTypeField.
   * @param {AssetTypeFieldUpdateArgs} args - Arguments to update one AssetTypeField.
   * @example
   * // Update one AssetTypeField
   * const assetTypeField = await prisma.assetTypeField.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AssetTypeFieldUpdateArgs>(args: Prisma.SelectSubset<T, AssetTypeFieldUpdateArgs<ExtArgs>>): Prisma.Prisma__AssetTypeFieldClient<runtime.Types.Result.GetResult<Prisma.$AssetTypeFieldPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AssetTypeFields.
   * @param {AssetTypeFieldDeleteManyArgs} args - Arguments to filter AssetTypeFields to delete.
   * @example
   * // Delete a few AssetTypeFields
   * const { count } = await prisma.assetTypeField.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AssetTypeFieldDeleteManyArgs>(args?: Prisma.SelectSubset<T, AssetTypeFieldDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AssetTypeFields.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetTypeFieldUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AssetTypeFields
   * const assetTypeField = await prisma.assetTypeField.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AssetTypeFieldUpdateManyArgs>(args: Prisma.SelectSubset<T, AssetTypeFieldUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AssetTypeFields and returns the data updated in the database.
   * @param {AssetTypeFieldUpdateManyAndReturnArgs} args - Arguments to update many AssetTypeFields.
   * @example
   * // Update many AssetTypeFields
   * const assetTypeField = await prisma.assetTypeField.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AssetTypeFields and only return the `assetTypeId`
   * const assetTypeFieldWithAssetTypeIdOnly = await prisma.assetTypeField.updateManyAndReturn({
   *   select: { assetTypeId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AssetTypeFieldUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AssetTypeFieldUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssetTypeFieldPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AssetTypeField.
   * @param {AssetTypeFieldUpsertArgs} args - Arguments to update or create a AssetTypeField.
   * @example
   * // Update or create a AssetTypeField
   * const assetTypeField = await prisma.assetTypeField.upsert({
   *   create: {
   *     // ... data to create a AssetTypeField
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AssetTypeField we want to update
   *   }
   * })
   */
  upsert<T extends AssetTypeFieldUpsertArgs>(args: Prisma.SelectSubset<T, AssetTypeFieldUpsertArgs<ExtArgs>>): Prisma.Prisma__AssetTypeFieldClient<runtime.Types.Result.GetResult<Prisma.$AssetTypeFieldPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AssetTypeFields.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetTypeFieldCountArgs} args - Arguments to filter AssetTypeFields to count.
   * @example
   * // Count the number of AssetTypeFields
   * const count = await prisma.assetTypeField.count({
   *   where: {
   *     // ... the filter for the AssetTypeFields we want to count
   *   }
   * })
  **/
  count<T extends AssetTypeFieldCountArgs>(
    args?: Prisma.Subset<T, AssetTypeFieldCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AssetTypeFieldCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AssetTypeField.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetTypeFieldAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AssetTypeFieldAggregateArgs>(args: Prisma.Subset<T, AssetTypeFieldAggregateArgs>): Prisma.PrismaPromise<GetAssetTypeFieldAggregateType<T>>

  /**
   * Group by AssetTypeField.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetTypeFieldGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AssetTypeFieldGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AssetTypeFieldGroupByArgs['orderBy'] }
      : { orderBy?: AssetTypeFieldGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AssetTypeFieldGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAssetTypeFieldGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AssetTypeField model
 */
readonly fields: AssetTypeFieldFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AssetTypeField.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AssetTypeFieldClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  allowedAssetTypes<T extends Prisma.AssetTypeField$allowedAssetTypesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AssetTypeField$allowedAssetTypesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReferencedFieldOnAssetTypePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  assetType<T extends Prisma.AssetTypeField$assetTypeArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AssetTypeField$assetTypeArgs<ExtArgs>>): Prisma.Prisma__AssetTypeClient<runtime.Types.Result.GetResult<Prisma.$AssetTypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AssetTypeField model
 */
export interface AssetTypeFieldFieldRefs {
  readonly assetTypeId: Prisma.FieldRef<"AssetTypeField", 'Int'>
  readonly fieldId: Prisma.FieldRef<"AssetTypeField", 'Int'>
  readonly fieldTypeId: Prisma.FieldRef<"AssetTypeField", 'Int'>
  readonly required: Prisma.FieldRef<"AssetTypeField", 'Boolean'>
  readonly name: Prisma.FieldRef<"AssetTypeField", 'String'>
  readonly items: Prisma.FieldRef<"AssetTypeField", 'String[]'>
  readonly referentialIntegrityStrategy: Prisma.FieldRef<"AssetTypeField", 'ReferentialIntegrityStrategy'>
  readonly allowMultipleRelations: Prisma.FieldRef<"AssetTypeField", 'Boolean'>
}
    

// Custom InputTypes
/**
 * AssetTypeField findUnique
 */
export type AssetTypeFieldFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetTypeField
   */
  select?: Prisma.AssetTypeFieldSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetTypeField
   */
  omit?: Prisma.AssetTypeFieldOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetTypeFieldInclude<ExtArgs> | null
  /**
   * Filter, which AssetTypeField to fetch.
   */
  where: Prisma.AssetTypeFieldWhereUniqueInput
}

/**
 * AssetTypeField findUniqueOrThrow
 */
export type AssetTypeFieldFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetTypeField
   */
  select?: Prisma.AssetTypeFieldSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetTypeField
   */
  omit?: Prisma.AssetTypeFieldOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetTypeFieldInclude<ExtArgs> | null
  /**
   * Filter, which AssetTypeField to fetch.
   */
  where: Prisma.AssetTypeFieldWhereUniqueInput
}

/**
 * AssetTypeField findFirst
 */
export type AssetTypeFieldFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetTypeField
   */
  select?: Prisma.AssetTypeFieldSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetTypeField
   */
  omit?: Prisma.AssetTypeFieldOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetTypeFieldInclude<ExtArgs> | null
  /**
   * Filter, which AssetTypeField to fetch.
   */
  where?: Prisma.AssetTypeFieldWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssetTypeFields to fetch.
   */
  orderBy?: Prisma.AssetTypeFieldOrderByWithRelationInput | Prisma.AssetTypeFieldOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AssetTypeFields.
   */
  cursor?: Prisma.AssetTypeFieldWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssetTypeFields from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssetTypeFields.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AssetTypeFields.
   */
  distinct?: Prisma.AssetTypeFieldScalarFieldEnum | Prisma.AssetTypeFieldScalarFieldEnum[]
}

/**
 * AssetTypeField findFirstOrThrow
 */
export type AssetTypeFieldFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetTypeField
   */
  select?: Prisma.AssetTypeFieldSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetTypeField
   */
  omit?: Prisma.AssetTypeFieldOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetTypeFieldInclude<ExtArgs> | null
  /**
   * Filter, which AssetTypeField to fetch.
   */
  where?: Prisma.AssetTypeFieldWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssetTypeFields to fetch.
   */
  orderBy?: Prisma.AssetTypeFieldOrderByWithRelationInput | Prisma.AssetTypeFieldOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AssetTypeFields.
   */
  cursor?: Prisma.AssetTypeFieldWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssetTypeFields from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssetTypeFields.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AssetTypeFields.
   */
  distinct?: Prisma.AssetTypeFieldScalarFieldEnum | Prisma.AssetTypeFieldScalarFieldEnum[]
}

/**
 * AssetTypeField findMany
 */
export type AssetTypeFieldFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetTypeField
   */
  select?: Prisma.AssetTypeFieldSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetTypeField
   */
  omit?: Prisma.AssetTypeFieldOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetTypeFieldInclude<ExtArgs> | null
  /**
   * Filter, which AssetTypeFields to fetch.
   */
  where?: Prisma.AssetTypeFieldWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssetTypeFields to fetch.
   */
  orderBy?: Prisma.AssetTypeFieldOrderByWithRelationInput | Prisma.AssetTypeFieldOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AssetTypeFields.
   */
  cursor?: Prisma.AssetTypeFieldWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssetTypeFields from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssetTypeFields.
   */
  skip?: number
  distinct?: Prisma.AssetTypeFieldScalarFieldEnum | Prisma.AssetTypeFieldScalarFieldEnum[]
}

/**
 * AssetTypeField create
 */
export type AssetTypeFieldCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetTypeField
   */
  select?: Prisma.AssetTypeFieldSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetTypeField
   */
  omit?: Prisma.AssetTypeFieldOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetTypeFieldInclude<ExtArgs> | null
  /**
   * The data needed to create a AssetTypeField.
   */
  data: Prisma.XOR<Prisma.AssetTypeFieldCreateInput, Prisma.AssetTypeFieldUncheckedCreateInput>
}

/**
 * AssetTypeField createMany
 */
export type AssetTypeFieldCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AssetTypeFields.
   */
  data: Prisma.AssetTypeFieldCreateManyInput | Prisma.AssetTypeFieldCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AssetTypeField createManyAndReturn
 */
export type AssetTypeFieldCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetTypeField
   */
  select?: Prisma.AssetTypeFieldSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AssetTypeField
   */
  omit?: Prisma.AssetTypeFieldOmit<ExtArgs> | null
  /**
   * The data used to create many AssetTypeFields.
   */
  data: Prisma.AssetTypeFieldCreateManyInput | Prisma.AssetTypeFieldCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetTypeFieldIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AssetTypeField update
 */
export type AssetTypeFieldUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetTypeField
   */
  select?: Prisma.AssetTypeFieldSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetTypeField
   */
  omit?: Prisma.AssetTypeFieldOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetTypeFieldInclude<ExtArgs> | null
  /**
   * The data needed to update a AssetTypeField.
   */
  data: Prisma.XOR<Prisma.AssetTypeFieldUpdateInput, Prisma.AssetTypeFieldUncheckedUpdateInput>
  /**
   * Choose, which AssetTypeField to update.
   */
  where: Prisma.AssetTypeFieldWhereUniqueInput
}

/**
 * AssetTypeField updateMany
 */
export type AssetTypeFieldUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AssetTypeFields.
   */
  data: Prisma.XOR<Prisma.AssetTypeFieldUpdateManyMutationInput, Prisma.AssetTypeFieldUncheckedUpdateManyInput>
  /**
   * Filter which AssetTypeFields to update
   */
  where?: Prisma.AssetTypeFieldWhereInput
  /**
   * Limit how many AssetTypeFields to update.
   */
  limit?: number
}

/**
 * AssetTypeField updateManyAndReturn
 */
export type AssetTypeFieldUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetTypeField
   */
  select?: Prisma.AssetTypeFieldSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AssetTypeField
   */
  omit?: Prisma.AssetTypeFieldOmit<ExtArgs> | null
  /**
   * The data used to update AssetTypeFields.
   */
  data: Prisma.XOR<Prisma.AssetTypeFieldUpdateManyMutationInput, Prisma.AssetTypeFieldUncheckedUpdateManyInput>
  /**
   * Filter which AssetTypeFields to update
   */
  where?: Prisma.AssetTypeFieldWhereInput
  /**
   * Limit how many AssetTypeFields to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetTypeFieldIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AssetTypeField upsert
 */
export type AssetTypeFieldUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetTypeField
   */
  select?: Prisma.AssetTypeFieldSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetTypeField
   */
  omit?: Prisma.AssetTypeFieldOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetTypeFieldInclude<ExtArgs> | null
  /**
   * The filter to search for the AssetTypeField to update in case it exists.
   */
  where: Prisma.AssetTypeFieldWhereUniqueInput
  /**
   * In case the AssetTypeField found by the `where` argument doesn't exist, create a new AssetTypeField with this data.
   */
  create: Prisma.XOR<Prisma.AssetTypeFieldCreateInput, Prisma.AssetTypeFieldUncheckedCreateInput>
  /**
   * In case the AssetTypeField was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AssetTypeFieldUpdateInput, Prisma.AssetTypeFieldUncheckedUpdateInput>
}

/**
 * AssetTypeField delete
 */
export type AssetTypeFieldDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetTypeField
   */
  select?: Prisma.AssetTypeFieldSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetTypeField
   */
  omit?: Prisma.AssetTypeFieldOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetTypeFieldInclude<ExtArgs> | null
  /**
   * Filter which AssetTypeField to delete.
   */
  where: Prisma.AssetTypeFieldWhereUniqueInput
}

/**
 * AssetTypeField deleteMany
 */
export type AssetTypeFieldDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AssetTypeFields to delete
   */
  where?: Prisma.AssetTypeFieldWhereInput
  /**
   * Limit how many AssetTypeFields to delete.
   */
  limit?: number
}

/**
 * AssetTypeField.allowedAssetTypes
 */
export type AssetTypeField$allowedAssetTypesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReferencedFieldOnAssetType
   */
  select?: Prisma.ReferencedFieldOnAssetTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReferencedFieldOnAssetType
   */
  omit?: Prisma.ReferencedFieldOnAssetTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReferencedFieldOnAssetTypeInclude<ExtArgs> | null
  where?: Prisma.ReferencedFieldOnAssetTypeWhereInput
  orderBy?: Prisma.ReferencedFieldOnAssetTypeOrderByWithRelationInput | Prisma.ReferencedFieldOnAssetTypeOrderByWithRelationInput[]
  cursor?: Prisma.ReferencedFieldOnAssetTypeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ReferencedFieldOnAssetTypeScalarFieldEnum | Prisma.ReferencedFieldOnAssetTypeScalarFieldEnum[]
}

/**
 * AssetTypeField.assetType
 */
export type AssetTypeField$assetTypeArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetType
   */
  select?: Prisma.AssetTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetType
   */
  omit?: Prisma.AssetTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetTypeInclude<ExtArgs> | null
  where?: Prisma.AssetTypeWhereInput
}

/**
 * AssetTypeField without action
 */
export type AssetTypeFieldDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetTypeField
   */
  select?: Prisma.AssetTypeFieldSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetTypeField
   */
  omit?: Prisma.AssetTypeFieldOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetTypeFieldInclude<ExtArgs> | null
}
