
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AssetToApp` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model AssetToApp
 * 
 */
export type AssetToAppModel = runtime.Types.Result.DefaultSelection<Prisma.$AssetToAppPayload>

export type AggregateAssetToApp = {
  _count: AssetToAppCountAggregateOutputType | null
  _avg: AssetToAppAvgAggregateOutputType | null
  _sum: AssetToAppSumAggregateOutputType | null
  _min: AssetToAppMinAggregateOutputType | null
  _max: AssetToAppMaxAggregateOutputType | null
}

export type AssetToAppAvgAggregateOutputType = {
  assetId: number | null
  appId: number | null
  fieldId: number | null
}

export type AssetToAppSumAggregateOutputType = {
  assetId: number | null
  appId: number | null
  fieldId: number | null
}

export type AssetToAppMinAggregateOutputType = {
  assetId: number | null
  appId: number | null
  fieldId: number | null
}

export type AssetToAppMaxAggregateOutputType = {
  assetId: number | null
  appId: number | null
  fieldId: number | null
}

export type AssetToAppCountAggregateOutputType = {
  assetId: number
  appId: number
  fieldId: number
  _all: number
}


export type AssetToAppAvgAggregateInputType = {
  assetId?: true
  appId?: true
  fieldId?: true
}

export type AssetToAppSumAggregateInputType = {
  assetId?: true
  appId?: true
  fieldId?: true
}

export type AssetToAppMinAggregateInputType = {
  assetId?: true
  appId?: true
  fieldId?: true
}

export type AssetToAppMaxAggregateInputType = {
  assetId?: true
  appId?: true
  fieldId?: true
}

export type AssetToAppCountAggregateInputType = {
  assetId?: true
  appId?: true
  fieldId?: true
  _all?: true
}

export type AssetToAppAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AssetToApp to aggregate.
   */
  where?: Prisma.AssetToAppWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssetToApps to fetch.
   */
  orderBy?: Prisma.AssetToAppOrderByWithRelationInput | Prisma.AssetToAppOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AssetToAppWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssetToApps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssetToApps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AssetToApps
  **/
  _count?: true | AssetToAppCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AssetToAppAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AssetToAppSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AssetToAppMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AssetToAppMaxAggregateInputType
}

export type GetAssetToAppAggregateType<T extends AssetToAppAggregateArgs> = {
      [P in keyof T & keyof AggregateAssetToApp]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAssetToApp[P]>
    : Prisma.GetScalarType<T[P], AggregateAssetToApp[P]>
}




export type AssetToAppGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AssetToAppWhereInput
  orderBy?: Prisma.AssetToAppOrderByWithAggregationInput | Prisma.AssetToAppOrderByWithAggregationInput[]
  by: Prisma.AssetToAppScalarFieldEnum[] | Prisma.AssetToAppScalarFieldEnum
  having?: Prisma.AssetToAppScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AssetToAppCountAggregateInputType | true
  _avg?: AssetToAppAvgAggregateInputType
  _sum?: AssetToAppSumAggregateInputType
  _min?: AssetToAppMinAggregateInputType
  _max?: AssetToAppMaxAggregateInputType
}

export type AssetToAppGroupByOutputType = {
  assetId: number
  appId: number
  fieldId: number
  _count: AssetToAppCountAggregateOutputType | null
  _avg: AssetToAppAvgAggregateOutputType | null
  _sum: AssetToAppSumAggregateOutputType | null
  _min: AssetToAppMinAggregateOutputType | null
  _max: AssetToAppMaxAggregateOutputType | null
}

type GetAssetToAppGroupByPayload<T extends AssetToAppGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AssetToAppGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AssetToAppGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AssetToAppGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AssetToAppGroupByOutputType[P]>
      }
    >
  >



export type AssetToAppWhereInput = {
  AND?: Prisma.AssetToAppWhereInput | Prisma.AssetToAppWhereInput[]
  OR?: Prisma.AssetToAppWhereInput[]
  NOT?: Prisma.AssetToAppWhereInput | Prisma.AssetToAppWhereInput[]
  assetId?: Prisma.IntFilter<"AssetToApp"> | number
  appId?: Prisma.IntFilter<"AssetToApp"> | number
  fieldId?: Prisma.IntFilter<"AssetToApp"> | number
  asset?: Prisma.XOR<Prisma.AssetScalarRelationFilter, Prisma.AssetWhereInput>
  app?: Prisma.XOR<Prisma.AppScalarRelationFilter, Prisma.AppWhereInput>
}

export type AssetToAppOrderByWithRelationInput = {
  assetId?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
  asset?: Prisma.AssetOrderByWithRelationInput
  app?: Prisma.AppOrderByWithRelationInput
}

export type AssetToAppWhereUniqueInput = Prisma.AtLeast<{
  assetId_appId_fieldId?: Prisma.AssetToAppAssetIdAppIdFieldIdCompoundUniqueInput
  AND?: Prisma.AssetToAppWhereInput | Prisma.AssetToAppWhereInput[]
  OR?: Prisma.AssetToAppWhereInput[]
  NOT?: Prisma.AssetToAppWhereInput | Prisma.AssetToAppWhereInput[]
  assetId?: Prisma.IntFilter<"AssetToApp"> | number
  appId?: Prisma.IntFilter<"AssetToApp"> | number
  fieldId?: Prisma.IntFilter<"AssetToApp"> | number
  asset?: Prisma.XOR<Prisma.AssetScalarRelationFilter, Prisma.AssetWhereInput>
  app?: Prisma.XOR<Prisma.AppScalarRelationFilter, Prisma.AppWhereInput>
}, "assetId_appId_fieldId">

export type AssetToAppOrderByWithAggregationInput = {
  assetId?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
  _count?: Prisma.AssetToAppCountOrderByAggregateInput
  _avg?: Prisma.AssetToAppAvgOrderByAggregateInput
  _max?: Prisma.AssetToAppMaxOrderByAggregateInput
  _min?: Prisma.AssetToAppMinOrderByAggregateInput
  _sum?: Prisma.AssetToAppSumOrderByAggregateInput
}

export type AssetToAppScalarWhereWithAggregatesInput = {
  AND?: Prisma.AssetToAppScalarWhereWithAggregatesInput | Prisma.AssetToAppScalarWhereWithAggregatesInput[]
  OR?: Prisma.AssetToAppScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AssetToAppScalarWhereWithAggregatesInput | Prisma.AssetToAppScalarWhereWithAggregatesInput[]
  assetId?: Prisma.IntWithAggregatesFilter<"AssetToApp"> | number
  appId?: Prisma.IntWithAggregatesFilter<"AssetToApp"> | number
  fieldId?: Prisma.IntWithAggregatesFilter<"AssetToApp"> | number
}

export type AssetToAppCreateInput = {
  fieldId: number
  asset: Prisma.AssetCreateNestedOneWithoutAssetToAppsInput
  app: Prisma.AppCreateNestedOneWithoutAssetToAppsInput
}

export type AssetToAppUncheckedCreateInput = {
  assetId: number
  appId: number
  fieldId: number
}

export type AssetToAppUpdateInput = {
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
  asset?: Prisma.AssetUpdateOneRequiredWithoutAssetToAppsNestedInput
  app?: Prisma.AppUpdateOneRequiredWithoutAssetToAppsNestedInput
}

export type AssetToAppUncheckedUpdateInput = {
  assetId?: Prisma.IntFieldUpdateOperationsInput | number
  appId?: Prisma.IntFieldUpdateOperationsInput | number
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AssetToAppCreateManyInput = {
  assetId: number
  appId: number
  fieldId: number
}

export type AssetToAppUpdateManyMutationInput = {
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AssetToAppUncheckedUpdateManyInput = {
  assetId?: Prisma.IntFieldUpdateOperationsInput | number
  appId?: Prisma.IntFieldUpdateOperationsInput | number
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AssetToAppListRelationFilter = {
  every?: Prisma.AssetToAppWhereInput
  some?: Prisma.AssetToAppWhereInput
  none?: Prisma.AssetToAppWhereInput
}

export type AssetToAppOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AssetToAppAssetIdAppIdFieldIdCompoundUniqueInput = {
  assetId: number
  appId: number
  fieldId: number
}

export type AssetToAppCountOrderByAggregateInput = {
  assetId?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
}

export type AssetToAppAvgOrderByAggregateInput = {
  assetId?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
}

export type AssetToAppMaxOrderByAggregateInput = {
  assetId?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
}

export type AssetToAppMinOrderByAggregateInput = {
  assetId?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
}

export type AssetToAppSumOrderByAggregateInput = {
  assetId?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
}

export type AssetToAppCreateNestedManyWithoutAssetInput = {
  create?: Prisma.XOR<Prisma.AssetToAppCreateWithoutAssetInput, Prisma.AssetToAppUncheckedCreateWithoutAssetInput> | Prisma.AssetToAppCreateWithoutAssetInput[] | Prisma.AssetToAppUncheckedCreateWithoutAssetInput[]
  connectOrCreate?: Prisma.AssetToAppCreateOrConnectWithoutAssetInput | Prisma.AssetToAppCreateOrConnectWithoutAssetInput[]
  createMany?: Prisma.AssetToAppCreateManyAssetInputEnvelope
  connect?: Prisma.AssetToAppWhereUniqueInput | Prisma.AssetToAppWhereUniqueInput[]
}

export type AssetToAppUncheckedCreateNestedManyWithoutAssetInput = {
  create?: Prisma.XOR<Prisma.AssetToAppCreateWithoutAssetInput, Prisma.AssetToAppUncheckedCreateWithoutAssetInput> | Prisma.AssetToAppCreateWithoutAssetInput[] | Prisma.AssetToAppUncheckedCreateWithoutAssetInput[]
  connectOrCreate?: Prisma.AssetToAppCreateOrConnectWithoutAssetInput | Prisma.AssetToAppCreateOrConnectWithoutAssetInput[]
  createMany?: Prisma.AssetToAppCreateManyAssetInputEnvelope
  connect?: Prisma.AssetToAppWhereUniqueInput | Prisma.AssetToAppWhereUniqueInput[]
}

export type AssetToAppUpdateManyWithoutAssetNestedInput = {
  create?: Prisma.XOR<Prisma.AssetToAppCreateWithoutAssetInput, Prisma.AssetToAppUncheckedCreateWithoutAssetInput> | Prisma.AssetToAppCreateWithoutAssetInput[] | Prisma.AssetToAppUncheckedCreateWithoutAssetInput[]
  connectOrCreate?: Prisma.AssetToAppCreateOrConnectWithoutAssetInput | Prisma.AssetToAppCreateOrConnectWithoutAssetInput[]
  upsert?: Prisma.AssetToAppUpsertWithWhereUniqueWithoutAssetInput | Prisma.AssetToAppUpsertWithWhereUniqueWithoutAssetInput[]
  createMany?: Prisma.AssetToAppCreateManyAssetInputEnvelope
  set?: Prisma.AssetToAppWhereUniqueInput | Prisma.AssetToAppWhereUniqueInput[]
  disconnect?: Prisma.AssetToAppWhereUniqueInput | Prisma.AssetToAppWhereUniqueInput[]
  delete?: Prisma.AssetToAppWhereUniqueInput | Prisma.AssetToAppWhereUniqueInput[]
  connect?: Prisma.AssetToAppWhereUniqueInput | Prisma.AssetToAppWhereUniqueInput[]
  update?: Prisma.AssetToAppUpdateWithWhereUniqueWithoutAssetInput | Prisma.AssetToAppUpdateWithWhereUniqueWithoutAssetInput[]
  updateMany?: Prisma.AssetToAppUpdateManyWithWhereWithoutAssetInput | Prisma.AssetToAppUpdateManyWithWhereWithoutAssetInput[]
  deleteMany?: Prisma.AssetToAppScalarWhereInput | Prisma.AssetToAppScalarWhereInput[]
}

export type AssetToAppUncheckedUpdateManyWithoutAssetNestedInput = {
  create?: Prisma.XOR<Prisma.AssetToAppCreateWithoutAssetInput, Prisma.AssetToAppUncheckedCreateWithoutAssetInput> | Prisma.AssetToAppCreateWithoutAssetInput[] | Prisma.AssetToAppUncheckedCreateWithoutAssetInput[]
  connectOrCreate?: Prisma.AssetToAppCreateOrConnectWithoutAssetInput | Prisma.AssetToAppCreateOrConnectWithoutAssetInput[]
  upsert?: Prisma.AssetToAppUpsertWithWhereUniqueWithoutAssetInput | Prisma.AssetToAppUpsertWithWhereUniqueWithoutAssetInput[]
  createMany?: Prisma.AssetToAppCreateManyAssetInputEnvelope
  set?: Prisma.AssetToAppWhereUniqueInput | Prisma.AssetToAppWhereUniqueInput[]
  disconnect?: Prisma.AssetToAppWhereUniqueInput | Prisma.AssetToAppWhereUniqueInput[]
  delete?: Prisma.AssetToAppWhereUniqueInput | Prisma.AssetToAppWhereUniqueInput[]
  connect?: Prisma.AssetToAppWhereUniqueInput | Prisma.AssetToAppWhereUniqueInput[]
  update?: Prisma.AssetToAppUpdateWithWhereUniqueWithoutAssetInput | Prisma.AssetToAppUpdateWithWhereUniqueWithoutAssetInput[]
  updateMany?: Prisma.AssetToAppUpdateManyWithWhereWithoutAssetInput | Prisma.AssetToAppUpdateManyWithWhereWithoutAssetInput[]
  deleteMany?: Prisma.AssetToAppScalarWhereInput | Prisma.AssetToAppScalarWhereInput[]
}

export type AssetToAppCreateNestedManyWithoutAppInput = {
  create?: Prisma.XOR<Prisma.AssetToAppCreateWithoutAppInput, Prisma.AssetToAppUncheckedCreateWithoutAppInput> | Prisma.AssetToAppCreateWithoutAppInput[] | Prisma.AssetToAppUncheckedCreateWithoutAppInput[]
  connectOrCreate?: Prisma.AssetToAppCreateOrConnectWithoutAppInput | Prisma.AssetToAppCreateOrConnectWithoutAppInput[]
  createMany?: Prisma.AssetToAppCreateManyAppInputEnvelope
  connect?: Prisma.AssetToAppWhereUniqueInput | Prisma.AssetToAppWhereUniqueInput[]
}

export type AssetToAppUncheckedCreateNestedManyWithoutAppInput = {
  create?: Prisma.XOR<Prisma.AssetToAppCreateWithoutAppInput, Prisma.AssetToAppUncheckedCreateWithoutAppInput> | Prisma.AssetToAppCreateWithoutAppInput[] | Prisma.AssetToAppUncheckedCreateWithoutAppInput[]
  connectOrCreate?: Prisma.AssetToAppCreateOrConnectWithoutAppInput | Prisma.AssetToAppCreateOrConnectWithoutAppInput[]
  createMany?: Prisma.AssetToAppCreateManyAppInputEnvelope
  connect?: Prisma.AssetToAppWhereUniqueInput | Prisma.AssetToAppWhereUniqueInput[]
}

export type AssetToAppUpdateManyWithoutAppNestedInput = {
  create?: Prisma.XOR<Prisma.AssetToAppCreateWithoutAppInput, Prisma.AssetToAppUncheckedCreateWithoutAppInput> | Prisma.AssetToAppCreateWithoutAppInput[] | Prisma.AssetToAppUncheckedCreateWithoutAppInput[]
  connectOrCreate?: Prisma.AssetToAppCreateOrConnectWithoutAppInput | Prisma.AssetToAppCreateOrConnectWithoutAppInput[]
  upsert?: Prisma.AssetToAppUpsertWithWhereUniqueWithoutAppInput | Prisma.AssetToAppUpsertWithWhereUniqueWithoutAppInput[]
  createMany?: Prisma.AssetToAppCreateManyAppInputEnvelope
  set?: Prisma.AssetToAppWhereUniqueInput | Prisma.AssetToAppWhereUniqueInput[]
  disconnect?: Prisma.AssetToAppWhereUniqueInput | Prisma.AssetToAppWhereUniqueInput[]
  delete?: Prisma.AssetToAppWhereUniqueInput | Prisma.AssetToAppWhereUniqueInput[]
  connect?: Prisma.AssetToAppWhereUniqueInput | Prisma.AssetToAppWhereUniqueInput[]
  update?: Prisma.AssetToAppUpdateWithWhereUniqueWithoutAppInput | Prisma.AssetToAppUpdateWithWhereUniqueWithoutAppInput[]
  updateMany?: Prisma.AssetToAppUpdateManyWithWhereWithoutAppInput | Prisma.AssetToAppUpdateManyWithWhereWithoutAppInput[]
  deleteMany?: Prisma.AssetToAppScalarWhereInput | Prisma.AssetToAppScalarWhereInput[]
}

export type AssetToAppUncheckedUpdateManyWithoutAppNestedInput = {
  create?: Prisma.XOR<Prisma.AssetToAppCreateWithoutAppInput, Prisma.AssetToAppUncheckedCreateWithoutAppInput> | Prisma.AssetToAppCreateWithoutAppInput[] | Prisma.AssetToAppUncheckedCreateWithoutAppInput[]
  connectOrCreate?: Prisma.AssetToAppCreateOrConnectWithoutAppInput | Prisma.AssetToAppCreateOrConnectWithoutAppInput[]
  upsert?: Prisma.AssetToAppUpsertWithWhereUniqueWithoutAppInput | Prisma.AssetToAppUpsertWithWhereUniqueWithoutAppInput[]
  createMany?: Prisma.AssetToAppCreateManyAppInputEnvelope
  set?: Prisma.AssetToAppWhereUniqueInput | Prisma.AssetToAppWhereUniqueInput[]
  disconnect?: Prisma.AssetToAppWhereUniqueInput | Prisma.AssetToAppWhereUniqueInput[]
  delete?: Prisma.AssetToAppWhereUniqueInput | Prisma.AssetToAppWhereUniqueInput[]
  connect?: Prisma.AssetToAppWhereUniqueInput | Prisma.AssetToAppWhereUniqueInput[]
  update?: Prisma.AssetToAppUpdateWithWhereUniqueWithoutAppInput | Prisma.AssetToAppUpdateWithWhereUniqueWithoutAppInput[]
  updateMany?: Prisma.AssetToAppUpdateManyWithWhereWithoutAppInput | Prisma.AssetToAppUpdateManyWithWhereWithoutAppInput[]
  deleteMany?: Prisma.AssetToAppScalarWhereInput | Prisma.AssetToAppScalarWhereInput[]
}

export type AssetToAppCreateWithoutAssetInput = {
  fieldId: number
  app: Prisma.AppCreateNestedOneWithoutAssetToAppsInput
}

export type AssetToAppUncheckedCreateWithoutAssetInput = {
  appId: number
  fieldId: number
}

export type AssetToAppCreateOrConnectWithoutAssetInput = {
  where: Prisma.AssetToAppWhereUniqueInput
  create: Prisma.XOR<Prisma.AssetToAppCreateWithoutAssetInput, Prisma.AssetToAppUncheckedCreateWithoutAssetInput>
}

export type AssetToAppCreateManyAssetInputEnvelope = {
  data: Prisma.AssetToAppCreateManyAssetInput | Prisma.AssetToAppCreateManyAssetInput[]
  skipDuplicates?: boolean
}

export type AssetToAppUpsertWithWhereUniqueWithoutAssetInput = {
  where: Prisma.AssetToAppWhereUniqueInput
  update: Prisma.XOR<Prisma.AssetToAppUpdateWithoutAssetInput, Prisma.AssetToAppUncheckedUpdateWithoutAssetInput>
  create: Prisma.XOR<Prisma.AssetToAppCreateWithoutAssetInput, Prisma.AssetToAppUncheckedCreateWithoutAssetInput>
}

export type AssetToAppUpdateWithWhereUniqueWithoutAssetInput = {
  where: Prisma.AssetToAppWhereUniqueInput
  data: Prisma.XOR<Prisma.AssetToAppUpdateWithoutAssetInput, Prisma.AssetToAppUncheckedUpdateWithoutAssetInput>
}

export type AssetToAppUpdateManyWithWhereWithoutAssetInput = {
  where: Prisma.AssetToAppScalarWhereInput
  data: Prisma.XOR<Prisma.AssetToAppUpdateManyMutationInput, Prisma.AssetToAppUncheckedUpdateManyWithoutAssetInput>
}

export type AssetToAppScalarWhereInput = {
  AND?: Prisma.AssetToAppScalarWhereInput | Prisma.AssetToAppScalarWhereInput[]
  OR?: Prisma.AssetToAppScalarWhereInput[]
  NOT?: Prisma.AssetToAppScalarWhereInput | Prisma.AssetToAppScalarWhereInput[]
  assetId?: Prisma.IntFilter<"AssetToApp"> | number
  appId?: Prisma.IntFilter<"AssetToApp"> | number
  fieldId?: Prisma.IntFilter<"AssetToApp"> | number
}

export type AssetToAppCreateWithoutAppInput = {
  fieldId: number
  asset: Prisma.AssetCreateNestedOneWithoutAssetToAppsInput
}

export type AssetToAppUncheckedCreateWithoutAppInput = {
  assetId: number
  fieldId: number
}

export type AssetToAppCreateOrConnectWithoutAppInput = {
  where: Prisma.AssetToAppWhereUniqueInput
  create: Prisma.XOR<Prisma.AssetToAppCreateWithoutAppInput, Prisma.AssetToAppUncheckedCreateWithoutAppInput>
}

export type AssetToAppCreateManyAppInputEnvelope = {
  data: Prisma.AssetToAppCreateManyAppInput | Prisma.AssetToAppCreateManyAppInput[]
  skipDuplicates?: boolean
}

export type AssetToAppUpsertWithWhereUniqueWithoutAppInput = {
  where: Prisma.AssetToAppWhereUniqueInput
  update: Prisma.XOR<Prisma.AssetToAppUpdateWithoutAppInput, Prisma.AssetToAppUncheckedUpdateWithoutAppInput>
  create: Prisma.XOR<Prisma.AssetToAppCreateWithoutAppInput, Prisma.AssetToAppUncheckedCreateWithoutAppInput>
}

export type AssetToAppUpdateWithWhereUniqueWithoutAppInput = {
  where: Prisma.AssetToAppWhereUniqueInput
  data: Prisma.XOR<Prisma.AssetToAppUpdateWithoutAppInput, Prisma.AssetToAppUncheckedUpdateWithoutAppInput>
}

export type AssetToAppUpdateManyWithWhereWithoutAppInput = {
  where: Prisma.AssetToAppScalarWhereInput
  data: Prisma.XOR<Prisma.AssetToAppUpdateManyMutationInput, Prisma.AssetToAppUncheckedUpdateManyWithoutAppInput>
}

export type AssetToAppCreateManyAssetInput = {
  appId: number
  fieldId: number
}

export type AssetToAppUpdateWithoutAssetInput = {
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
  app?: Prisma.AppUpdateOneRequiredWithoutAssetToAppsNestedInput
}

export type AssetToAppUncheckedUpdateWithoutAssetInput = {
  appId?: Prisma.IntFieldUpdateOperationsInput | number
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AssetToAppUncheckedUpdateManyWithoutAssetInput = {
  appId?: Prisma.IntFieldUpdateOperationsInput | number
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AssetToAppCreateManyAppInput = {
  assetId: number
  fieldId: number
}

export type AssetToAppUpdateWithoutAppInput = {
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
  asset?: Prisma.AssetUpdateOneRequiredWithoutAssetToAppsNestedInput
}

export type AssetToAppUncheckedUpdateWithoutAppInput = {
  assetId?: Prisma.IntFieldUpdateOperationsInput | number
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AssetToAppUncheckedUpdateManyWithoutAppInput = {
  assetId?: Prisma.IntFieldUpdateOperationsInput | number
  fieldId?: Prisma.IntFieldUpdateOperationsInput | number
}



export type AssetToAppSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  assetId?: boolean
  appId?: boolean
  fieldId?: boolean
  asset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assetToApp"]>

export type AssetToAppSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  assetId?: boolean
  appId?: boolean
  fieldId?: boolean
  asset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assetToApp"]>

export type AssetToAppSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  assetId?: boolean
  appId?: boolean
  fieldId?: boolean
  asset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assetToApp"]>

export type AssetToAppSelectScalar = {
  assetId?: boolean
  appId?: boolean
  fieldId?: boolean
}

export type AssetToAppOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"assetId" | "appId" | "fieldId", ExtArgs["result"]["assetToApp"]>
export type AssetToAppInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  asset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
}
export type AssetToAppIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  asset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
}
export type AssetToAppIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  asset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
}

export type $AssetToAppPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AssetToApp"
  objects: {
    asset: Prisma.$AssetPayload<ExtArgs>
    app: Prisma.$AppPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    assetId: number
    appId: number
    fieldId: number
  }, ExtArgs["result"]["assetToApp"]>
  composites: {}
}

export type AssetToAppGetPayload<S extends boolean | null | undefined | AssetToAppDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AssetToAppPayload, S>

export type AssetToAppCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AssetToAppFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AssetToAppCountAggregateInputType | true
  }

export interface AssetToAppDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AssetToApp'], meta: { name: 'AssetToApp' } }
  /**
   * Find zero or one AssetToApp that matches the filter.
   * @param {AssetToAppFindUniqueArgs} args - Arguments to find a AssetToApp
   * @example
   * // Get one AssetToApp
   * const assetToApp = await prisma.assetToApp.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AssetToAppFindUniqueArgs>(args: Prisma.SelectSubset<T, AssetToAppFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AssetToAppClient<runtime.Types.Result.GetResult<Prisma.$AssetToAppPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AssetToApp that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AssetToAppFindUniqueOrThrowArgs} args - Arguments to find a AssetToApp
   * @example
   * // Get one AssetToApp
   * const assetToApp = await prisma.assetToApp.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AssetToAppFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AssetToAppFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AssetToAppClient<runtime.Types.Result.GetResult<Prisma.$AssetToAppPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AssetToApp that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetToAppFindFirstArgs} args - Arguments to find a AssetToApp
   * @example
   * // Get one AssetToApp
   * const assetToApp = await prisma.assetToApp.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AssetToAppFindFirstArgs>(args?: Prisma.SelectSubset<T, AssetToAppFindFirstArgs<ExtArgs>>): Prisma.Prisma__AssetToAppClient<runtime.Types.Result.GetResult<Prisma.$AssetToAppPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AssetToApp that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetToAppFindFirstOrThrowArgs} args - Arguments to find a AssetToApp
   * @example
   * // Get one AssetToApp
   * const assetToApp = await prisma.assetToApp.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AssetToAppFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AssetToAppFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AssetToAppClient<runtime.Types.Result.GetResult<Prisma.$AssetToAppPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AssetToApps that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetToAppFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AssetToApps
   * const assetToApps = await prisma.assetToApp.findMany()
   * 
   * // Get first 10 AssetToApps
   * const assetToApps = await prisma.assetToApp.findMany({ take: 10 })
   * 
   * // Only select the `assetId`
   * const assetToAppWithAssetIdOnly = await prisma.assetToApp.findMany({ select: { assetId: true } })
   * 
   */
  findMany<T extends AssetToAppFindManyArgs>(args?: Prisma.SelectSubset<T, AssetToAppFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssetToAppPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AssetToApp.
   * @param {AssetToAppCreateArgs} args - Arguments to create a AssetToApp.
   * @example
   * // Create one AssetToApp
   * const AssetToApp = await prisma.assetToApp.create({
   *   data: {
   *     // ... data to create a AssetToApp
   *   }
   * })
   * 
   */
  create<T extends AssetToAppCreateArgs>(args: Prisma.SelectSubset<T, AssetToAppCreateArgs<ExtArgs>>): Prisma.Prisma__AssetToAppClient<runtime.Types.Result.GetResult<Prisma.$AssetToAppPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AssetToApps.
   * @param {AssetToAppCreateManyArgs} args - Arguments to create many AssetToApps.
   * @example
   * // Create many AssetToApps
   * const assetToApp = await prisma.assetToApp.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AssetToAppCreateManyArgs>(args?: Prisma.SelectSubset<T, AssetToAppCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AssetToApps and returns the data saved in the database.
   * @param {AssetToAppCreateManyAndReturnArgs} args - Arguments to create many AssetToApps.
   * @example
   * // Create many AssetToApps
   * const assetToApp = await prisma.assetToApp.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AssetToApps and only return the `assetId`
   * const assetToAppWithAssetIdOnly = await prisma.assetToApp.createManyAndReturn({
   *   select: { assetId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AssetToAppCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AssetToAppCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssetToAppPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AssetToApp.
   * @param {AssetToAppDeleteArgs} args - Arguments to delete one AssetToApp.
   * @example
   * // Delete one AssetToApp
   * const AssetToApp = await prisma.assetToApp.delete({
   *   where: {
   *     // ... filter to delete one AssetToApp
   *   }
   * })
   * 
   */
  delete<T extends AssetToAppDeleteArgs>(args: Prisma.SelectSubset<T, AssetToAppDeleteArgs<ExtArgs>>): Prisma.Prisma__AssetToAppClient<runtime.Types.Result.GetResult<Prisma.$AssetToAppPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AssetToApp.
   * @param {AssetToAppUpdateArgs} args - Arguments to update one AssetToApp.
   * @example
   * // Update one AssetToApp
   * const assetToApp = await prisma.assetToApp.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AssetToAppUpdateArgs>(args: Prisma.SelectSubset<T, AssetToAppUpdateArgs<ExtArgs>>): Prisma.Prisma__AssetToAppClient<runtime.Types.Result.GetResult<Prisma.$AssetToAppPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AssetToApps.
   * @param {AssetToAppDeleteManyArgs} args - Arguments to filter AssetToApps to delete.
   * @example
   * // Delete a few AssetToApps
   * const { count } = await prisma.assetToApp.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AssetToAppDeleteManyArgs>(args?: Prisma.SelectSubset<T, AssetToAppDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AssetToApps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetToAppUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AssetToApps
   * const assetToApp = await prisma.assetToApp.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AssetToAppUpdateManyArgs>(args: Prisma.SelectSubset<T, AssetToAppUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AssetToApps and returns the data updated in the database.
   * @param {AssetToAppUpdateManyAndReturnArgs} args - Arguments to update many AssetToApps.
   * @example
   * // Update many AssetToApps
   * const assetToApp = await prisma.assetToApp.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AssetToApps and only return the `assetId`
   * const assetToAppWithAssetIdOnly = await prisma.assetToApp.updateManyAndReturn({
   *   select: { assetId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AssetToAppUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AssetToAppUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssetToAppPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AssetToApp.
   * @param {AssetToAppUpsertArgs} args - Arguments to update or create a AssetToApp.
   * @example
   * // Update or create a AssetToApp
   * const assetToApp = await prisma.assetToApp.upsert({
   *   create: {
   *     // ... data to create a AssetToApp
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AssetToApp we want to update
   *   }
   * })
   */
  upsert<T extends AssetToAppUpsertArgs>(args: Prisma.SelectSubset<T, AssetToAppUpsertArgs<ExtArgs>>): Prisma.Prisma__AssetToAppClient<runtime.Types.Result.GetResult<Prisma.$AssetToAppPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AssetToApps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetToAppCountArgs} args - Arguments to filter AssetToApps to count.
   * @example
   * // Count the number of AssetToApps
   * const count = await prisma.assetToApp.count({
   *   where: {
   *     // ... the filter for the AssetToApps we want to count
   *   }
   * })
  **/
  count<T extends AssetToAppCountArgs>(
    args?: Prisma.Subset<T, AssetToAppCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AssetToAppCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AssetToApp.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetToAppAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AssetToAppAggregateArgs>(args: Prisma.Subset<T, AssetToAppAggregateArgs>): Prisma.PrismaPromise<GetAssetToAppAggregateType<T>>

  /**
   * Group by AssetToApp.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetToAppGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AssetToAppGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AssetToAppGroupByArgs['orderBy'] }
      : { orderBy?: AssetToAppGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AssetToAppGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAssetToAppGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AssetToApp model
 */
readonly fields: AssetToAppFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AssetToApp.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AssetToAppClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  asset<T extends Prisma.AssetDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AssetDefaultArgs<ExtArgs>>): Prisma.Prisma__AssetClient<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  app<T extends Prisma.AppDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AppDefaultArgs<ExtArgs>>): Prisma.Prisma__AppClient<runtime.Types.Result.GetResult<Prisma.$AppPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AssetToApp model
 */
export interface AssetToAppFieldRefs {
  readonly assetId: Prisma.FieldRef<"AssetToApp", 'Int'>
  readonly appId: Prisma.FieldRef<"AssetToApp", 'Int'>
  readonly fieldId: Prisma.FieldRef<"AssetToApp", 'Int'>
}
    

// Custom InputTypes
/**
 * AssetToApp findUnique
 */
export type AssetToAppFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetToApp
   */
  select?: Prisma.AssetToAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetToApp
   */
  omit?: Prisma.AssetToAppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetToAppInclude<ExtArgs> | null
  /**
   * Filter, which AssetToApp to fetch.
   */
  where: Prisma.AssetToAppWhereUniqueInput
}

/**
 * AssetToApp findUniqueOrThrow
 */
export type AssetToAppFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetToApp
   */
  select?: Prisma.AssetToAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetToApp
   */
  omit?: Prisma.AssetToAppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetToAppInclude<ExtArgs> | null
  /**
   * Filter, which AssetToApp to fetch.
   */
  where: Prisma.AssetToAppWhereUniqueInput
}

/**
 * AssetToApp findFirst
 */
export type AssetToAppFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetToApp
   */
  select?: Prisma.AssetToAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetToApp
   */
  omit?: Prisma.AssetToAppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetToAppInclude<ExtArgs> | null
  /**
   * Filter, which AssetToApp to fetch.
   */
  where?: Prisma.AssetToAppWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssetToApps to fetch.
   */
  orderBy?: Prisma.AssetToAppOrderByWithRelationInput | Prisma.AssetToAppOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AssetToApps.
   */
  cursor?: Prisma.AssetToAppWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssetToApps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssetToApps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AssetToApps.
   */
  distinct?: Prisma.AssetToAppScalarFieldEnum | Prisma.AssetToAppScalarFieldEnum[]
}

/**
 * AssetToApp findFirstOrThrow
 */
export type AssetToAppFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetToApp
   */
  select?: Prisma.AssetToAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetToApp
   */
  omit?: Prisma.AssetToAppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetToAppInclude<ExtArgs> | null
  /**
   * Filter, which AssetToApp to fetch.
   */
  where?: Prisma.AssetToAppWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssetToApps to fetch.
   */
  orderBy?: Prisma.AssetToAppOrderByWithRelationInput | Prisma.AssetToAppOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AssetToApps.
   */
  cursor?: Prisma.AssetToAppWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssetToApps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssetToApps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AssetToApps.
   */
  distinct?: Prisma.AssetToAppScalarFieldEnum | Prisma.AssetToAppScalarFieldEnum[]
}

/**
 * AssetToApp findMany
 */
export type AssetToAppFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetToApp
   */
  select?: Prisma.AssetToAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetToApp
   */
  omit?: Prisma.AssetToAppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetToAppInclude<ExtArgs> | null
  /**
   * Filter, which AssetToApps to fetch.
   */
  where?: Prisma.AssetToAppWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssetToApps to fetch.
   */
  orderBy?: Prisma.AssetToAppOrderByWithRelationInput | Prisma.AssetToAppOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AssetToApps.
   */
  cursor?: Prisma.AssetToAppWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssetToApps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssetToApps.
   */
  skip?: number
  distinct?: Prisma.AssetToAppScalarFieldEnum | Prisma.AssetToAppScalarFieldEnum[]
}

/**
 * AssetToApp create
 */
export type AssetToAppCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetToApp
   */
  select?: Prisma.AssetToAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetToApp
   */
  omit?: Prisma.AssetToAppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetToAppInclude<ExtArgs> | null
  /**
   * The data needed to create a AssetToApp.
   */
  data: Prisma.XOR<Prisma.AssetToAppCreateInput, Prisma.AssetToAppUncheckedCreateInput>
}

/**
 * AssetToApp createMany
 */
export type AssetToAppCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AssetToApps.
   */
  data: Prisma.AssetToAppCreateManyInput | Prisma.AssetToAppCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AssetToApp createManyAndReturn
 */
export type AssetToAppCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetToApp
   */
  select?: Prisma.AssetToAppSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AssetToApp
   */
  omit?: Prisma.AssetToAppOmit<ExtArgs> | null
  /**
   * The data used to create many AssetToApps.
   */
  data: Prisma.AssetToAppCreateManyInput | Prisma.AssetToAppCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetToAppIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AssetToApp update
 */
export type AssetToAppUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetToApp
   */
  select?: Prisma.AssetToAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetToApp
   */
  omit?: Prisma.AssetToAppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetToAppInclude<ExtArgs> | null
  /**
   * The data needed to update a AssetToApp.
   */
  data: Prisma.XOR<Prisma.AssetToAppUpdateInput, Prisma.AssetToAppUncheckedUpdateInput>
  /**
   * Choose, which AssetToApp to update.
   */
  where: Prisma.AssetToAppWhereUniqueInput
}

/**
 * AssetToApp updateMany
 */
export type AssetToAppUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AssetToApps.
   */
  data: Prisma.XOR<Prisma.AssetToAppUpdateManyMutationInput, Prisma.AssetToAppUncheckedUpdateManyInput>
  /**
   * Filter which AssetToApps to update
   */
  where?: Prisma.AssetToAppWhereInput
  /**
   * Limit how many AssetToApps to update.
   */
  limit?: number
}

/**
 * AssetToApp updateManyAndReturn
 */
export type AssetToAppUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetToApp
   */
  select?: Prisma.AssetToAppSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AssetToApp
   */
  omit?: Prisma.AssetToAppOmit<ExtArgs> | null
  /**
   * The data used to update AssetToApps.
   */
  data: Prisma.XOR<Prisma.AssetToAppUpdateManyMutationInput, Prisma.AssetToAppUncheckedUpdateManyInput>
  /**
   * Filter which AssetToApps to update
   */
  where?: Prisma.AssetToAppWhereInput
  /**
   * Limit how many AssetToApps to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetToAppIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AssetToApp upsert
 */
export type AssetToAppUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetToApp
   */
  select?: Prisma.AssetToAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetToApp
   */
  omit?: Prisma.AssetToAppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetToAppInclude<ExtArgs> | null
  /**
   * The filter to search for the AssetToApp to update in case it exists.
   */
  where: Prisma.AssetToAppWhereUniqueInput
  /**
   * In case the AssetToApp found by the `where` argument doesn't exist, create a new AssetToApp with this data.
   */
  create: Prisma.XOR<Prisma.AssetToAppCreateInput, Prisma.AssetToAppUncheckedCreateInput>
  /**
   * In case the AssetToApp was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AssetToAppUpdateInput, Prisma.AssetToAppUncheckedUpdateInput>
}

/**
 * AssetToApp delete
 */
export type AssetToAppDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetToApp
   */
  select?: Prisma.AssetToAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetToApp
   */
  omit?: Prisma.AssetToAppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetToAppInclude<ExtArgs> | null
  /**
   * Filter which AssetToApp to delete.
   */
  where: Prisma.AssetToAppWhereUniqueInput
}

/**
 * AssetToApp deleteMany
 */
export type AssetToAppDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AssetToApps to delete
   */
  where?: Prisma.AssetToAppWhereInput
  /**
   * Limit how many AssetToApps to delete.
   */
  limit?: number
}

/**
 * AssetToApp without action
 */
export type AssetToAppDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetToApp
   */
  select?: Prisma.AssetToAppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetToApp
   */
  omit?: Prisma.AssetToAppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetToAppInclude<ExtArgs> | null
}
