
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AuthorizationChallenge` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model AuthorizationChallenge
 * 
 */
export type AuthorizationChallengeModel = runtime.Types.Result.DefaultSelection<Prisma.$AuthorizationChallengePayload>

export type AggregateAuthorizationChallenge = {
  _count: AuthorizationChallengeCountAggregateOutputType | null
  _avg: AuthorizationChallengeAvgAggregateOutputType | null
  _sum: AuthorizationChallengeSumAggregateOutputType | null
  _min: AuthorizationChallengeMinAggregateOutputType | null
  _max: AuthorizationChallengeMaxAggregateOutputType | null
}

export type AuthorizationChallengeAvgAggregateOutputType = {
  id: number | null
  appId: number | null
}

export type AuthorizationChallengeSumAggregateOutputType = {
  id: number | null
  appId: number | null
}

export type AuthorizationChallengeMinAggregateOutputType = {
  id: number | null
  sessionId: string | null
  appId: number | null
  authorizationCode: string | null
  challenge: string | null
  redirectUri: string | null
  created: Date | null
}

export type AuthorizationChallengeMaxAggregateOutputType = {
  id: number | null
  sessionId: string | null
  appId: number | null
  authorizationCode: string | null
  challenge: string | null
  redirectUri: string | null
  created: Date | null
}

export type AuthorizationChallengeCountAggregateOutputType = {
  id: number
  sessionId: number
  appId: number
  authorizationCode: number
  challenge: number
  redirectUri: number
  created: number
  _all: number
}


export type AuthorizationChallengeAvgAggregateInputType = {
  id?: true
  appId?: true
}

export type AuthorizationChallengeSumAggregateInputType = {
  id?: true
  appId?: true
}

export type AuthorizationChallengeMinAggregateInputType = {
  id?: true
  sessionId?: true
  appId?: true
  authorizationCode?: true
  challenge?: true
  redirectUri?: true
  created?: true
}

export type AuthorizationChallengeMaxAggregateInputType = {
  id?: true
  sessionId?: true
  appId?: true
  authorizationCode?: true
  challenge?: true
  redirectUri?: true
  created?: true
}

export type AuthorizationChallengeCountAggregateInputType = {
  id?: true
  sessionId?: true
  appId?: true
  authorizationCode?: true
  challenge?: true
  redirectUri?: true
  created?: true
  _all?: true
}

export type AuthorizationChallengeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AuthorizationChallenge to aggregate.
   */
  where?: Prisma.AuthorizationChallengeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthorizationChallenges to fetch.
   */
  orderBy?: Prisma.AuthorizationChallengeOrderByWithRelationInput | Prisma.AuthorizationChallengeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AuthorizationChallengeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthorizationChallenges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthorizationChallenges.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AuthorizationChallenges
  **/
  _count?: true | AuthorizationChallengeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AuthorizationChallengeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AuthorizationChallengeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AuthorizationChallengeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AuthorizationChallengeMaxAggregateInputType
}

export type GetAuthorizationChallengeAggregateType<T extends AuthorizationChallengeAggregateArgs> = {
      [P in keyof T & keyof AggregateAuthorizationChallenge]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAuthorizationChallenge[P]>
    : Prisma.GetScalarType<T[P], AggregateAuthorizationChallenge[P]>
}




export type AuthorizationChallengeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AuthorizationChallengeWhereInput
  orderBy?: Prisma.AuthorizationChallengeOrderByWithAggregationInput | Prisma.AuthorizationChallengeOrderByWithAggregationInput[]
  by: Prisma.AuthorizationChallengeScalarFieldEnum[] | Prisma.AuthorizationChallengeScalarFieldEnum
  having?: Prisma.AuthorizationChallengeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AuthorizationChallengeCountAggregateInputType | true
  _avg?: AuthorizationChallengeAvgAggregateInputType
  _sum?: AuthorizationChallengeSumAggregateInputType
  _min?: AuthorizationChallengeMinAggregateInputType
  _max?: AuthorizationChallengeMaxAggregateInputType
}

export type AuthorizationChallengeGroupByOutputType = {
  id: number
  sessionId: string
  appId: number
  authorizationCode: string
  challenge: string | null
  redirectUri: string
  created: Date
  _count: AuthorizationChallengeCountAggregateOutputType | null
  _avg: AuthorizationChallengeAvgAggregateOutputType | null
  _sum: AuthorizationChallengeSumAggregateOutputType | null
  _min: AuthorizationChallengeMinAggregateOutputType | null
  _max: AuthorizationChallengeMaxAggregateOutputType | null
}

type GetAuthorizationChallengeGroupByPayload<T extends AuthorizationChallengeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AuthorizationChallengeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AuthorizationChallengeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AuthorizationChallengeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AuthorizationChallengeGroupByOutputType[P]>
      }
    >
  >



export type AuthorizationChallengeWhereInput = {
  AND?: Prisma.AuthorizationChallengeWhereInput | Prisma.AuthorizationChallengeWhereInput[]
  OR?: Prisma.AuthorizationChallengeWhereInput[]
  NOT?: Prisma.AuthorizationChallengeWhereInput | Prisma.AuthorizationChallengeWhereInput[]
  id?: Prisma.IntFilter<"AuthorizationChallenge"> | number
  sessionId?: Prisma.StringFilter<"AuthorizationChallenge"> | string
  appId?: Prisma.IntFilter<"AuthorizationChallenge"> | number
  authorizationCode?: Prisma.StringFilter<"AuthorizationChallenge"> | string
  challenge?: Prisma.StringNullableFilter<"AuthorizationChallenge"> | string | null
  redirectUri?: Prisma.StringFilter<"AuthorizationChallenge"> | string
  created?: Prisma.DateTimeFilter<"AuthorizationChallenge"> | Date | string
  session?: Prisma.XOR<Prisma.SessionScalarRelationFilter, Prisma.SessionWhereInput>
  app?: Prisma.XOR<Prisma.AppScalarRelationFilter, Prisma.AppWhereInput>
}

export type AuthorizationChallengeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  authorizationCode?: Prisma.SortOrder
  challenge?: Prisma.SortOrderInput | Prisma.SortOrder
  redirectUri?: Prisma.SortOrder
  created?: Prisma.SortOrder
  session?: Prisma.SessionOrderByWithRelationInput
  app?: Prisma.AppOrderByWithRelationInput
}

export type AuthorizationChallengeWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  authorizationCode?: string
  challenge?: string
  AND?: Prisma.AuthorizationChallengeWhereInput | Prisma.AuthorizationChallengeWhereInput[]
  OR?: Prisma.AuthorizationChallengeWhereInput[]
  NOT?: Prisma.AuthorizationChallengeWhereInput | Prisma.AuthorizationChallengeWhereInput[]
  sessionId?: Prisma.StringFilter<"AuthorizationChallenge"> | string
  appId?: Prisma.IntFilter<"AuthorizationChallenge"> | number
  redirectUri?: Prisma.StringFilter<"AuthorizationChallenge"> | string
  created?: Prisma.DateTimeFilter<"AuthorizationChallenge"> | Date | string
  session?: Prisma.XOR<Prisma.SessionScalarRelationFilter, Prisma.SessionWhereInput>
  app?: Prisma.XOR<Prisma.AppScalarRelationFilter, Prisma.AppWhereInput>
}, "id" | "authorizationCode" | "challenge">

export type AuthorizationChallengeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  authorizationCode?: Prisma.SortOrder
  challenge?: Prisma.SortOrderInput | Prisma.SortOrder
  redirectUri?: Prisma.SortOrder
  created?: Prisma.SortOrder
  _count?: Prisma.AuthorizationChallengeCountOrderByAggregateInput
  _avg?: Prisma.AuthorizationChallengeAvgOrderByAggregateInput
  _max?: Prisma.AuthorizationChallengeMaxOrderByAggregateInput
  _min?: Prisma.AuthorizationChallengeMinOrderByAggregateInput
  _sum?: Prisma.AuthorizationChallengeSumOrderByAggregateInput
}

export type AuthorizationChallengeScalarWhereWithAggregatesInput = {
  AND?: Prisma.AuthorizationChallengeScalarWhereWithAggregatesInput | Prisma.AuthorizationChallengeScalarWhereWithAggregatesInput[]
  OR?: Prisma.AuthorizationChallengeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AuthorizationChallengeScalarWhereWithAggregatesInput | Prisma.AuthorizationChallengeScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"AuthorizationChallenge"> | number
  sessionId?: Prisma.StringWithAggregatesFilter<"AuthorizationChallenge"> | string
  appId?: Prisma.IntWithAggregatesFilter<"AuthorizationChallenge"> | number
  authorizationCode?: Prisma.StringWithAggregatesFilter<"AuthorizationChallenge"> | string
  challenge?: Prisma.StringNullableWithAggregatesFilter<"AuthorizationChallenge"> | string | null
  redirectUri?: Prisma.StringWithAggregatesFilter<"AuthorizationChallenge"> | string
  created?: Prisma.DateTimeWithAggregatesFilter<"AuthorizationChallenge"> | Date | string
}

export type AuthorizationChallengeCreateInput = {
  authorizationCode: string
  challenge?: string | null
  redirectUri: string
  created?: Date | string
  session: Prisma.SessionCreateNestedOneWithoutChallengesInput
  app: Prisma.AppCreateNestedOneWithoutAuthorizationChallengeInput
}

export type AuthorizationChallengeUncheckedCreateInput = {
  id?: number
  sessionId: string
  appId: number
  authorizationCode: string
  challenge?: string | null
  redirectUri: string
  created?: Date | string
}

export type AuthorizationChallengeUpdateInput = {
  authorizationCode?: Prisma.StringFieldUpdateOperationsInput | string
  challenge?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redirectUri?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  session?: Prisma.SessionUpdateOneRequiredWithoutChallengesNestedInput
  app?: Prisma.AppUpdateOneRequiredWithoutAuthorizationChallengeNestedInput
}

export type AuthorizationChallengeUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  appId?: Prisma.IntFieldUpdateOperationsInput | number
  authorizationCode?: Prisma.StringFieldUpdateOperationsInput | string
  challenge?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redirectUri?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuthorizationChallengeCreateManyInput = {
  id?: number
  sessionId: string
  appId: number
  authorizationCode: string
  challenge?: string | null
  redirectUri: string
  created?: Date | string
}

export type AuthorizationChallengeUpdateManyMutationInput = {
  authorizationCode?: Prisma.StringFieldUpdateOperationsInput | string
  challenge?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redirectUri?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuthorizationChallengeUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  appId?: Prisma.IntFieldUpdateOperationsInput | number
  authorizationCode?: Prisma.StringFieldUpdateOperationsInput | string
  challenge?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redirectUri?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuthorizationChallengeListRelationFilter = {
  every?: Prisma.AuthorizationChallengeWhereInput
  some?: Prisma.AuthorizationChallengeWhereInput
  none?: Prisma.AuthorizationChallengeWhereInput
}

export type AuthorizationChallengeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AuthorizationChallengeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  authorizationCode?: Prisma.SortOrder
  challenge?: Prisma.SortOrder
  redirectUri?: Prisma.SortOrder
  created?: Prisma.SortOrder
}

export type AuthorizationChallengeAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  appId?: Prisma.SortOrder
}

export type AuthorizationChallengeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  authorizationCode?: Prisma.SortOrder
  challenge?: Prisma.SortOrder
  redirectUri?: Prisma.SortOrder
  created?: Prisma.SortOrder
}

export type AuthorizationChallengeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  authorizationCode?: Prisma.SortOrder
  challenge?: Prisma.SortOrder
  redirectUri?: Prisma.SortOrder
  created?: Prisma.SortOrder
}

export type AuthorizationChallengeSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  appId?: Prisma.SortOrder
}

export type AuthorizationChallengeCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.AuthorizationChallengeCreateWithoutSessionInput, Prisma.AuthorizationChallengeUncheckedCreateWithoutSessionInput> | Prisma.AuthorizationChallengeCreateWithoutSessionInput[] | Prisma.AuthorizationChallengeUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.AuthorizationChallengeCreateOrConnectWithoutSessionInput | Prisma.AuthorizationChallengeCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.AuthorizationChallengeCreateManySessionInputEnvelope
  connect?: Prisma.AuthorizationChallengeWhereUniqueInput | Prisma.AuthorizationChallengeWhereUniqueInput[]
}

export type AuthorizationChallengeUncheckedCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.AuthorizationChallengeCreateWithoutSessionInput, Prisma.AuthorizationChallengeUncheckedCreateWithoutSessionInput> | Prisma.AuthorizationChallengeCreateWithoutSessionInput[] | Prisma.AuthorizationChallengeUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.AuthorizationChallengeCreateOrConnectWithoutSessionInput | Prisma.AuthorizationChallengeCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.AuthorizationChallengeCreateManySessionInputEnvelope
  connect?: Prisma.AuthorizationChallengeWhereUniqueInput | Prisma.AuthorizationChallengeWhereUniqueInput[]
}

export type AuthorizationChallengeUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.AuthorizationChallengeCreateWithoutSessionInput, Prisma.AuthorizationChallengeUncheckedCreateWithoutSessionInput> | Prisma.AuthorizationChallengeCreateWithoutSessionInput[] | Prisma.AuthorizationChallengeUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.AuthorizationChallengeCreateOrConnectWithoutSessionInput | Prisma.AuthorizationChallengeCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.AuthorizationChallengeUpsertWithWhereUniqueWithoutSessionInput | Prisma.AuthorizationChallengeUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.AuthorizationChallengeCreateManySessionInputEnvelope
  set?: Prisma.AuthorizationChallengeWhereUniqueInput | Prisma.AuthorizationChallengeWhereUniqueInput[]
  disconnect?: Prisma.AuthorizationChallengeWhereUniqueInput | Prisma.AuthorizationChallengeWhereUniqueInput[]
  delete?: Prisma.AuthorizationChallengeWhereUniqueInput | Prisma.AuthorizationChallengeWhereUniqueInput[]
  connect?: Prisma.AuthorizationChallengeWhereUniqueInput | Prisma.AuthorizationChallengeWhereUniqueInput[]
  update?: Prisma.AuthorizationChallengeUpdateWithWhereUniqueWithoutSessionInput | Prisma.AuthorizationChallengeUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.AuthorizationChallengeUpdateManyWithWhereWithoutSessionInput | Prisma.AuthorizationChallengeUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.AuthorizationChallengeScalarWhereInput | Prisma.AuthorizationChallengeScalarWhereInput[]
}

export type AuthorizationChallengeUncheckedUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.AuthorizationChallengeCreateWithoutSessionInput, Prisma.AuthorizationChallengeUncheckedCreateWithoutSessionInput> | Prisma.AuthorizationChallengeCreateWithoutSessionInput[] | Prisma.AuthorizationChallengeUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.AuthorizationChallengeCreateOrConnectWithoutSessionInput | Prisma.AuthorizationChallengeCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.AuthorizationChallengeUpsertWithWhereUniqueWithoutSessionInput | Prisma.AuthorizationChallengeUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.AuthorizationChallengeCreateManySessionInputEnvelope
  set?: Prisma.AuthorizationChallengeWhereUniqueInput | Prisma.AuthorizationChallengeWhereUniqueInput[]
  disconnect?: Prisma.AuthorizationChallengeWhereUniqueInput | Prisma.AuthorizationChallengeWhereUniqueInput[]
  delete?: Prisma.AuthorizationChallengeWhereUniqueInput | Prisma.AuthorizationChallengeWhereUniqueInput[]
  connect?: Prisma.AuthorizationChallengeWhereUniqueInput | Prisma.AuthorizationChallengeWhereUniqueInput[]
  update?: Prisma.AuthorizationChallengeUpdateWithWhereUniqueWithoutSessionInput | Prisma.AuthorizationChallengeUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.AuthorizationChallengeUpdateManyWithWhereWithoutSessionInput | Prisma.AuthorizationChallengeUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.AuthorizationChallengeScalarWhereInput | Prisma.AuthorizationChallengeScalarWhereInput[]
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type AuthorizationChallengeCreateNestedManyWithoutAppInput = {
  create?: Prisma.XOR<Prisma.AuthorizationChallengeCreateWithoutAppInput, Prisma.AuthorizationChallengeUncheckedCreateWithoutAppInput> | Prisma.AuthorizationChallengeCreateWithoutAppInput[] | Prisma.AuthorizationChallengeUncheckedCreateWithoutAppInput[]
  connectOrCreate?: Prisma.AuthorizationChallengeCreateOrConnectWithoutAppInput | Prisma.AuthorizationChallengeCreateOrConnectWithoutAppInput[]
  createMany?: Prisma.AuthorizationChallengeCreateManyAppInputEnvelope
  connect?: Prisma.AuthorizationChallengeWhereUniqueInput | Prisma.AuthorizationChallengeWhereUniqueInput[]
}

export type AuthorizationChallengeUncheckedCreateNestedManyWithoutAppInput = {
  create?: Prisma.XOR<Prisma.AuthorizationChallengeCreateWithoutAppInput, Prisma.AuthorizationChallengeUncheckedCreateWithoutAppInput> | Prisma.AuthorizationChallengeCreateWithoutAppInput[] | Prisma.AuthorizationChallengeUncheckedCreateWithoutAppInput[]
  connectOrCreate?: Prisma.AuthorizationChallengeCreateOrConnectWithoutAppInput | Prisma.AuthorizationChallengeCreateOrConnectWithoutAppInput[]
  createMany?: Prisma.AuthorizationChallengeCreateManyAppInputEnvelope
  connect?: Prisma.AuthorizationChallengeWhereUniqueInput | Prisma.AuthorizationChallengeWhereUniqueInput[]
}

export type AuthorizationChallengeUpdateManyWithoutAppNestedInput = {
  create?: Prisma.XOR<Prisma.AuthorizationChallengeCreateWithoutAppInput, Prisma.AuthorizationChallengeUncheckedCreateWithoutAppInput> | Prisma.AuthorizationChallengeCreateWithoutAppInput[] | Prisma.AuthorizationChallengeUncheckedCreateWithoutAppInput[]
  connectOrCreate?: Prisma.AuthorizationChallengeCreateOrConnectWithoutAppInput | Prisma.AuthorizationChallengeCreateOrConnectWithoutAppInput[]
  upsert?: Prisma.AuthorizationChallengeUpsertWithWhereUniqueWithoutAppInput | Prisma.AuthorizationChallengeUpsertWithWhereUniqueWithoutAppInput[]
  createMany?: Prisma.AuthorizationChallengeCreateManyAppInputEnvelope
  set?: Prisma.AuthorizationChallengeWhereUniqueInput | Prisma.AuthorizationChallengeWhereUniqueInput[]
  disconnect?: Prisma.AuthorizationChallengeWhereUniqueInput | Prisma.AuthorizationChallengeWhereUniqueInput[]
  delete?: Prisma.AuthorizationChallengeWhereUniqueInput | Prisma.AuthorizationChallengeWhereUniqueInput[]
  connect?: Prisma.AuthorizationChallengeWhereUniqueInput | Prisma.AuthorizationChallengeWhereUniqueInput[]
  update?: Prisma.AuthorizationChallengeUpdateWithWhereUniqueWithoutAppInput | Prisma.AuthorizationChallengeUpdateWithWhereUniqueWithoutAppInput[]
  updateMany?: Prisma.AuthorizationChallengeUpdateManyWithWhereWithoutAppInput | Prisma.AuthorizationChallengeUpdateManyWithWhereWithoutAppInput[]
  deleteMany?: Prisma.AuthorizationChallengeScalarWhereInput | Prisma.AuthorizationChallengeScalarWhereInput[]
}

export type AuthorizationChallengeUncheckedUpdateManyWithoutAppNestedInput = {
  create?: Prisma.XOR<Prisma.AuthorizationChallengeCreateWithoutAppInput, Prisma.AuthorizationChallengeUncheckedCreateWithoutAppInput> | Prisma.AuthorizationChallengeCreateWithoutAppInput[] | Prisma.AuthorizationChallengeUncheckedCreateWithoutAppInput[]
  connectOrCreate?: Prisma.AuthorizationChallengeCreateOrConnectWithoutAppInput | Prisma.AuthorizationChallengeCreateOrConnectWithoutAppInput[]
  upsert?: Prisma.AuthorizationChallengeUpsertWithWhereUniqueWithoutAppInput | Prisma.AuthorizationChallengeUpsertWithWhereUniqueWithoutAppInput[]
  createMany?: Prisma.AuthorizationChallengeCreateManyAppInputEnvelope
  set?: Prisma.AuthorizationChallengeWhereUniqueInput | Prisma.AuthorizationChallengeWhereUniqueInput[]
  disconnect?: Prisma.AuthorizationChallengeWhereUniqueInput | Prisma.AuthorizationChallengeWhereUniqueInput[]
  delete?: Prisma.AuthorizationChallengeWhereUniqueInput | Prisma.AuthorizationChallengeWhereUniqueInput[]
  connect?: Prisma.AuthorizationChallengeWhereUniqueInput | Prisma.AuthorizationChallengeWhereUniqueInput[]
  update?: Prisma.AuthorizationChallengeUpdateWithWhereUniqueWithoutAppInput | Prisma.AuthorizationChallengeUpdateWithWhereUniqueWithoutAppInput[]
  updateMany?: Prisma.AuthorizationChallengeUpdateManyWithWhereWithoutAppInput | Prisma.AuthorizationChallengeUpdateManyWithWhereWithoutAppInput[]
  deleteMany?: Prisma.AuthorizationChallengeScalarWhereInput | Prisma.AuthorizationChallengeScalarWhereInput[]
}

export type AuthorizationChallengeCreateWithoutSessionInput = {
  authorizationCode: string
  challenge?: string | null
  redirectUri: string
  created?: Date | string
  app: Prisma.AppCreateNestedOneWithoutAuthorizationChallengeInput
}

export type AuthorizationChallengeUncheckedCreateWithoutSessionInput = {
  id?: number
  appId: number
  authorizationCode: string
  challenge?: string | null
  redirectUri: string
  created?: Date | string
}

export type AuthorizationChallengeCreateOrConnectWithoutSessionInput = {
  where: Prisma.AuthorizationChallengeWhereUniqueInput
  create: Prisma.XOR<Prisma.AuthorizationChallengeCreateWithoutSessionInput, Prisma.AuthorizationChallengeUncheckedCreateWithoutSessionInput>
}

export type AuthorizationChallengeCreateManySessionInputEnvelope = {
  data: Prisma.AuthorizationChallengeCreateManySessionInput | Prisma.AuthorizationChallengeCreateManySessionInput[]
  skipDuplicates?: boolean
}

export type AuthorizationChallengeUpsertWithWhereUniqueWithoutSessionInput = {
  where: Prisma.AuthorizationChallengeWhereUniqueInput
  update: Prisma.XOR<Prisma.AuthorizationChallengeUpdateWithoutSessionInput, Prisma.AuthorizationChallengeUncheckedUpdateWithoutSessionInput>
  create: Prisma.XOR<Prisma.AuthorizationChallengeCreateWithoutSessionInput, Prisma.AuthorizationChallengeUncheckedCreateWithoutSessionInput>
}

export type AuthorizationChallengeUpdateWithWhereUniqueWithoutSessionInput = {
  where: Prisma.AuthorizationChallengeWhereUniqueInput
  data: Prisma.XOR<Prisma.AuthorizationChallengeUpdateWithoutSessionInput, Prisma.AuthorizationChallengeUncheckedUpdateWithoutSessionInput>
}

export type AuthorizationChallengeUpdateManyWithWhereWithoutSessionInput = {
  where: Prisma.AuthorizationChallengeScalarWhereInput
  data: Prisma.XOR<Prisma.AuthorizationChallengeUpdateManyMutationInput, Prisma.AuthorizationChallengeUncheckedUpdateManyWithoutSessionInput>
}

export type AuthorizationChallengeScalarWhereInput = {
  AND?: Prisma.AuthorizationChallengeScalarWhereInput | Prisma.AuthorizationChallengeScalarWhereInput[]
  OR?: Prisma.AuthorizationChallengeScalarWhereInput[]
  NOT?: Prisma.AuthorizationChallengeScalarWhereInput | Prisma.AuthorizationChallengeScalarWhereInput[]
  id?: Prisma.IntFilter<"AuthorizationChallenge"> | number
  sessionId?: Prisma.StringFilter<"AuthorizationChallenge"> | string
  appId?: Prisma.IntFilter<"AuthorizationChallenge"> | number
  authorizationCode?: Prisma.StringFilter<"AuthorizationChallenge"> | string
  challenge?: Prisma.StringNullableFilter<"AuthorizationChallenge"> | string | null
  redirectUri?: Prisma.StringFilter<"AuthorizationChallenge"> | string
  created?: Prisma.DateTimeFilter<"AuthorizationChallenge"> | Date | string
}

export type AuthorizationChallengeCreateWithoutAppInput = {
  authorizationCode: string
  challenge?: string | null
  redirectUri: string
  created?: Date | string
  session: Prisma.SessionCreateNestedOneWithoutChallengesInput
}

export type AuthorizationChallengeUncheckedCreateWithoutAppInput = {
  id?: number
  sessionId: string
  authorizationCode: string
  challenge?: string | null
  redirectUri: string
  created?: Date | string
}

export type AuthorizationChallengeCreateOrConnectWithoutAppInput = {
  where: Prisma.AuthorizationChallengeWhereUniqueInput
  create: Prisma.XOR<Prisma.AuthorizationChallengeCreateWithoutAppInput, Prisma.AuthorizationChallengeUncheckedCreateWithoutAppInput>
}

export type AuthorizationChallengeCreateManyAppInputEnvelope = {
  data: Prisma.AuthorizationChallengeCreateManyAppInput | Prisma.AuthorizationChallengeCreateManyAppInput[]
  skipDuplicates?: boolean
}

export type AuthorizationChallengeUpsertWithWhereUniqueWithoutAppInput = {
  where: Prisma.AuthorizationChallengeWhereUniqueInput
  update: Prisma.XOR<Prisma.AuthorizationChallengeUpdateWithoutAppInput, Prisma.AuthorizationChallengeUncheckedUpdateWithoutAppInput>
  create: Prisma.XOR<Prisma.AuthorizationChallengeCreateWithoutAppInput, Prisma.AuthorizationChallengeUncheckedCreateWithoutAppInput>
}

export type AuthorizationChallengeUpdateWithWhereUniqueWithoutAppInput = {
  where: Prisma.AuthorizationChallengeWhereUniqueInput
  data: Prisma.XOR<Prisma.AuthorizationChallengeUpdateWithoutAppInput, Prisma.AuthorizationChallengeUncheckedUpdateWithoutAppInput>
}

export type AuthorizationChallengeUpdateManyWithWhereWithoutAppInput = {
  where: Prisma.AuthorizationChallengeScalarWhereInput
  data: Prisma.XOR<Prisma.AuthorizationChallengeUpdateManyMutationInput, Prisma.AuthorizationChallengeUncheckedUpdateManyWithoutAppInput>
}

export type AuthorizationChallengeCreateManySessionInput = {
  id?: number
  appId: number
  authorizationCode: string
  challenge?: string | null
  redirectUri: string
  created?: Date | string
}

export type AuthorizationChallengeUpdateWithoutSessionInput = {
  authorizationCode?: Prisma.StringFieldUpdateOperationsInput | string
  challenge?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redirectUri?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  app?: Prisma.AppUpdateOneRequiredWithoutAuthorizationChallengeNestedInput
}

export type AuthorizationChallengeUncheckedUpdateWithoutSessionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  appId?: Prisma.IntFieldUpdateOperationsInput | number
  authorizationCode?: Prisma.StringFieldUpdateOperationsInput | string
  challenge?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redirectUri?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuthorizationChallengeUncheckedUpdateManyWithoutSessionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  appId?: Prisma.IntFieldUpdateOperationsInput | number
  authorizationCode?: Prisma.StringFieldUpdateOperationsInput | string
  challenge?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redirectUri?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuthorizationChallengeCreateManyAppInput = {
  id?: number
  sessionId: string
  authorizationCode: string
  challenge?: string | null
  redirectUri: string
  created?: Date | string
}

export type AuthorizationChallengeUpdateWithoutAppInput = {
  authorizationCode?: Prisma.StringFieldUpdateOperationsInput | string
  challenge?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redirectUri?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  session?: Prisma.SessionUpdateOneRequiredWithoutChallengesNestedInput
}

export type AuthorizationChallengeUncheckedUpdateWithoutAppInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  authorizationCode?: Prisma.StringFieldUpdateOperationsInput | string
  challenge?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redirectUri?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuthorizationChallengeUncheckedUpdateManyWithoutAppInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  authorizationCode?: Prisma.StringFieldUpdateOperationsInput | string
  challenge?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redirectUri?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AuthorizationChallengeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  appId?: boolean
  authorizationCode?: boolean
  challenge?: boolean
  redirectUri?: boolean
  created?: boolean
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
}, ExtArgs["result"]["authorizationChallenge"]>

export type AuthorizationChallengeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  appId?: boolean
  authorizationCode?: boolean
  challenge?: boolean
  redirectUri?: boolean
  created?: boolean
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
}, ExtArgs["result"]["authorizationChallenge"]>

export type AuthorizationChallengeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  appId?: boolean
  authorizationCode?: boolean
  challenge?: boolean
  redirectUri?: boolean
  created?: boolean
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
}, ExtArgs["result"]["authorizationChallenge"]>

export type AuthorizationChallengeSelectScalar = {
  id?: boolean
  sessionId?: boolean
  appId?: boolean
  authorizationCode?: boolean
  challenge?: boolean
  redirectUri?: boolean
  created?: boolean
}

export type AuthorizationChallengeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "sessionId" | "appId" | "authorizationCode" | "challenge" | "redirectUri" | "created", ExtArgs["result"]["authorizationChallenge"]>
export type AuthorizationChallengeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
}
export type AuthorizationChallengeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
}
export type AuthorizationChallengeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
}

export type $AuthorizationChallengePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AuthorizationChallenge"
  objects: {
    session: Prisma.$SessionPayload<ExtArgs>
    app: Prisma.$AppPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    sessionId: string
    appId: number
    authorizationCode: string
    challenge: string | null
    redirectUri: string
    created: Date
  }, ExtArgs["result"]["authorizationChallenge"]>
  composites: {}
}

export type AuthorizationChallengeGetPayload<S extends boolean | null | undefined | AuthorizationChallengeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AuthorizationChallengePayload, S>

export type AuthorizationChallengeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AuthorizationChallengeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AuthorizationChallengeCountAggregateInputType | true
  }

export interface AuthorizationChallengeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AuthorizationChallenge'], meta: { name: 'AuthorizationChallenge' } }
  /**
   * Find zero or one AuthorizationChallenge that matches the filter.
   * @param {AuthorizationChallengeFindUniqueArgs} args - Arguments to find a AuthorizationChallenge
   * @example
   * // Get one AuthorizationChallenge
   * const authorizationChallenge = await prisma.authorizationChallenge.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AuthorizationChallengeFindUniqueArgs>(args: Prisma.SelectSubset<T, AuthorizationChallengeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AuthorizationChallengeClient<runtime.Types.Result.GetResult<Prisma.$AuthorizationChallengePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AuthorizationChallenge that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AuthorizationChallengeFindUniqueOrThrowArgs} args - Arguments to find a AuthorizationChallenge
   * @example
   * // Get one AuthorizationChallenge
   * const authorizationChallenge = await prisma.authorizationChallenge.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AuthorizationChallengeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AuthorizationChallengeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AuthorizationChallengeClient<runtime.Types.Result.GetResult<Prisma.$AuthorizationChallengePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AuthorizationChallenge that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthorizationChallengeFindFirstArgs} args - Arguments to find a AuthorizationChallenge
   * @example
   * // Get one AuthorizationChallenge
   * const authorizationChallenge = await prisma.authorizationChallenge.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AuthorizationChallengeFindFirstArgs>(args?: Prisma.SelectSubset<T, AuthorizationChallengeFindFirstArgs<ExtArgs>>): Prisma.Prisma__AuthorizationChallengeClient<runtime.Types.Result.GetResult<Prisma.$AuthorizationChallengePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AuthorizationChallenge that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthorizationChallengeFindFirstOrThrowArgs} args - Arguments to find a AuthorizationChallenge
   * @example
   * // Get one AuthorizationChallenge
   * const authorizationChallenge = await prisma.authorizationChallenge.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AuthorizationChallengeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AuthorizationChallengeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AuthorizationChallengeClient<runtime.Types.Result.GetResult<Prisma.$AuthorizationChallengePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AuthorizationChallenges that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthorizationChallengeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AuthorizationChallenges
   * const authorizationChallenges = await prisma.authorizationChallenge.findMany()
   * 
   * // Get first 10 AuthorizationChallenges
   * const authorizationChallenges = await prisma.authorizationChallenge.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const authorizationChallengeWithIdOnly = await prisma.authorizationChallenge.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AuthorizationChallengeFindManyArgs>(args?: Prisma.SelectSubset<T, AuthorizationChallengeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthorizationChallengePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AuthorizationChallenge.
   * @param {AuthorizationChallengeCreateArgs} args - Arguments to create a AuthorizationChallenge.
   * @example
   * // Create one AuthorizationChallenge
   * const AuthorizationChallenge = await prisma.authorizationChallenge.create({
   *   data: {
   *     // ... data to create a AuthorizationChallenge
   *   }
   * })
   * 
   */
  create<T extends AuthorizationChallengeCreateArgs>(args: Prisma.SelectSubset<T, AuthorizationChallengeCreateArgs<ExtArgs>>): Prisma.Prisma__AuthorizationChallengeClient<runtime.Types.Result.GetResult<Prisma.$AuthorizationChallengePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AuthorizationChallenges.
   * @param {AuthorizationChallengeCreateManyArgs} args - Arguments to create many AuthorizationChallenges.
   * @example
   * // Create many AuthorizationChallenges
   * const authorizationChallenge = await prisma.authorizationChallenge.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AuthorizationChallengeCreateManyArgs>(args?: Prisma.SelectSubset<T, AuthorizationChallengeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AuthorizationChallenges and returns the data saved in the database.
   * @param {AuthorizationChallengeCreateManyAndReturnArgs} args - Arguments to create many AuthorizationChallenges.
   * @example
   * // Create many AuthorizationChallenges
   * const authorizationChallenge = await prisma.authorizationChallenge.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AuthorizationChallenges and only return the `id`
   * const authorizationChallengeWithIdOnly = await prisma.authorizationChallenge.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AuthorizationChallengeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AuthorizationChallengeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthorizationChallengePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AuthorizationChallenge.
   * @param {AuthorizationChallengeDeleteArgs} args - Arguments to delete one AuthorizationChallenge.
   * @example
   * // Delete one AuthorizationChallenge
   * const AuthorizationChallenge = await prisma.authorizationChallenge.delete({
   *   where: {
   *     // ... filter to delete one AuthorizationChallenge
   *   }
   * })
   * 
   */
  delete<T extends AuthorizationChallengeDeleteArgs>(args: Prisma.SelectSubset<T, AuthorizationChallengeDeleteArgs<ExtArgs>>): Prisma.Prisma__AuthorizationChallengeClient<runtime.Types.Result.GetResult<Prisma.$AuthorizationChallengePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AuthorizationChallenge.
   * @param {AuthorizationChallengeUpdateArgs} args - Arguments to update one AuthorizationChallenge.
   * @example
   * // Update one AuthorizationChallenge
   * const authorizationChallenge = await prisma.authorizationChallenge.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AuthorizationChallengeUpdateArgs>(args: Prisma.SelectSubset<T, AuthorizationChallengeUpdateArgs<ExtArgs>>): Prisma.Prisma__AuthorizationChallengeClient<runtime.Types.Result.GetResult<Prisma.$AuthorizationChallengePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AuthorizationChallenges.
   * @param {AuthorizationChallengeDeleteManyArgs} args - Arguments to filter AuthorizationChallenges to delete.
   * @example
   * // Delete a few AuthorizationChallenges
   * const { count } = await prisma.authorizationChallenge.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AuthorizationChallengeDeleteManyArgs>(args?: Prisma.SelectSubset<T, AuthorizationChallengeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AuthorizationChallenges.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthorizationChallengeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AuthorizationChallenges
   * const authorizationChallenge = await prisma.authorizationChallenge.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AuthorizationChallengeUpdateManyArgs>(args: Prisma.SelectSubset<T, AuthorizationChallengeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AuthorizationChallenges and returns the data updated in the database.
   * @param {AuthorizationChallengeUpdateManyAndReturnArgs} args - Arguments to update many AuthorizationChallenges.
   * @example
   * // Update many AuthorizationChallenges
   * const authorizationChallenge = await prisma.authorizationChallenge.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AuthorizationChallenges and only return the `id`
   * const authorizationChallengeWithIdOnly = await prisma.authorizationChallenge.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AuthorizationChallengeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AuthorizationChallengeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthorizationChallengePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AuthorizationChallenge.
   * @param {AuthorizationChallengeUpsertArgs} args - Arguments to update or create a AuthorizationChallenge.
   * @example
   * // Update or create a AuthorizationChallenge
   * const authorizationChallenge = await prisma.authorizationChallenge.upsert({
   *   create: {
   *     // ... data to create a AuthorizationChallenge
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AuthorizationChallenge we want to update
   *   }
   * })
   */
  upsert<T extends AuthorizationChallengeUpsertArgs>(args: Prisma.SelectSubset<T, AuthorizationChallengeUpsertArgs<ExtArgs>>): Prisma.Prisma__AuthorizationChallengeClient<runtime.Types.Result.GetResult<Prisma.$AuthorizationChallengePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AuthorizationChallenges.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthorizationChallengeCountArgs} args - Arguments to filter AuthorizationChallenges to count.
   * @example
   * // Count the number of AuthorizationChallenges
   * const count = await prisma.authorizationChallenge.count({
   *   where: {
   *     // ... the filter for the AuthorizationChallenges we want to count
   *   }
   * })
  **/
  count<T extends AuthorizationChallengeCountArgs>(
    args?: Prisma.Subset<T, AuthorizationChallengeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AuthorizationChallengeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AuthorizationChallenge.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthorizationChallengeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AuthorizationChallengeAggregateArgs>(args: Prisma.Subset<T, AuthorizationChallengeAggregateArgs>): Prisma.PrismaPromise<GetAuthorizationChallengeAggregateType<T>>

  /**
   * Group by AuthorizationChallenge.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthorizationChallengeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AuthorizationChallengeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AuthorizationChallengeGroupByArgs['orderBy'] }
      : { orderBy?: AuthorizationChallengeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AuthorizationChallengeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAuthorizationChallengeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AuthorizationChallenge model
 */
readonly fields: AuthorizationChallengeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AuthorizationChallenge.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AuthorizationChallengeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  session<T extends Prisma.SessionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SessionDefaultArgs<ExtArgs>>): Prisma.Prisma__SessionClient<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  app<T extends Prisma.AppDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AppDefaultArgs<ExtArgs>>): Prisma.Prisma__AppClient<runtime.Types.Result.GetResult<Prisma.$AppPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AuthorizationChallenge model
 */
export interface AuthorizationChallengeFieldRefs {
  readonly id: Prisma.FieldRef<"AuthorizationChallenge", 'Int'>
  readonly sessionId: Prisma.FieldRef<"AuthorizationChallenge", 'String'>
  readonly appId: Prisma.FieldRef<"AuthorizationChallenge", 'Int'>
  readonly authorizationCode: Prisma.FieldRef<"AuthorizationChallenge", 'String'>
  readonly challenge: Prisma.FieldRef<"AuthorizationChallenge", 'String'>
  readonly redirectUri: Prisma.FieldRef<"AuthorizationChallenge", 'String'>
  readonly created: Prisma.FieldRef<"AuthorizationChallenge", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AuthorizationChallenge findUnique
 */
export type AuthorizationChallengeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthorizationChallenge
   */
  select?: Prisma.AuthorizationChallengeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthorizationChallenge
   */
  omit?: Prisma.AuthorizationChallengeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthorizationChallengeInclude<ExtArgs> | null
  /**
   * Filter, which AuthorizationChallenge to fetch.
   */
  where: Prisma.AuthorizationChallengeWhereUniqueInput
}

/**
 * AuthorizationChallenge findUniqueOrThrow
 */
export type AuthorizationChallengeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthorizationChallenge
   */
  select?: Prisma.AuthorizationChallengeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthorizationChallenge
   */
  omit?: Prisma.AuthorizationChallengeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthorizationChallengeInclude<ExtArgs> | null
  /**
   * Filter, which AuthorizationChallenge to fetch.
   */
  where: Prisma.AuthorizationChallengeWhereUniqueInput
}

/**
 * AuthorizationChallenge findFirst
 */
export type AuthorizationChallengeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthorizationChallenge
   */
  select?: Prisma.AuthorizationChallengeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthorizationChallenge
   */
  omit?: Prisma.AuthorizationChallengeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthorizationChallengeInclude<ExtArgs> | null
  /**
   * Filter, which AuthorizationChallenge to fetch.
   */
  where?: Prisma.AuthorizationChallengeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthorizationChallenges to fetch.
   */
  orderBy?: Prisma.AuthorizationChallengeOrderByWithRelationInput | Prisma.AuthorizationChallengeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AuthorizationChallenges.
   */
  cursor?: Prisma.AuthorizationChallengeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthorizationChallenges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthorizationChallenges.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AuthorizationChallenges.
   */
  distinct?: Prisma.AuthorizationChallengeScalarFieldEnum | Prisma.AuthorizationChallengeScalarFieldEnum[]
}

/**
 * AuthorizationChallenge findFirstOrThrow
 */
export type AuthorizationChallengeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthorizationChallenge
   */
  select?: Prisma.AuthorizationChallengeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthorizationChallenge
   */
  omit?: Prisma.AuthorizationChallengeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthorizationChallengeInclude<ExtArgs> | null
  /**
   * Filter, which AuthorizationChallenge to fetch.
   */
  where?: Prisma.AuthorizationChallengeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthorizationChallenges to fetch.
   */
  orderBy?: Prisma.AuthorizationChallengeOrderByWithRelationInput | Prisma.AuthorizationChallengeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AuthorizationChallenges.
   */
  cursor?: Prisma.AuthorizationChallengeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthorizationChallenges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthorizationChallenges.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AuthorizationChallenges.
   */
  distinct?: Prisma.AuthorizationChallengeScalarFieldEnum | Prisma.AuthorizationChallengeScalarFieldEnum[]
}

/**
 * AuthorizationChallenge findMany
 */
export type AuthorizationChallengeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthorizationChallenge
   */
  select?: Prisma.AuthorizationChallengeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthorizationChallenge
   */
  omit?: Prisma.AuthorizationChallengeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthorizationChallengeInclude<ExtArgs> | null
  /**
   * Filter, which AuthorizationChallenges to fetch.
   */
  where?: Prisma.AuthorizationChallengeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthorizationChallenges to fetch.
   */
  orderBy?: Prisma.AuthorizationChallengeOrderByWithRelationInput | Prisma.AuthorizationChallengeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AuthorizationChallenges.
   */
  cursor?: Prisma.AuthorizationChallengeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthorizationChallenges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthorizationChallenges.
   */
  skip?: number
  distinct?: Prisma.AuthorizationChallengeScalarFieldEnum | Prisma.AuthorizationChallengeScalarFieldEnum[]
}

/**
 * AuthorizationChallenge create
 */
export type AuthorizationChallengeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthorizationChallenge
   */
  select?: Prisma.AuthorizationChallengeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthorizationChallenge
   */
  omit?: Prisma.AuthorizationChallengeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthorizationChallengeInclude<ExtArgs> | null
  /**
   * The data needed to create a AuthorizationChallenge.
   */
  data: Prisma.XOR<Prisma.AuthorizationChallengeCreateInput, Prisma.AuthorizationChallengeUncheckedCreateInput>
}

/**
 * AuthorizationChallenge createMany
 */
export type AuthorizationChallengeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AuthorizationChallenges.
   */
  data: Prisma.AuthorizationChallengeCreateManyInput | Prisma.AuthorizationChallengeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AuthorizationChallenge createManyAndReturn
 */
export type AuthorizationChallengeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthorizationChallenge
   */
  select?: Prisma.AuthorizationChallengeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AuthorizationChallenge
   */
  omit?: Prisma.AuthorizationChallengeOmit<ExtArgs> | null
  /**
   * The data used to create many AuthorizationChallenges.
   */
  data: Prisma.AuthorizationChallengeCreateManyInput | Prisma.AuthorizationChallengeCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthorizationChallengeIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AuthorizationChallenge update
 */
export type AuthorizationChallengeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthorizationChallenge
   */
  select?: Prisma.AuthorizationChallengeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthorizationChallenge
   */
  omit?: Prisma.AuthorizationChallengeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthorizationChallengeInclude<ExtArgs> | null
  /**
   * The data needed to update a AuthorizationChallenge.
   */
  data: Prisma.XOR<Prisma.AuthorizationChallengeUpdateInput, Prisma.AuthorizationChallengeUncheckedUpdateInput>
  /**
   * Choose, which AuthorizationChallenge to update.
   */
  where: Prisma.AuthorizationChallengeWhereUniqueInput
}

/**
 * AuthorizationChallenge updateMany
 */
export type AuthorizationChallengeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AuthorizationChallenges.
   */
  data: Prisma.XOR<Prisma.AuthorizationChallengeUpdateManyMutationInput, Prisma.AuthorizationChallengeUncheckedUpdateManyInput>
  /**
   * Filter which AuthorizationChallenges to update
   */
  where?: Prisma.AuthorizationChallengeWhereInput
  /**
   * Limit how many AuthorizationChallenges to update.
   */
  limit?: number
}

/**
 * AuthorizationChallenge updateManyAndReturn
 */
export type AuthorizationChallengeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthorizationChallenge
   */
  select?: Prisma.AuthorizationChallengeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AuthorizationChallenge
   */
  omit?: Prisma.AuthorizationChallengeOmit<ExtArgs> | null
  /**
   * The data used to update AuthorizationChallenges.
   */
  data: Prisma.XOR<Prisma.AuthorizationChallengeUpdateManyMutationInput, Prisma.AuthorizationChallengeUncheckedUpdateManyInput>
  /**
   * Filter which AuthorizationChallenges to update
   */
  where?: Prisma.AuthorizationChallengeWhereInput
  /**
   * Limit how many AuthorizationChallenges to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthorizationChallengeIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AuthorizationChallenge upsert
 */
export type AuthorizationChallengeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthorizationChallenge
   */
  select?: Prisma.AuthorizationChallengeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthorizationChallenge
   */
  omit?: Prisma.AuthorizationChallengeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthorizationChallengeInclude<ExtArgs> | null
  /**
   * The filter to search for the AuthorizationChallenge to update in case it exists.
   */
  where: Prisma.AuthorizationChallengeWhereUniqueInput
  /**
   * In case the AuthorizationChallenge found by the `where` argument doesn't exist, create a new AuthorizationChallenge with this data.
   */
  create: Prisma.XOR<Prisma.AuthorizationChallengeCreateInput, Prisma.AuthorizationChallengeUncheckedCreateInput>
  /**
   * In case the AuthorizationChallenge was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AuthorizationChallengeUpdateInput, Prisma.AuthorizationChallengeUncheckedUpdateInput>
}

/**
 * AuthorizationChallenge delete
 */
export type AuthorizationChallengeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthorizationChallenge
   */
  select?: Prisma.AuthorizationChallengeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthorizationChallenge
   */
  omit?: Prisma.AuthorizationChallengeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthorizationChallengeInclude<ExtArgs> | null
  /**
   * Filter which AuthorizationChallenge to delete.
   */
  where: Prisma.AuthorizationChallengeWhereUniqueInput
}

/**
 * AuthorizationChallenge deleteMany
 */
export type AuthorizationChallengeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AuthorizationChallenges to delete
   */
  where?: Prisma.AuthorizationChallengeWhereInput
  /**
   * Limit how many AuthorizationChallenges to delete.
   */
  limit?: number
}

/**
 * AuthorizationChallenge without action
 */
export type AuthorizationChallengeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthorizationChallenge
   */
  select?: Prisma.AuthorizationChallengeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthorizationChallenge
   */
  omit?: Prisma.AuthorizationChallengeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthorizationChallengeInclude<ExtArgs> | null
}
