
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AuthorizationInstance` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AuthorizationInstance
 * 
 */
export type AuthorizationInstanceModel = runtime.Types.Result.DefaultSelection<Prisma.$AuthorizationInstancePayload>

export type AggregateAuthorizationInstance = {
  _count: AuthorizationInstanceCountAggregateOutputType | null
  _avg: AuthorizationInstanceAvgAggregateOutputType | null
  _sum: AuthorizationInstanceSumAggregateOutputType | null
  _min: AuthorizationInstanceMinAggregateOutputType | null
  _max: AuthorizationInstanceMaxAggregateOutputType | null
}

export type AuthorizationInstanceAvgAggregateOutputType = {
  id: number | null
  appId: number | null
  refreshTokenExpire: number | null
}

export type AuthorizationInstanceSumAggregateOutputType = {
  id: number | null
  appId: number | null
  refreshTokenExpire: number | null
}

export type AuthorizationInstanceMinAggregateOutputType = {
  id: number | null
  sessionId: string | null
  appId: number | null
  refreshToken: string | null
  refreshTokenExpire: number | null
}

export type AuthorizationInstanceMaxAggregateOutputType = {
  id: number | null
  sessionId: string | null
  appId: number | null
  refreshToken: string | null
  refreshTokenExpire: number | null
}

export type AuthorizationInstanceCountAggregateOutputType = {
  id: number
  sessionId: number
  appId: number
  refreshToken: number
  refreshTokenExpire: number
  _all: number
}


export type AuthorizationInstanceAvgAggregateInputType = {
  id?: true
  appId?: true
  refreshTokenExpire?: true
}

export type AuthorizationInstanceSumAggregateInputType = {
  id?: true
  appId?: true
  refreshTokenExpire?: true
}

export type AuthorizationInstanceMinAggregateInputType = {
  id?: true
  sessionId?: true
  appId?: true
  refreshToken?: true
  refreshTokenExpire?: true
}

export type AuthorizationInstanceMaxAggregateInputType = {
  id?: true
  sessionId?: true
  appId?: true
  refreshToken?: true
  refreshTokenExpire?: true
}

export type AuthorizationInstanceCountAggregateInputType = {
  id?: true
  sessionId?: true
  appId?: true
  refreshToken?: true
  refreshTokenExpire?: true
  _all?: true
}

export type AuthorizationInstanceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AuthorizationInstance to aggregate.
   */
  where?: Prisma.AuthorizationInstanceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthorizationInstances to fetch.
   */
  orderBy?: Prisma.AuthorizationInstanceOrderByWithRelationInput | Prisma.AuthorizationInstanceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AuthorizationInstanceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthorizationInstances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthorizationInstances.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AuthorizationInstances
  **/
  _count?: true | AuthorizationInstanceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AuthorizationInstanceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AuthorizationInstanceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AuthorizationInstanceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AuthorizationInstanceMaxAggregateInputType
}

export type GetAuthorizationInstanceAggregateType<T extends AuthorizationInstanceAggregateArgs> = {
      [P in keyof T & keyof AggregateAuthorizationInstance]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAuthorizationInstance[P]>
    : Prisma.GetScalarType<T[P], AggregateAuthorizationInstance[P]>
}




export type AuthorizationInstanceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AuthorizationInstanceWhereInput
  orderBy?: Prisma.AuthorizationInstanceOrderByWithAggregationInput | Prisma.AuthorizationInstanceOrderByWithAggregationInput[]
  by: Prisma.AuthorizationInstanceScalarFieldEnum[] | Prisma.AuthorizationInstanceScalarFieldEnum
  having?: Prisma.AuthorizationInstanceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AuthorizationInstanceCountAggregateInputType | true
  _avg?: AuthorizationInstanceAvgAggregateInputType
  _sum?: AuthorizationInstanceSumAggregateInputType
  _min?: AuthorizationInstanceMinAggregateInputType
  _max?: AuthorizationInstanceMaxAggregateInputType
}

export type AuthorizationInstanceGroupByOutputType = {
  id: number
  sessionId: string
  appId: number
  refreshToken: string
  refreshTokenExpire: number
  _count: AuthorizationInstanceCountAggregateOutputType | null
  _avg: AuthorizationInstanceAvgAggregateOutputType | null
  _sum: AuthorizationInstanceSumAggregateOutputType | null
  _min: AuthorizationInstanceMinAggregateOutputType | null
  _max: AuthorizationInstanceMaxAggregateOutputType | null
}

type GetAuthorizationInstanceGroupByPayload<T extends AuthorizationInstanceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AuthorizationInstanceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AuthorizationInstanceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AuthorizationInstanceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AuthorizationInstanceGroupByOutputType[P]>
      }
    >
  >



export type AuthorizationInstanceWhereInput = {
  AND?: Prisma.AuthorizationInstanceWhereInput | Prisma.AuthorizationInstanceWhereInput[]
  OR?: Prisma.AuthorizationInstanceWhereInput[]
  NOT?: Prisma.AuthorizationInstanceWhereInput | Prisma.AuthorizationInstanceWhereInput[]
  id?: Prisma.IntFilter<"AuthorizationInstance"> | number
  sessionId?: Prisma.StringFilter<"AuthorizationInstance"> | string
  appId?: Prisma.IntFilter<"AuthorizationInstance"> | number
  refreshToken?: Prisma.StringFilter<"AuthorizationInstance"> | string
  refreshTokenExpire?: Prisma.IntFilter<"AuthorizationInstance"> | number
  app?: Prisma.XOR<Prisma.AppScalarRelationFilter, Prisma.AppWhereInput>
  session?: Prisma.XOR<Prisma.SessionScalarRelationFilter, Prisma.SessionWhereInput>
}

export type AuthorizationInstanceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  refreshToken?: Prisma.SortOrder
  refreshTokenExpire?: Prisma.SortOrder
  app?: Prisma.AppOrderByWithRelationInput
  session?: Prisma.SessionOrderByWithRelationInput
}

export type AuthorizationInstanceWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  refreshToken?: string
  AND?: Prisma.AuthorizationInstanceWhereInput | Prisma.AuthorizationInstanceWhereInput[]
  OR?: Prisma.AuthorizationInstanceWhereInput[]
  NOT?: Prisma.AuthorizationInstanceWhereInput | Prisma.AuthorizationInstanceWhereInput[]
  sessionId?: Prisma.StringFilter<"AuthorizationInstance"> | string
  appId?: Prisma.IntFilter<"AuthorizationInstance"> | number
  refreshTokenExpire?: Prisma.IntFilter<"AuthorizationInstance"> | number
  app?: Prisma.XOR<Prisma.AppScalarRelationFilter, Prisma.AppWhereInput>
  session?: Prisma.XOR<Prisma.SessionScalarRelationFilter, Prisma.SessionWhereInput>
}, "id" | "refreshToken">

export type AuthorizationInstanceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  refreshToken?: Prisma.SortOrder
  refreshTokenExpire?: Prisma.SortOrder
  _count?: Prisma.AuthorizationInstanceCountOrderByAggregateInput
  _avg?: Prisma.AuthorizationInstanceAvgOrderByAggregateInput
  _max?: Prisma.AuthorizationInstanceMaxOrderByAggregateInput
  _min?: Prisma.AuthorizationInstanceMinOrderByAggregateInput
  _sum?: Prisma.AuthorizationInstanceSumOrderByAggregateInput
}

export type AuthorizationInstanceScalarWhereWithAggregatesInput = {
  AND?: Prisma.AuthorizationInstanceScalarWhereWithAggregatesInput | Prisma.AuthorizationInstanceScalarWhereWithAggregatesInput[]
  OR?: Prisma.AuthorizationInstanceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AuthorizationInstanceScalarWhereWithAggregatesInput | Prisma.AuthorizationInstanceScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"AuthorizationInstance"> | number
  sessionId?: Prisma.StringWithAggregatesFilter<"AuthorizationInstance"> | string
  appId?: Prisma.IntWithAggregatesFilter<"AuthorizationInstance"> | number
  refreshToken?: Prisma.StringWithAggregatesFilter<"AuthorizationInstance"> | string
  refreshTokenExpire?: Prisma.IntWithAggregatesFilter<"AuthorizationInstance"> | number
}

export type AuthorizationInstanceCreateInput = {
  refreshToken: string
  refreshTokenExpire: number
  app: Prisma.AppCreateNestedOneWithoutAuthorizationInstanceInput
  session: Prisma.SessionCreateNestedOneWithoutInstancesInput
}

export type AuthorizationInstanceUncheckedCreateInput = {
  id?: number
  sessionId: string
  appId: number
  refreshToken: string
  refreshTokenExpire: number
}

export type AuthorizationInstanceUpdateInput = {
  refreshToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshTokenExpire?: Prisma.IntFieldUpdateOperationsInput | number
  app?: Prisma.AppUpdateOneRequiredWithoutAuthorizationInstanceNestedInput
  session?: Prisma.SessionUpdateOneRequiredWithoutInstancesNestedInput
}

export type AuthorizationInstanceUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  appId?: Prisma.IntFieldUpdateOperationsInput | number
  refreshToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshTokenExpire?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AuthorizationInstanceCreateManyInput = {
  id?: number
  sessionId: string
  appId: number
  refreshToken: string
  refreshTokenExpire: number
}

export type AuthorizationInstanceUpdateManyMutationInput = {
  refreshToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshTokenExpire?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AuthorizationInstanceUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  appId?: Prisma.IntFieldUpdateOperationsInput | number
  refreshToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshTokenExpire?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AuthorizationInstanceListRelationFilter = {
  every?: Prisma.AuthorizationInstanceWhereInput
  some?: Prisma.AuthorizationInstanceWhereInput
  none?: Prisma.AuthorizationInstanceWhereInput
}

export type AuthorizationInstanceOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AuthorizationInstanceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  refreshToken?: Prisma.SortOrder
  refreshTokenExpire?: Prisma.SortOrder
}

export type AuthorizationInstanceAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  refreshTokenExpire?: Prisma.SortOrder
}

export type AuthorizationInstanceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  refreshToken?: Prisma.SortOrder
  refreshTokenExpire?: Prisma.SortOrder
}

export type AuthorizationInstanceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  refreshToken?: Prisma.SortOrder
  refreshTokenExpire?: Prisma.SortOrder
}

export type AuthorizationInstanceSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  refreshTokenExpire?: Prisma.SortOrder
}

export type AuthorizationInstanceCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.AuthorizationInstanceCreateWithoutSessionInput, Prisma.AuthorizationInstanceUncheckedCreateWithoutSessionInput> | Prisma.AuthorizationInstanceCreateWithoutSessionInput[] | Prisma.AuthorizationInstanceUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.AuthorizationInstanceCreateOrConnectWithoutSessionInput | Prisma.AuthorizationInstanceCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.AuthorizationInstanceCreateManySessionInputEnvelope
  connect?: Prisma.AuthorizationInstanceWhereUniqueInput | Prisma.AuthorizationInstanceWhereUniqueInput[]
}

export type AuthorizationInstanceUncheckedCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.AuthorizationInstanceCreateWithoutSessionInput, Prisma.AuthorizationInstanceUncheckedCreateWithoutSessionInput> | Prisma.AuthorizationInstanceCreateWithoutSessionInput[] | Prisma.AuthorizationInstanceUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.AuthorizationInstanceCreateOrConnectWithoutSessionInput | Prisma.AuthorizationInstanceCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.AuthorizationInstanceCreateManySessionInputEnvelope
  connect?: Prisma.AuthorizationInstanceWhereUniqueInput | Prisma.AuthorizationInstanceWhereUniqueInput[]
}

export type AuthorizationInstanceUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.AuthorizationInstanceCreateWithoutSessionInput, Prisma.AuthorizationInstanceUncheckedCreateWithoutSessionInput> | Prisma.AuthorizationInstanceCreateWithoutSessionInput[] | Prisma.AuthorizationInstanceUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.AuthorizationInstanceCreateOrConnectWithoutSessionInput | Prisma.AuthorizationInstanceCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.AuthorizationInstanceUpsertWithWhereUniqueWithoutSessionInput | Prisma.AuthorizationInstanceUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.AuthorizationInstanceCreateManySessionInputEnvelope
  set?: Prisma.AuthorizationInstanceWhereUniqueInput | Prisma.AuthorizationInstanceWhereUniqueInput[]
  disconnect?: Prisma.AuthorizationInstanceWhereUniqueInput | Prisma.AuthorizationInstanceWhereUniqueInput[]
  delete?: Prisma.AuthorizationInstanceWhereUniqueInput | Prisma.AuthorizationInstanceWhereUniqueInput[]
  connect?: Prisma.AuthorizationInstanceWhereUniqueInput | Prisma.AuthorizationInstanceWhereUniqueInput[]
  update?: Prisma.AuthorizationInstanceUpdateWithWhereUniqueWithoutSessionInput | Prisma.AuthorizationInstanceUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.AuthorizationInstanceUpdateManyWithWhereWithoutSessionInput | Prisma.AuthorizationInstanceUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.AuthorizationInstanceScalarWhereInput | Prisma.AuthorizationInstanceScalarWhereInput[]
}

export type AuthorizationInstanceUncheckedUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.AuthorizationInstanceCreateWithoutSessionInput, Prisma.AuthorizationInstanceUncheckedCreateWithoutSessionInput> | Prisma.AuthorizationInstanceCreateWithoutSessionInput[] | Prisma.AuthorizationInstanceUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.AuthorizationInstanceCreateOrConnectWithoutSessionInput | Prisma.AuthorizationInstanceCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.AuthorizationInstanceUpsertWithWhereUniqueWithoutSessionInput | Prisma.AuthorizationInstanceUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.AuthorizationInstanceCreateManySessionInputEnvelope
  set?: Prisma.AuthorizationInstanceWhereUniqueInput | Prisma.AuthorizationInstanceWhereUniqueInput[]
  disconnect?: Prisma.AuthorizationInstanceWhereUniqueInput | Prisma.AuthorizationInstanceWhereUniqueInput[]
  delete?: Prisma.AuthorizationInstanceWhereUniqueInput | Prisma.AuthorizationInstanceWhereUniqueInput[]
  connect?: Prisma.AuthorizationInstanceWhereUniqueInput | Prisma.AuthorizationInstanceWhereUniqueInput[]
  update?: Prisma.AuthorizationInstanceUpdateWithWhereUniqueWithoutSessionInput | Prisma.AuthorizationInstanceUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.AuthorizationInstanceUpdateManyWithWhereWithoutSessionInput | Prisma.AuthorizationInstanceUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.AuthorizationInstanceScalarWhereInput | Prisma.AuthorizationInstanceScalarWhereInput[]
}

export type AuthorizationInstanceCreateNestedManyWithoutAppInput = {
  create?: Prisma.XOR<Prisma.AuthorizationInstanceCreateWithoutAppInput, Prisma.AuthorizationInstanceUncheckedCreateWithoutAppInput> | Prisma.AuthorizationInstanceCreateWithoutAppInput[] | Prisma.AuthorizationInstanceUncheckedCreateWithoutAppInput[]
  connectOrCreate?: Prisma.AuthorizationInstanceCreateOrConnectWithoutAppInput | Prisma.AuthorizationInstanceCreateOrConnectWithoutAppInput[]
  createMany?: Prisma.AuthorizationInstanceCreateManyAppInputEnvelope
  connect?: Prisma.AuthorizationInstanceWhereUniqueInput | Prisma.AuthorizationInstanceWhereUniqueInput[]
}

export type AuthorizationInstanceUncheckedCreateNestedManyWithoutAppInput = {
  create?: Prisma.XOR<Prisma.AuthorizationInstanceCreateWithoutAppInput, Prisma.AuthorizationInstanceUncheckedCreateWithoutAppInput> | Prisma.AuthorizationInstanceCreateWithoutAppInput[] | Prisma.AuthorizationInstanceUncheckedCreateWithoutAppInput[]
  connectOrCreate?: Prisma.AuthorizationInstanceCreateOrConnectWithoutAppInput | Prisma.AuthorizationInstanceCreateOrConnectWithoutAppInput[]
  createMany?: Prisma.AuthorizationInstanceCreateManyAppInputEnvelope
  connect?: Prisma.AuthorizationInstanceWhereUniqueInput | Prisma.AuthorizationInstanceWhereUniqueInput[]
}

export type AuthorizationInstanceUpdateManyWithoutAppNestedInput = {
  create?: Prisma.XOR<Prisma.AuthorizationInstanceCreateWithoutAppInput, Prisma.AuthorizationInstanceUncheckedCreateWithoutAppInput> | Prisma.AuthorizationInstanceCreateWithoutAppInput[] | Prisma.AuthorizationInstanceUncheckedCreateWithoutAppInput[]
  connectOrCreate?: Prisma.AuthorizationInstanceCreateOrConnectWithoutAppInput | Prisma.AuthorizationInstanceCreateOrConnectWithoutAppInput[]
  upsert?: Prisma.AuthorizationInstanceUpsertWithWhereUniqueWithoutAppInput | Prisma.AuthorizationInstanceUpsertWithWhereUniqueWithoutAppInput[]
  createMany?: Prisma.AuthorizationInstanceCreateManyAppInputEnvelope
  set?: Prisma.AuthorizationInstanceWhereUniqueInput | Prisma.AuthorizationInstanceWhereUniqueInput[]
  disconnect?: Prisma.AuthorizationInstanceWhereUniqueInput | Prisma.AuthorizationInstanceWhereUniqueInput[]
  delete?: Prisma.AuthorizationInstanceWhereUniqueInput | Prisma.AuthorizationInstanceWhereUniqueInput[]
  connect?: Prisma.AuthorizationInstanceWhereUniqueInput | Prisma.AuthorizationInstanceWhereUniqueInput[]
  update?: Prisma.AuthorizationInstanceUpdateWithWhereUniqueWithoutAppInput | Prisma.AuthorizationInstanceUpdateWithWhereUniqueWithoutAppInput[]
  updateMany?: Prisma.AuthorizationInstanceUpdateManyWithWhereWithoutAppInput | Prisma.AuthorizationInstanceUpdateManyWithWhereWithoutAppInput[]
  deleteMany?: Prisma.AuthorizationInstanceScalarWhereInput | Prisma.AuthorizationInstanceScalarWhereInput[]
}

export type AuthorizationInstanceUncheckedUpdateManyWithoutAppNestedInput = {
  create?: Prisma.XOR<Prisma.AuthorizationInstanceCreateWithoutAppInput, Prisma.AuthorizationInstanceUncheckedCreateWithoutAppInput> | Prisma.AuthorizationInstanceCreateWithoutAppInput[] | Prisma.AuthorizationInstanceUncheckedCreateWithoutAppInput[]
  connectOrCreate?: Prisma.AuthorizationInstanceCreateOrConnectWithoutAppInput | Prisma.AuthorizationInstanceCreateOrConnectWithoutAppInput[]
  upsert?: Prisma.AuthorizationInstanceUpsertWithWhereUniqueWithoutAppInput | Prisma.AuthorizationInstanceUpsertWithWhereUniqueWithoutAppInput[]
  createMany?: Prisma.AuthorizationInstanceCreateManyAppInputEnvelope
  set?: Prisma.AuthorizationInstanceWhereUniqueInput | Prisma.AuthorizationInstanceWhereUniqueInput[]
  disconnect?: Prisma.AuthorizationInstanceWhereUniqueInput | Prisma.AuthorizationInstanceWhereUniqueInput[]
  delete?: Prisma.AuthorizationInstanceWhereUniqueInput | Prisma.AuthorizationInstanceWhereUniqueInput[]
  connect?: Prisma.AuthorizationInstanceWhereUniqueInput | Prisma.AuthorizationInstanceWhereUniqueInput[]
  update?: Prisma.AuthorizationInstanceUpdateWithWhereUniqueWithoutAppInput | Prisma.AuthorizationInstanceUpdateWithWhereUniqueWithoutAppInput[]
  updateMany?: Prisma.AuthorizationInstanceUpdateManyWithWhereWithoutAppInput | Prisma.AuthorizationInstanceUpdateManyWithWhereWithoutAppInput[]
  deleteMany?: Prisma.AuthorizationInstanceScalarWhereInput | Prisma.AuthorizationInstanceScalarWhereInput[]
}

export type AuthorizationInstanceCreateWithoutSessionInput = {
  refreshToken: string
  refreshTokenExpire: number
  app: Prisma.AppCreateNestedOneWithoutAuthorizationInstanceInput
}

export type AuthorizationInstanceUncheckedCreateWithoutSessionInput = {
  id?: number
  appId: number
  refreshToken: string
  refreshTokenExpire: number
}

export type AuthorizationInstanceCreateOrConnectWithoutSessionInput = {
  where: Prisma.AuthorizationInstanceWhereUniqueInput
  create: Prisma.XOR<Prisma.AuthorizationInstanceCreateWithoutSessionInput, Prisma.AuthorizationInstanceUncheckedCreateWithoutSessionInput>
}

export type AuthorizationInstanceCreateManySessionInputEnvelope = {
  data: Prisma.AuthorizationInstanceCreateManySessionInput | Prisma.AuthorizationInstanceCreateManySessionInput[]
  skipDuplicates?: boolean
}

export type AuthorizationInstanceUpsertWithWhereUniqueWithoutSessionInput = {
  where: Prisma.AuthorizationInstanceWhereUniqueInput
  update: Prisma.XOR<Prisma.AuthorizationInstanceUpdateWithoutSessionInput, Prisma.AuthorizationInstanceUncheckedUpdateWithoutSessionInput>
  create: Prisma.XOR<Prisma.AuthorizationInstanceCreateWithoutSessionInput, Prisma.AuthorizationInstanceUncheckedCreateWithoutSessionInput>
}

export type AuthorizationInstanceUpdateWithWhereUniqueWithoutSessionInput = {
  where: Prisma.AuthorizationInstanceWhereUniqueInput
  data: Prisma.XOR<Prisma.AuthorizationInstanceUpdateWithoutSessionInput, Prisma.AuthorizationInstanceUncheckedUpdateWithoutSessionInput>
}

export type AuthorizationInstanceUpdateManyWithWhereWithoutSessionInput = {
  where: Prisma.AuthorizationInstanceScalarWhereInput
  data: Prisma.XOR<Prisma.AuthorizationInstanceUpdateManyMutationInput, Prisma.AuthorizationInstanceUncheckedUpdateManyWithoutSessionInput>
}

export type AuthorizationInstanceScalarWhereInput = {
  AND?: Prisma.AuthorizationInstanceScalarWhereInput | Prisma.AuthorizationInstanceScalarWhereInput[]
  OR?: Prisma.AuthorizationInstanceScalarWhereInput[]
  NOT?: Prisma.AuthorizationInstanceScalarWhereInput | Prisma.AuthorizationInstanceScalarWhereInput[]
  id?: Prisma.IntFilter<"AuthorizationInstance"> | number
  sessionId?: Prisma.StringFilter<"AuthorizationInstance"> | string
  appId?: Prisma.IntFilter<"AuthorizationInstance"> | number
  refreshToken?: Prisma.StringFilter<"AuthorizationInstance"> | string
  refreshTokenExpire?: Prisma.IntFilter<"AuthorizationInstance"> | number
}

export type AuthorizationInstanceCreateWithoutAppInput = {
  refreshToken: string
  refreshTokenExpire: number
  session: Prisma.SessionCreateNestedOneWithoutInstancesInput
}

export type AuthorizationInstanceUncheckedCreateWithoutAppInput = {
  id?: number
  sessionId: string
  refreshToken: string
  refreshTokenExpire: number
}

export type AuthorizationInstanceCreateOrConnectWithoutAppInput = {
  where: Prisma.AuthorizationInstanceWhereUniqueInput
  create: Prisma.XOR<Prisma.AuthorizationInstanceCreateWithoutAppInput, Prisma.AuthorizationInstanceUncheckedCreateWithoutAppInput>
}

export type AuthorizationInstanceCreateManyAppInputEnvelope = {
  data: Prisma.AuthorizationInstanceCreateManyAppInput | Prisma.AuthorizationInstanceCreateManyAppInput[]
  skipDuplicates?: boolean
}

export type AuthorizationInstanceUpsertWithWhereUniqueWithoutAppInput = {
  where: Prisma.AuthorizationInstanceWhereUniqueInput
  update: Prisma.XOR<Prisma.AuthorizationInstanceUpdateWithoutAppInput, Prisma.AuthorizationInstanceUncheckedUpdateWithoutAppInput>
  create: Prisma.XOR<Prisma.AuthorizationInstanceCreateWithoutAppInput, Prisma.AuthorizationInstanceUncheckedCreateWithoutAppInput>
}

export type AuthorizationInstanceUpdateWithWhereUniqueWithoutAppInput = {
  where: Prisma.AuthorizationInstanceWhereUniqueInput
  data: Prisma.XOR<Prisma.AuthorizationInstanceUpdateWithoutAppInput, Prisma.AuthorizationInstanceUncheckedUpdateWithoutAppInput>
}

export type AuthorizationInstanceUpdateManyWithWhereWithoutAppInput = {
  where: Prisma.AuthorizationInstanceScalarWhereInput
  data: Prisma.XOR<Prisma.AuthorizationInstanceUpdateManyMutationInput, Prisma.AuthorizationInstanceUncheckedUpdateManyWithoutAppInput>
}

export type AuthorizationInstanceCreateManySessionInput = {
  id?: number
  appId: number
  refreshToken: string
  refreshTokenExpire: number
}

export type AuthorizationInstanceUpdateWithoutSessionInput = {
  refreshToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshTokenExpire?: Prisma.IntFieldUpdateOperationsInput | number
  app?: Prisma.AppUpdateOneRequiredWithoutAuthorizationInstanceNestedInput
}

export type AuthorizationInstanceUncheckedUpdateWithoutSessionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  appId?: Prisma.IntFieldUpdateOperationsInput | number
  refreshToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshTokenExpire?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AuthorizationInstanceUncheckedUpdateManyWithoutSessionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  appId?: Prisma.IntFieldUpdateOperationsInput | number
  refreshToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshTokenExpire?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AuthorizationInstanceCreateManyAppInput = {
  id?: number
  sessionId: string
  refreshToken: string
  refreshTokenExpire: number
}

export type AuthorizationInstanceUpdateWithoutAppInput = {
  refreshToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshTokenExpire?: Prisma.IntFieldUpdateOperationsInput | number
  session?: Prisma.SessionUpdateOneRequiredWithoutInstancesNestedInput
}

export type AuthorizationInstanceUncheckedUpdateWithoutAppInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  refreshToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshTokenExpire?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AuthorizationInstanceUncheckedUpdateManyWithoutAppInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  refreshToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshTokenExpire?: Prisma.IntFieldUpdateOperationsInput | number
}



export type AuthorizationInstanceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  appId?: boolean
  refreshToken?: boolean
  refreshTokenExpire?: boolean
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["authorizationInstance"]>

export type AuthorizationInstanceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  appId?: boolean
  refreshToken?: boolean
  refreshTokenExpire?: boolean
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["authorizationInstance"]>

export type AuthorizationInstanceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  appId?: boolean
  refreshToken?: boolean
  refreshTokenExpire?: boolean
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["authorizationInstance"]>

export type AuthorizationInstanceSelectScalar = {
  id?: boolean
  sessionId?: boolean
  appId?: boolean
  refreshToken?: boolean
  refreshTokenExpire?: boolean
}

export type AuthorizationInstanceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "sessionId" | "appId" | "refreshToken" | "refreshTokenExpire", ExtArgs["result"]["authorizationInstance"]>
export type AuthorizationInstanceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
}
export type AuthorizationInstanceIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
}
export type AuthorizationInstanceIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
}

export type $AuthorizationInstancePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AuthorizationInstance"
  objects: {
    app: Prisma.$AppPayload<ExtArgs>
    session: Prisma.$SessionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    sessionId: string
    appId: number
    refreshToken: string
    refreshTokenExpire: number
  }, ExtArgs["result"]["authorizationInstance"]>
  composites: {}
}

export type AuthorizationInstanceGetPayload<S extends boolean | null | undefined | AuthorizationInstanceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AuthorizationInstancePayload, S>

export type AuthorizationInstanceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AuthorizationInstanceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AuthorizationInstanceCountAggregateInputType | true
  }

export interface AuthorizationInstanceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AuthorizationInstance'], meta: { name: 'AuthorizationInstance' } }
  /**
   * Find zero or one AuthorizationInstance that matches the filter.
   * @param {AuthorizationInstanceFindUniqueArgs} args - Arguments to find a AuthorizationInstance
   * @example
   * // Get one AuthorizationInstance
   * const authorizationInstance = await prisma.authorizationInstance.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AuthorizationInstanceFindUniqueArgs>(args: Prisma.SelectSubset<T, AuthorizationInstanceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AuthorizationInstanceClient<runtime.Types.Result.GetResult<Prisma.$AuthorizationInstancePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AuthorizationInstance that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AuthorizationInstanceFindUniqueOrThrowArgs} args - Arguments to find a AuthorizationInstance
   * @example
   * // Get one AuthorizationInstance
   * const authorizationInstance = await prisma.authorizationInstance.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AuthorizationInstanceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AuthorizationInstanceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AuthorizationInstanceClient<runtime.Types.Result.GetResult<Prisma.$AuthorizationInstancePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AuthorizationInstance that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthorizationInstanceFindFirstArgs} args - Arguments to find a AuthorizationInstance
   * @example
   * // Get one AuthorizationInstance
   * const authorizationInstance = await prisma.authorizationInstance.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AuthorizationInstanceFindFirstArgs>(args?: Prisma.SelectSubset<T, AuthorizationInstanceFindFirstArgs<ExtArgs>>): Prisma.Prisma__AuthorizationInstanceClient<runtime.Types.Result.GetResult<Prisma.$AuthorizationInstancePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AuthorizationInstance that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthorizationInstanceFindFirstOrThrowArgs} args - Arguments to find a AuthorizationInstance
   * @example
   * // Get one AuthorizationInstance
   * const authorizationInstance = await prisma.authorizationInstance.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AuthorizationInstanceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AuthorizationInstanceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AuthorizationInstanceClient<runtime.Types.Result.GetResult<Prisma.$AuthorizationInstancePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AuthorizationInstances that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthorizationInstanceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AuthorizationInstances
   * const authorizationInstances = await prisma.authorizationInstance.findMany()
   * 
   * // Get first 10 AuthorizationInstances
   * const authorizationInstances = await prisma.authorizationInstance.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const authorizationInstanceWithIdOnly = await prisma.authorizationInstance.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AuthorizationInstanceFindManyArgs>(args?: Prisma.SelectSubset<T, AuthorizationInstanceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthorizationInstancePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AuthorizationInstance.
   * @param {AuthorizationInstanceCreateArgs} args - Arguments to create a AuthorizationInstance.
   * @example
   * // Create one AuthorizationInstance
   * const AuthorizationInstance = await prisma.authorizationInstance.create({
   *   data: {
   *     // ... data to create a AuthorizationInstance
   *   }
   * })
   * 
   */
  create<T extends AuthorizationInstanceCreateArgs>(args: Prisma.SelectSubset<T, AuthorizationInstanceCreateArgs<ExtArgs>>): Prisma.Prisma__AuthorizationInstanceClient<runtime.Types.Result.GetResult<Prisma.$AuthorizationInstancePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AuthorizationInstances.
   * @param {AuthorizationInstanceCreateManyArgs} args - Arguments to create many AuthorizationInstances.
   * @example
   * // Create many AuthorizationInstances
   * const authorizationInstance = await prisma.authorizationInstance.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AuthorizationInstanceCreateManyArgs>(args?: Prisma.SelectSubset<T, AuthorizationInstanceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AuthorizationInstances and returns the data saved in the database.
   * @param {AuthorizationInstanceCreateManyAndReturnArgs} args - Arguments to create many AuthorizationInstances.
   * @example
   * // Create many AuthorizationInstances
   * const authorizationInstance = await prisma.authorizationInstance.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AuthorizationInstances and only return the `id`
   * const authorizationInstanceWithIdOnly = await prisma.authorizationInstance.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AuthorizationInstanceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AuthorizationInstanceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthorizationInstancePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AuthorizationInstance.
   * @param {AuthorizationInstanceDeleteArgs} args - Arguments to delete one AuthorizationInstance.
   * @example
   * // Delete one AuthorizationInstance
   * const AuthorizationInstance = await prisma.authorizationInstance.delete({
   *   where: {
   *     // ... filter to delete one AuthorizationInstance
   *   }
   * })
   * 
   */
  delete<T extends AuthorizationInstanceDeleteArgs>(args: Prisma.SelectSubset<T, AuthorizationInstanceDeleteArgs<ExtArgs>>): Prisma.Prisma__AuthorizationInstanceClient<runtime.Types.Result.GetResult<Prisma.$AuthorizationInstancePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AuthorizationInstance.
   * @param {AuthorizationInstanceUpdateArgs} args - Arguments to update one AuthorizationInstance.
   * @example
   * // Update one AuthorizationInstance
   * const authorizationInstance = await prisma.authorizationInstance.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AuthorizationInstanceUpdateArgs>(args: Prisma.SelectSubset<T, AuthorizationInstanceUpdateArgs<ExtArgs>>): Prisma.Prisma__AuthorizationInstanceClient<runtime.Types.Result.GetResult<Prisma.$AuthorizationInstancePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AuthorizationInstances.
   * @param {AuthorizationInstanceDeleteManyArgs} args - Arguments to filter AuthorizationInstances to delete.
   * @example
   * // Delete a few AuthorizationInstances
   * const { count } = await prisma.authorizationInstance.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AuthorizationInstanceDeleteManyArgs>(args?: Prisma.SelectSubset<T, AuthorizationInstanceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AuthorizationInstances.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthorizationInstanceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AuthorizationInstances
   * const authorizationInstance = await prisma.authorizationInstance.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AuthorizationInstanceUpdateManyArgs>(args: Prisma.SelectSubset<T, AuthorizationInstanceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AuthorizationInstances and returns the data updated in the database.
   * @param {AuthorizationInstanceUpdateManyAndReturnArgs} args - Arguments to update many AuthorizationInstances.
   * @example
   * // Update many AuthorizationInstances
   * const authorizationInstance = await prisma.authorizationInstance.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AuthorizationInstances and only return the `id`
   * const authorizationInstanceWithIdOnly = await prisma.authorizationInstance.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AuthorizationInstanceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AuthorizationInstanceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthorizationInstancePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AuthorizationInstance.
   * @param {AuthorizationInstanceUpsertArgs} args - Arguments to update or create a AuthorizationInstance.
   * @example
   * // Update or create a AuthorizationInstance
   * const authorizationInstance = await prisma.authorizationInstance.upsert({
   *   create: {
   *     // ... data to create a AuthorizationInstance
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AuthorizationInstance we want to update
   *   }
   * })
   */
  upsert<T extends AuthorizationInstanceUpsertArgs>(args: Prisma.SelectSubset<T, AuthorizationInstanceUpsertArgs<ExtArgs>>): Prisma.Prisma__AuthorizationInstanceClient<runtime.Types.Result.GetResult<Prisma.$AuthorizationInstancePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AuthorizationInstances.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthorizationInstanceCountArgs} args - Arguments to filter AuthorizationInstances to count.
   * @example
   * // Count the number of AuthorizationInstances
   * const count = await prisma.authorizationInstance.count({
   *   where: {
   *     // ... the filter for the AuthorizationInstances we want to count
   *   }
   * })
  **/
  count<T extends AuthorizationInstanceCountArgs>(
    args?: Prisma.Subset<T, AuthorizationInstanceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AuthorizationInstanceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AuthorizationInstance.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthorizationInstanceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AuthorizationInstanceAggregateArgs>(args: Prisma.Subset<T, AuthorizationInstanceAggregateArgs>): Prisma.PrismaPromise<GetAuthorizationInstanceAggregateType<T>>

  /**
   * Group by AuthorizationInstance.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthorizationInstanceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AuthorizationInstanceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AuthorizationInstanceGroupByArgs['orderBy'] }
      : { orderBy?: AuthorizationInstanceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AuthorizationInstanceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAuthorizationInstanceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AuthorizationInstance model
 */
readonly fields: AuthorizationInstanceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AuthorizationInstance.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AuthorizationInstanceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  app<T extends Prisma.AppDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AppDefaultArgs<ExtArgs>>): Prisma.Prisma__AppClient<runtime.Types.Result.GetResult<Prisma.$AppPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  session<T extends Prisma.SessionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SessionDefaultArgs<ExtArgs>>): Prisma.Prisma__SessionClient<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AuthorizationInstance model
 */
export interface AuthorizationInstanceFieldRefs {
  readonly id: Prisma.FieldRef<"AuthorizationInstance", 'Int'>
  readonly sessionId: Prisma.FieldRef<"AuthorizationInstance", 'String'>
  readonly appId: Prisma.FieldRef<"AuthorizationInstance", 'Int'>
  readonly refreshToken: Prisma.FieldRef<"AuthorizationInstance", 'String'>
  readonly refreshTokenExpire: Prisma.FieldRef<"AuthorizationInstance", 'Int'>
}
    

// Custom InputTypes
/**
 * AuthorizationInstance findUnique
 */
export type AuthorizationInstanceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthorizationInstance
   */
  select?: Prisma.AuthorizationInstanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthorizationInstance
   */
  omit?: Prisma.AuthorizationInstanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthorizationInstanceInclude<ExtArgs> | null
  /**
   * Filter, which AuthorizationInstance to fetch.
   */
  where: Prisma.AuthorizationInstanceWhereUniqueInput
}

/**
 * AuthorizationInstance findUniqueOrThrow
 */
export type AuthorizationInstanceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthorizationInstance
   */
  select?: Prisma.AuthorizationInstanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthorizationInstance
   */
  omit?: Prisma.AuthorizationInstanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthorizationInstanceInclude<ExtArgs> | null
  /**
   * Filter, which AuthorizationInstance to fetch.
   */
  where: Prisma.AuthorizationInstanceWhereUniqueInput
}

/**
 * AuthorizationInstance findFirst
 */
export type AuthorizationInstanceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthorizationInstance
   */
  select?: Prisma.AuthorizationInstanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthorizationInstance
   */
  omit?: Prisma.AuthorizationInstanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthorizationInstanceInclude<ExtArgs> | null
  /**
   * Filter, which AuthorizationInstance to fetch.
   */
  where?: Prisma.AuthorizationInstanceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthorizationInstances to fetch.
   */
  orderBy?: Prisma.AuthorizationInstanceOrderByWithRelationInput | Prisma.AuthorizationInstanceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AuthorizationInstances.
   */
  cursor?: Prisma.AuthorizationInstanceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthorizationInstances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthorizationInstances.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AuthorizationInstances.
   */
  distinct?: Prisma.AuthorizationInstanceScalarFieldEnum | Prisma.AuthorizationInstanceScalarFieldEnum[]
}

/**
 * AuthorizationInstance findFirstOrThrow
 */
export type AuthorizationInstanceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthorizationInstance
   */
  select?: Prisma.AuthorizationInstanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthorizationInstance
   */
  omit?: Prisma.AuthorizationInstanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthorizationInstanceInclude<ExtArgs> | null
  /**
   * Filter, which AuthorizationInstance to fetch.
   */
  where?: Prisma.AuthorizationInstanceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthorizationInstances to fetch.
   */
  orderBy?: Prisma.AuthorizationInstanceOrderByWithRelationInput | Prisma.AuthorizationInstanceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AuthorizationInstances.
   */
  cursor?: Prisma.AuthorizationInstanceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthorizationInstances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthorizationInstances.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AuthorizationInstances.
   */
  distinct?: Prisma.AuthorizationInstanceScalarFieldEnum | Prisma.AuthorizationInstanceScalarFieldEnum[]
}

/**
 * AuthorizationInstance findMany
 */
export type AuthorizationInstanceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthorizationInstance
   */
  select?: Prisma.AuthorizationInstanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthorizationInstance
   */
  omit?: Prisma.AuthorizationInstanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthorizationInstanceInclude<ExtArgs> | null
  /**
   * Filter, which AuthorizationInstances to fetch.
   */
  where?: Prisma.AuthorizationInstanceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthorizationInstances to fetch.
   */
  orderBy?: Prisma.AuthorizationInstanceOrderByWithRelationInput | Prisma.AuthorizationInstanceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AuthorizationInstances.
   */
  cursor?: Prisma.AuthorizationInstanceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthorizationInstances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthorizationInstances.
   */
  skip?: number
  distinct?: Prisma.AuthorizationInstanceScalarFieldEnum | Prisma.AuthorizationInstanceScalarFieldEnum[]
}

/**
 * AuthorizationInstance create
 */
export type AuthorizationInstanceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthorizationInstance
   */
  select?: Prisma.AuthorizationInstanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthorizationInstance
   */
  omit?: Prisma.AuthorizationInstanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthorizationInstanceInclude<ExtArgs> | null
  /**
   * The data needed to create a AuthorizationInstance.
   */
  data: Prisma.XOR<Prisma.AuthorizationInstanceCreateInput, Prisma.AuthorizationInstanceUncheckedCreateInput>
}

/**
 * AuthorizationInstance createMany
 */
export type AuthorizationInstanceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AuthorizationInstances.
   */
  data: Prisma.AuthorizationInstanceCreateManyInput | Prisma.AuthorizationInstanceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AuthorizationInstance createManyAndReturn
 */
export type AuthorizationInstanceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthorizationInstance
   */
  select?: Prisma.AuthorizationInstanceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AuthorizationInstance
   */
  omit?: Prisma.AuthorizationInstanceOmit<ExtArgs> | null
  /**
   * The data used to create many AuthorizationInstances.
   */
  data: Prisma.AuthorizationInstanceCreateManyInput | Prisma.AuthorizationInstanceCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthorizationInstanceIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AuthorizationInstance update
 */
export type AuthorizationInstanceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthorizationInstance
   */
  select?: Prisma.AuthorizationInstanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthorizationInstance
   */
  omit?: Prisma.AuthorizationInstanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthorizationInstanceInclude<ExtArgs> | null
  /**
   * The data needed to update a AuthorizationInstance.
   */
  data: Prisma.XOR<Prisma.AuthorizationInstanceUpdateInput, Prisma.AuthorizationInstanceUncheckedUpdateInput>
  /**
   * Choose, which AuthorizationInstance to update.
   */
  where: Prisma.AuthorizationInstanceWhereUniqueInput
}

/**
 * AuthorizationInstance updateMany
 */
export type AuthorizationInstanceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AuthorizationInstances.
   */
  data: Prisma.XOR<Prisma.AuthorizationInstanceUpdateManyMutationInput, Prisma.AuthorizationInstanceUncheckedUpdateManyInput>
  /**
   * Filter which AuthorizationInstances to update
   */
  where?: Prisma.AuthorizationInstanceWhereInput
  /**
   * Limit how many AuthorizationInstances to update.
   */
  limit?: number
}

/**
 * AuthorizationInstance updateManyAndReturn
 */
export type AuthorizationInstanceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthorizationInstance
   */
  select?: Prisma.AuthorizationInstanceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AuthorizationInstance
   */
  omit?: Prisma.AuthorizationInstanceOmit<ExtArgs> | null
  /**
   * The data used to update AuthorizationInstances.
   */
  data: Prisma.XOR<Prisma.AuthorizationInstanceUpdateManyMutationInput, Prisma.AuthorizationInstanceUncheckedUpdateManyInput>
  /**
   * Filter which AuthorizationInstances to update
   */
  where?: Prisma.AuthorizationInstanceWhereInput
  /**
   * Limit how many AuthorizationInstances to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthorizationInstanceIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AuthorizationInstance upsert
 */
export type AuthorizationInstanceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthorizationInstance
   */
  select?: Prisma.AuthorizationInstanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthorizationInstance
   */
  omit?: Prisma.AuthorizationInstanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthorizationInstanceInclude<ExtArgs> | null
  /**
   * The filter to search for the AuthorizationInstance to update in case it exists.
   */
  where: Prisma.AuthorizationInstanceWhereUniqueInput
  /**
   * In case the AuthorizationInstance found by the `where` argument doesn't exist, create a new AuthorizationInstance with this data.
   */
  create: Prisma.XOR<Prisma.AuthorizationInstanceCreateInput, Prisma.AuthorizationInstanceUncheckedCreateInput>
  /**
   * In case the AuthorizationInstance was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AuthorizationInstanceUpdateInput, Prisma.AuthorizationInstanceUncheckedUpdateInput>
}

/**
 * AuthorizationInstance delete
 */
export type AuthorizationInstanceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthorizationInstance
   */
  select?: Prisma.AuthorizationInstanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthorizationInstance
   */
  omit?: Prisma.AuthorizationInstanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthorizationInstanceInclude<ExtArgs> | null
  /**
   * Filter which AuthorizationInstance to delete.
   */
  where: Prisma.AuthorizationInstanceWhereUniqueInput
}

/**
 * AuthorizationInstance deleteMany
 */
export type AuthorizationInstanceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AuthorizationInstances to delete
   */
  where?: Prisma.AuthorizationInstanceWhereInput
  /**
   * Limit how many AuthorizationInstances to delete.
   */
  limit?: number
}

/**
 * AuthorizationInstance without action
 */
export type AuthorizationInstanceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthorizationInstance
   */
  select?: Prisma.AuthorizationInstanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthorizationInstance
   */
  omit?: Prisma.AuthorizationInstanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthorizationInstanceInclude<ExtArgs> | null
}
