
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Mirror` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Mirror
 * 
 */
export type MirrorModel = runtime.Types.Result.DefaultSelection<Prisma.$MirrorPayload>

export type AggregateMirror = {
  _count: MirrorCountAggregateOutputType | null
  _avg: MirrorAvgAggregateOutputType | null
  _sum: MirrorSumAggregateOutputType | null
  _min: MirrorMinAggregateOutputType | null
  _max: MirrorMaxAggregateOutputType | null
}

export type MirrorAvgAggregateOutputType = {
  id: number | null
  autoRunInterval: number | null
}

export type MirrorSumAggregateOutputType = {
  id: number | null
  autoRunInterval: number | null
}

export type MirrorMinAggregateOutputType = {
  id: number | null
  name: string | null
  code: string | null
  autoRun: boolean | null
  autoRunInterval: number | null
  lastRun: Date | null
  lastResult: string | null
}

export type MirrorMaxAggregateOutputType = {
  id: number | null
  name: string | null
  code: string | null
  autoRun: boolean | null
  autoRunInterval: number | null
  lastRun: Date | null
  lastResult: string | null
}

export type MirrorCountAggregateOutputType = {
  id: number
  name: number
  code: number
  autoRun: number
  autoRunInterval: number
  lastRun: number
  lastResult: number
  _all: number
}


export type MirrorAvgAggregateInputType = {
  id?: true
  autoRunInterval?: true
}

export type MirrorSumAggregateInputType = {
  id?: true
  autoRunInterval?: true
}

export type MirrorMinAggregateInputType = {
  id?: true
  name?: true
  code?: true
  autoRun?: true
  autoRunInterval?: true
  lastRun?: true
  lastResult?: true
}

export type MirrorMaxAggregateInputType = {
  id?: true
  name?: true
  code?: true
  autoRun?: true
  autoRunInterval?: true
  lastRun?: true
  lastResult?: true
}

export type MirrorCountAggregateInputType = {
  id?: true
  name?: true
  code?: true
  autoRun?: true
  autoRunInterval?: true
  lastRun?: true
  lastResult?: true
  _all?: true
}

export type MirrorAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Mirror to aggregate.
   */
  where?: Prisma.MirrorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Mirrors to fetch.
   */
  orderBy?: Prisma.MirrorOrderByWithRelationInput | Prisma.MirrorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MirrorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Mirrors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Mirrors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Mirrors
  **/
  _count?: true | MirrorCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MirrorAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MirrorSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MirrorMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MirrorMaxAggregateInputType
}

export type GetMirrorAggregateType<T extends MirrorAggregateArgs> = {
      [P in keyof T & keyof AggregateMirror]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMirror[P]>
    : Prisma.GetScalarType<T[P], AggregateMirror[P]>
}




export type MirrorGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MirrorWhereInput
  orderBy?: Prisma.MirrorOrderByWithAggregationInput | Prisma.MirrorOrderByWithAggregationInput[]
  by: Prisma.MirrorScalarFieldEnum[] | Prisma.MirrorScalarFieldEnum
  having?: Prisma.MirrorScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MirrorCountAggregateInputType | true
  _avg?: MirrorAvgAggregateInputType
  _sum?: MirrorSumAggregateInputType
  _min?: MirrorMinAggregateInputType
  _max?: MirrorMaxAggregateInputType
}

export type MirrorGroupByOutputType = {
  id: number
  name: string
  code: string
  autoRun: boolean
  autoRunInterval: number | null
  lastRun: Date | null
  lastResult: string | null
  _count: MirrorCountAggregateOutputType | null
  _avg: MirrorAvgAggregateOutputType | null
  _sum: MirrorSumAggregateOutputType | null
  _min: MirrorMinAggregateOutputType | null
  _max: MirrorMaxAggregateOutputType | null
}

type GetMirrorGroupByPayload<T extends MirrorGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MirrorGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MirrorGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MirrorGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MirrorGroupByOutputType[P]>
      }
    >
  >



export type MirrorWhereInput = {
  AND?: Prisma.MirrorWhereInput | Prisma.MirrorWhereInput[]
  OR?: Prisma.MirrorWhereInput[]
  NOT?: Prisma.MirrorWhereInput | Prisma.MirrorWhereInput[]
  id?: Prisma.IntFilter<"Mirror"> | number
  name?: Prisma.StringFilter<"Mirror"> | string
  code?: Prisma.StringFilter<"Mirror"> | string
  autoRun?: Prisma.BoolFilter<"Mirror"> | boolean
  autoRunInterval?: Prisma.IntNullableFilter<"Mirror"> | number | null
  lastRun?: Prisma.DateTimeNullableFilter<"Mirror"> | Date | string | null
  lastResult?: Prisma.StringNullableFilter<"Mirror"> | string | null
}

export type MirrorOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  code?: Prisma.SortOrder
  autoRun?: Prisma.SortOrder
  autoRunInterval?: Prisma.SortOrderInput | Prisma.SortOrder
  lastRun?: Prisma.SortOrderInput | Prisma.SortOrder
  lastResult?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type MirrorWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.MirrorWhereInput | Prisma.MirrorWhereInput[]
  OR?: Prisma.MirrorWhereInput[]
  NOT?: Prisma.MirrorWhereInput | Prisma.MirrorWhereInput[]
  name?: Prisma.StringFilter<"Mirror"> | string
  code?: Prisma.StringFilter<"Mirror"> | string
  autoRun?: Prisma.BoolFilter<"Mirror"> | boolean
  autoRunInterval?: Prisma.IntNullableFilter<"Mirror"> | number | null
  lastRun?: Prisma.DateTimeNullableFilter<"Mirror"> | Date | string | null
  lastResult?: Prisma.StringNullableFilter<"Mirror"> | string | null
}, "id">

export type MirrorOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  code?: Prisma.SortOrder
  autoRun?: Prisma.SortOrder
  autoRunInterval?: Prisma.SortOrderInput | Prisma.SortOrder
  lastRun?: Prisma.SortOrderInput | Prisma.SortOrder
  lastResult?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.MirrorCountOrderByAggregateInput
  _avg?: Prisma.MirrorAvgOrderByAggregateInput
  _max?: Prisma.MirrorMaxOrderByAggregateInput
  _min?: Prisma.MirrorMinOrderByAggregateInput
  _sum?: Prisma.MirrorSumOrderByAggregateInput
}

export type MirrorScalarWhereWithAggregatesInput = {
  AND?: Prisma.MirrorScalarWhereWithAggregatesInput | Prisma.MirrorScalarWhereWithAggregatesInput[]
  OR?: Prisma.MirrorScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MirrorScalarWhereWithAggregatesInput | Prisma.MirrorScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Mirror"> | number
  name?: Prisma.StringWithAggregatesFilter<"Mirror"> | string
  code?: Prisma.StringWithAggregatesFilter<"Mirror"> | string
  autoRun?: Prisma.BoolWithAggregatesFilter<"Mirror"> | boolean
  autoRunInterval?: Prisma.IntNullableWithAggregatesFilter<"Mirror"> | number | null
  lastRun?: Prisma.DateTimeNullableWithAggregatesFilter<"Mirror"> | Date | string | null
  lastResult?: Prisma.StringNullableWithAggregatesFilter<"Mirror"> | string | null
}

export type MirrorCreateInput = {
  name: string
  code: string
  autoRun?: boolean
  autoRunInterval?: number | null
  lastRun?: Date | string | null
  lastResult?: string | null
}

export type MirrorUncheckedCreateInput = {
  id?: number
  name: string
  code: string
  autoRun?: boolean
  autoRunInterval?: number | null
  lastRun?: Date | string | null
  lastResult?: string | null
}

export type MirrorUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  autoRun?: Prisma.BoolFieldUpdateOperationsInput | boolean
  autoRunInterval?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lastRun?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastResult?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MirrorUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  autoRun?: Prisma.BoolFieldUpdateOperationsInput | boolean
  autoRunInterval?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lastRun?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastResult?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MirrorCreateManyInput = {
  id?: number
  name: string
  code: string
  autoRun?: boolean
  autoRunInterval?: number | null
  lastRun?: Date | string | null
  lastResult?: string | null
}

export type MirrorUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  autoRun?: Prisma.BoolFieldUpdateOperationsInput | boolean
  autoRunInterval?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lastRun?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastResult?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MirrorUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  autoRun?: Prisma.BoolFieldUpdateOperationsInput | boolean
  autoRunInterval?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lastRun?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastResult?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MirrorCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  code?: Prisma.SortOrder
  autoRun?: Prisma.SortOrder
  autoRunInterval?: Prisma.SortOrder
  lastRun?: Prisma.SortOrder
  lastResult?: Prisma.SortOrder
}

export type MirrorAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  autoRunInterval?: Prisma.SortOrder
}

export type MirrorMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  code?: Prisma.SortOrder
  autoRun?: Prisma.SortOrder
  autoRunInterval?: Prisma.SortOrder
  lastRun?: Prisma.SortOrder
  lastResult?: Prisma.SortOrder
}

export type MirrorMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  code?: Prisma.SortOrder
  autoRun?: Prisma.SortOrder
  autoRunInterval?: Prisma.SortOrder
  lastRun?: Prisma.SortOrder
  lastResult?: Prisma.SortOrder
}

export type MirrorSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  autoRunInterval?: Prisma.SortOrder
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}



export type MirrorSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  code?: boolean
  autoRun?: boolean
  autoRunInterval?: boolean
  lastRun?: boolean
  lastResult?: boolean
}, ExtArgs["result"]["mirror"]>

export type MirrorSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  code?: boolean
  autoRun?: boolean
  autoRunInterval?: boolean
  lastRun?: boolean
  lastResult?: boolean
}, ExtArgs["result"]["mirror"]>

export type MirrorSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  code?: boolean
  autoRun?: boolean
  autoRunInterval?: boolean
  lastRun?: boolean
  lastResult?: boolean
}, ExtArgs["result"]["mirror"]>

export type MirrorSelectScalar = {
  id?: boolean
  name?: boolean
  code?: boolean
  autoRun?: boolean
  autoRunInterval?: boolean
  lastRun?: boolean
  lastResult?: boolean
}

export type MirrorOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "code" | "autoRun" | "autoRunInterval" | "lastRun" | "lastResult", ExtArgs["result"]["mirror"]>

export type $MirrorPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Mirror"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    code: string
    autoRun: boolean
    autoRunInterval: number | null
    lastRun: Date | null
    lastResult: string | null
  }, ExtArgs["result"]["mirror"]>
  composites: {}
}

export type MirrorGetPayload<S extends boolean | null | undefined | MirrorDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MirrorPayload, S>

export type MirrorCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MirrorFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MirrorCountAggregateInputType | true
  }

export interface MirrorDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Mirror'], meta: { name: 'Mirror' } }
  /**
   * Find zero or one Mirror that matches the filter.
   * @param {MirrorFindUniqueArgs} args - Arguments to find a Mirror
   * @example
   * // Get one Mirror
   * const mirror = await prisma.mirror.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MirrorFindUniqueArgs>(args: Prisma.SelectSubset<T, MirrorFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MirrorClient<runtime.Types.Result.GetResult<Prisma.$MirrorPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Mirror that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MirrorFindUniqueOrThrowArgs} args - Arguments to find a Mirror
   * @example
   * // Get one Mirror
   * const mirror = await prisma.mirror.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MirrorFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MirrorFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MirrorClient<runtime.Types.Result.GetResult<Prisma.$MirrorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Mirror that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MirrorFindFirstArgs} args - Arguments to find a Mirror
   * @example
   * // Get one Mirror
   * const mirror = await prisma.mirror.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MirrorFindFirstArgs>(args?: Prisma.SelectSubset<T, MirrorFindFirstArgs<ExtArgs>>): Prisma.Prisma__MirrorClient<runtime.Types.Result.GetResult<Prisma.$MirrorPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Mirror that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MirrorFindFirstOrThrowArgs} args - Arguments to find a Mirror
   * @example
   * // Get one Mirror
   * const mirror = await prisma.mirror.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MirrorFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MirrorFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MirrorClient<runtime.Types.Result.GetResult<Prisma.$MirrorPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Mirrors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MirrorFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Mirrors
   * const mirrors = await prisma.mirror.findMany()
   * 
   * // Get first 10 Mirrors
   * const mirrors = await prisma.mirror.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const mirrorWithIdOnly = await prisma.mirror.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MirrorFindManyArgs>(args?: Prisma.SelectSubset<T, MirrorFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MirrorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Mirror.
   * @param {MirrorCreateArgs} args - Arguments to create a Mirror.
   * @example
   * // Create one Mirror
   * const Mirror = await prisma.mirror.create({
   *   data: {
   *     // ... data to create a Mirror
   *   }
   * })
   * 
   */
  create<T extends MirrorCreateArgs>(args: Prisma.SelectSubset<T, MirrorCreateArgs<ExtArgs>>): Prisma.Prisma__MirrorClient<runtime.Types.Result.GetResult<Prisma.$MirrorPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Mirrors.
   * @param {MirrorCreateManyArgs} args - Arguments to create many Mirrors.
   * @example
   * // Create many Mirrors
   * const mirror = await prisma.mirror.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MirrorCreateManyArgs>(args?: Prisma.SelectSubset<T, MirrorCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Mirrors and returns the data saved in the database.
   * @param {MirrorCreateManyAndReturnArgs} args - Arguments to create many Mirrors.
   * @example
   * // Create many Mirrors
   * const mirror = await prisma.mirror.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Mirrors and only return the `id`
   * const mirrorWithIdOnly = await prisma.mirror.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MirrorCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MirrorCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MirrorPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Mirror.
   * @param {MirrorDeleteArgs} args - Arguments to delete one Mirror.
   * @example
   * // Delete one Mirror
   * const Mirror = await prisma.mirror.delete({
   *   where: {
   *     // ... filter to delete one Mirror
   *   }
   * })
   * 
   */
  delete<T extends MirrorDeleteArgs>(args: Prisma.SelectSubset<T, MirrorDeleteArgs<ExtArgs>>): Prisma.Prisma__MirrorClient<runtime.Types.Result.GetResult<Prisma.$MirrorPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Mirror.
   * @param {MirrorUpdateArgs} args - Arguments to update one Mirror.
   * @example
   * // Update one Mirror
   * const mirror = await prisma.mirror.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MirrorUpdateArgs>(args: Prisma.SelectSubset<T, MirrorUpdateArgs<ExtArgs>>): Prisma.Prisma__MirrorClient<runtime.Types.Result.GetResult<Prisma.$MirrorPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Mirrors.
   * @param {MirrorDeleteManyArgs} args - Arguments to filter Mirrors to delete.
   * @example
   * // Delete a few Mirrors
   * const { count } = await prisma.mirror.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MirrorDeleteManyArgs>(args?: Prisma.SelectSubset<T, MirrorDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Mirrors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MirrorUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Mirrors
   * const mirror = await prisma.mirror.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MirrorUpdateManyArgs>(args: Prisma.SelectSubset<T, MirrorUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Mirrors and returns the data updated in the database.
   * @param {MirrorUpdateManyAndReturnArgs} args - Arguments to update many Mirrors.
   * @example
   * // Update many Mirrors
   * const mirror = await prisma.mirror.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Mirrors and only return the `id`
   * const mirrorWithIdOnly = await prisma.mirror.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MirrorUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MirrorUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MirrorPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Mirror.
   * @param {MirrorUpsertArgs} args - Arguments to update or create a Mirror.
   * @example
   * // Update or create a Mirror
   * const mirror = await prisma.mirror.upsert({
   *   create: {
   *     // ... data to create a Mirror
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Mirror we want to update
   *   }
   * })
   */
  upsert<T extends MirrorUpsertArgs>(args: Prisma.SelectSubset<T, MirrorUpsertArgs<ExtArgs>>): Prisma.Prisma__MirrorClient<runtime.Types.Result.GetResult<Prisma.$MirrorPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Mirrors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MirrorCountArgs} args - Arguments to filter Mirrors to count.
   * @example
   * // Count the number of Mirrors
   * const count = await prisma.mirror.count({
   *   where: {
   *     // ... the filter for the Mirrors we want to count
   *   }
   * })
  **/
  count<T extends MirrorCountArgs>(
    args?: Prisma.Subset<T, MirrorCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MirrorCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Mirror.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MirrorAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MirrorAggregateArgs>(args: Prisma.Subset<T, MirrorAggregateArgs>): Prisma.PrismaPromise<GetMirrorAggregateType<T>>

  /**
   * Group by Mirror.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MirrorGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MirrorGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MirrorGroupByArgs['orderBy'] }
      : { orderBy?: MirrorGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MirrorGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMirrorGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Mirror model
 */
readonly fields: MirrorFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Mirror.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MirrorClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Mirror model
 */
export interface MirrorFieldRefs {
  readonly id: Prisma.FieldRef<"Mirror", 'Int'>
  readonly name: Prisma.FieldRef<"Mirror", 'String'>
  readonly code: Prisma.FieldRef<"Mirror", 'String'>
  readonly autoRun: Prisma.FieldRef<"Mirror", 'Boolean'>
  readonly autoRunInterval: Prisma.FieldRef<"Mirror", 'Int'>
  readonly lastRun: Prisma.FieldRef<"Mirror", 'DateTime'>
  readonly lastResult: Prisma.FieldRef<"Mirror", 'String'>
}
    

// Custom InputTypes
/**
 * Mirror findUnique
 */
export type MirrorFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mirror
   */
  select?: Prisma.MirrorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mirror
   */
  omit?: Prisma.MirrorOmit<ExtArgs> | null
  /**
   * Filter, which Mirror to fetch.
   */
  where: Prisma.MirrorWhereUniqueInput
}

/**
 * Mirror findUniqueOrThrow
 */
export type MirrorFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mirror
   */
  select?: Prisma.MirrorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mirror
   */
  omit?: Prisma.MirrorOmit<ExtArgs> | null
  /**
   * Filter, which Mirror to fetch.
   */
  where: Prisma.MirrorWhereUniqueInput
}

/**
 * Mirror findFirst
 */
export type MirrorFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mirror
   */
  select?: Prisma.MirrorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mirror
   */
  omit?: Prisma.MirrorOmit<ExtArgs> | null
  /**
   * Filter, which Mirror to fetch.
   */
  where?: Prisma.MirrorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Mirrors to fetch.
   */
  orderBy?: Prisma.MirrorOrderByWithRelationInput | Prisma.MirrorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Mirrors.
   */
  cursor?: Prisma.MirrorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Mirrors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Mirrors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Mirrors.
   */
  distinct?: Prisma.MirrorScalarFieldEnum | Prisma.MirrorScalarFieldEnum[]
}

/**
 * Mirror findFirstOrThrow
 */
export type MirrorFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mirror
   */
  select?: Prisma.MirrorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mirror
   */
  omit?: Prisma.MirrorOmit<ExtArgs> | null
  /**
   * Filter, which Mirror to fetch.
   */
  where?: Prisma.MirrorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Mirrors to fetch.
   */
  orderBy?: Prisma.MirrorOrderByWithRelationInput | Prisma.MirrorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Mirrors.
   */
  cursor?: Prisma.MirrorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Mirrors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Mirrors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Mirrors.
   */
  distinct?: Prisma.MirrorScalarFieldEnum | Prisma.MirrorScalarFieldEnum[]
}

/**
 * Mirror findMany
 */
export type MirrorFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mirror
   */
  select?: Prisma.MirrorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mirror
   */
  omit?: Prisma.MirrorOmit<ExtArgs> | null
  /**
   * Filter, which Mirrors to fetch.
   */
  where?: Prisma.MirrorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Mirrors to fetch.
   */
  orderBy?: Prisma.MirrorOrderByWithRelationInput | Prisma.MirrorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Mirrors.
   */
  cursor?: Prisma.MirrorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Mirrors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Mirrors.
   */
  skip?: number
  distinct?: Prisma.MirrorScalarFieldEnum | Prisma.MirrorScalarFieldEnum[]
}

/**
 * Mirror create
 */
export type MirrorCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mirror
   */
  select?: Prisma.MirrorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mirror
   */
  omit?: Prisma.MirrorOmit<ExtArgs> | null
  /**
   * The data needed to create a Mirror.
   */
  data: Prisma.XOR<Prisma.MirrorCreateInput, Prisma.MirrorUncheckedCreateInput>
}

/**
 * Mirror createMany
 */
export type MirrorCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Mirrors.
   */
  data: Prisma.MirrorCreateManyInput | Prisma.MirrorCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Mirror createManyAndReturn
 */
export type MirrorCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mirror
   */
  select?: Prisma.MirrorSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Mirror
   */
  omit?: Prisma.MirrorOmit<ExtArgs> | null
  /**
   * The data used to create many Mirrors.
   */
  data: Prisma.MirrorCreateManyInput | Prisma.MirrorCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Mirror update
 */
export type MirrorUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mirror
   */
  select?: Prisma.MirrorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mirror
   */
  omit?: Prisma.MirrorOmit<ExtArgs> | null
  /**
   * The data needed to update a Mirror.
   */
  data: Prisma.XOR<Prisma.MirrorUpdateInput, Prisma.MirrorUncheckedUpdateInput>
  /**
   * Choose, which Mirror to update.
   */
  where: Prisma.MirrorWhereUniqueInput
}

/**
 * Mirror updateMany
 */
export type MirrorUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Mirrors.
   */
  data: Prisma.XOR<Prisma.MirrorUpdateManyMutationInput, Prisma.MirrorUncheckedUpdateManyInput>
  /**
   * Filter which Mirrors to update
   */
  where?: Prisma.MirrorWhereInput
  /**
   * Limit how many Mirrors to update.
   */
  limit?: number
}

/**
 * Mirror updateManyAndReturn
 */
export type MirrorUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mirror
   */
  select?: Prisma.MirrorSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Mirror
   */
  omit?: Prisma.MirrorOmit<ExtArgs> | null
  /**
   * The data used to update Mirrors.
   */
  data: Prisma.XOR<Prisma.MirrorUpdateManyMutationInput, Prisma.MirrorUncheckedUpdateManyInput>
  /**
   * Filter which Mirrors to update
   */
  where?: Prisma.MirrorWhereInput
  /**
   * Limit how many Mirrors to update.
   */
  limit?: number
}

/**
 * Mirror upsert
 */
export type MirrorUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mirror
   */
  select?: Prisma.MirrorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mirror
   */
  omit?: Prisma.MirrorOmit<ExtArgs> | null
  /**
   * The filter to search for the Mirror to update in case it exists.
   */
  where: Prisma.MirrorWhereUniqueInput
  /**
   * In case the Mirror found by the `where` argument doesn't exist, create a new Mirror with this data.
   */
  create: Prisma.XOR<Prisma.MirrorCreateInput, Prisma.MirrorUncheckedCreateInput>
  /**
   * In case the Mirror was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MirrorUpdateInput, Prisma.MirrorUncheckedUpdateInput>
}

/**
 * Mirror delete
 */
export type MirrorDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mirror
   */
  select?: Prisma.MirrorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mirror
   */
  omit?: Prisma.MirrorOmit<ExtArgs> | null
  /**
   * Filter which Mirror to delete.
   */
  where: Prisma.MirrorWhereUniqueInput
}

/**
 * Mirror deleteMany
 */
export type MirrorDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Mirrors to delete
   */
  where?: Prisma.MirrorWhereInput
  /**
   * Limit how many Mirrors to delete.
   */
  limit?: number
}

/**
 * Mirror without action
 */
export type MirrorDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mirror
   */
  select?: Prisma.MirrorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mirror
   */
  omit?: Prisma.MirrorOmit<ExtArgs> | null
}
