
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Account: 'Account',
  Session: 'Session',
  AuthorizationInstance: 'AuthorizationInstance',
  AuthorizationChallenge: 'AuthorizationChallenge',
  PermissionInstance: 'PermissionInstance',
  AssetType: 'AssetType',
  Asset: 'Asset',
  Container: 'Container',
  App: 'App'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const AccountScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  api: 'api',
  secondFactor: 'secondFactor',
  password: 'password',
  accounts: 'accounts'
} as const

export type AccountScalarFieldEnum = (typeof AccountScalarFieldEnum)[keyof typeof AccountScalarFieldEnum]


export const SessionScalarFieldEnum = {
  id: 'id',
  subject: 'subject',
  expire: 'expire',
  created: 'created'
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]


export const AuthorizationInstanceScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  appId: 'appId',
  refreshToken: 'refreshToken',
  refreshTokenExpire: 'refreshTokenExpire'
} as const

export type AuthorizationInstanceScalarFieldEnum = (typeof AuthorizationInstanceScalarFieldEnum)[keyof typeof AuthorizationInstanceScalarFieldEnum]


export const AuthorizationChallengeScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  appId: 'appId',
  authorizationCode: 'authorizationCode',
  challenge: 'challenge',
  created: 'created'
} as const

export type AuthorizationChallengeScalarFieldEnum = (typeof AuthorizationChallengeScalarFieldEnum)[keyof typeof AuthorizationChallengeScalarFieldEnum]


export const PermissionInstanceScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  containerId: 'containerId',
  appId: 'appId',
  identifier: 'identifier',
  assetId: 'assetId'
} as const

export type PermissionInstanceScalarFieldEnum = (typeof PermissionInstanceScalarFieldEnum)[keyof typeof PermissionInstanceScalarFieldEnum]


export const AssetTypeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  fields: 'fields'
} as const

export type AssetTypeScalarFieldEnum = (typeof AssetTypeScalarFieldEnum)[keyof typeof AssetTypeScalarFieldEnum]


export const AssetScalarFieldEnum = {
  id: 'id',
  name: 'name',
  typeId: 'typeId',
  fields: 'fields'
} as const

export type AssetScalarFieldEnum = (typeof AssetScalarFieldEnum)[keyof typeof AssetScalarFieldEnum]


export const ContainerScalarFieldEnum = {
  id: 'id',
  name: 'name',
  assets: 'assets',
  apps: 'apps'
} as const

export type ContainerScalarFieldEnum = (typeof ContainerScalarFieldEnum)[keyof typeof ContainerScalarFieldEnum]


export const AppScalarFieldEnum = {
  id: 'id',
  name: 'name',
  url: 'url',
  oidcAuthCodeUrl: 'oidcAuthCodeUrl',
  token: 'token',
  permissions: 'permissions',
  webFetch: 'webFetch'
} as const

export type AppScalarFieldEnum = (typeof AppScalarFieldEnum)[keyof typeof AppScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: 'JsonNull'
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const JsonNullValueFilter = {
  DbNull: 'DbNull',
  JsonNull: 'JsonNull',
  AnyNull: 'AnyNull'
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

